coral-xyz/backpack

- packages/app-extension/src/components/Onboarding/CheckInviteCodeForm.tsx
- packages/app-extension/src/components/Onboarding/index.tsx
- packages/background/src/backend/core.ts
a couple of things that will be improved later -
- adds a bit of local validation for invite codes & usernames to reduce network requests
- if there's an issue during onboarding e.g. username was available at the start, but isn't when user reaches the end of signup, the keystore is reset and the page refreshes, this is a brutal and very temporary measure to prevent inconsistent state between the extension & reef backend
> add some local validation during onboarding

- packages/app-extension/src/components/Unlocked/Balances/RecentActivity.tsx
- packages/recoil/src/atoms/recent-transactions.tsx
Handle rejected promises so wallet doesn't crash if these queries fail.
Related #877
> dont crash on rejected ethereum recent activity queries

- packages/app-extension/src/components/common/index.tsx
This do anything? Looks like it just gets passed down to the MUI button component and generates a console error.
> remove is secondary prop from button

- packages/app-extension/src/components/Unlocked/Settings/Preferences/Ethereum/Connection.tsx
Remove the (Beta) tag from Mainnet (Beta) in user settings/preferences for Ethereum RPC Connection.
> remove (Beta) from mainnet eth rpc connection

- packages/react-xnft-renderer/src/Component.tsx
- packages/react-xnft/src/reconciler.ts
The PR adds `text area` props to the `TextField` component. 
This is in line with the react-native API - https://reactnative.dev/docs/textinput#multiline
```js
<TextField
multiline={true}
numberOfLines={3}
onChange={(e) => {setVal(e.data.value)}}
value={val}
placeholder={"placeholder"}
/>
```
Closes https://github.com/coral-xyz/backpack/issues/888
> Added textarea props to textfield component

- packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx
The PR catches errors in `ApproveTransactionRequest` that is causing unhandled rejections to remain uncaught. This prevents application developers from knowing if the underlying transaction failed.
I've now called the `onReject` callback in case the background requests fails which will cause `window.xnft.solana.send` throw, which the application developer can then handle according to their app.
Does it make sense to propagate the `error message` to the developer? Right now the `error message` that reaches them is `user rejected signature request` from [here](https://github.com/coral-xyz/backpack/blob/master/packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx#L124)
Closes #810
> Catches transaction errors in ApproveTransactionRequest

- packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx
Follow up from https://github.com/coral-xyz/backpack/pull/904 to propagate the error message to the developer.
The PR also catches the error in `SignAllTransactionsRequest` which was missing in the existing PR
> Surfaced error message to user

- packages/app-extension/src/components/common/Account/CreatePassword.tsx
it feels like having a single button shared between both fields is a bit simpler, but maybe a bad idea?
https://user-images.githubusercontent.com/101902546/193170469-97c0832e-c98b-4ca8-b45d-7fac51c67ffc.mov
> share toggle password visibility button with confirmation field

- packages/react-xnft/src/sdk/Tab.tsx
Export useTabContext so that it can be used for navigation by other UIs.
> Export useTabContext

- packages/background/src/frontend/server-injected.ts
- packages/provider-core/src/provider-ethereum.ts
Restrict connect requests to one per origin and handle `eth_accounts` requests separately from `eth_requestAccounts`.
Closes https://github.com/coral-xyz/backpack/issues/829
Closes https://github.com/coral-xyz/backpack/issues/965
> single connect per origin and handle eth_accounts separately

- backend/workers/xnft-wrapper/package.json
- package.json
- yarn.lock
fixes issue with a broken release of `@miniflare/durable-objects@2.5.1`
```
Error: Cannot find module 'coral-xyz/backpack/node_modules/miniflare/node_modules/@miniflare/durable-objects/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
```
> use wrangler ^2.1.9 across monorepo

- packages/app-extension/src/components/Unlocked/Settings/index.tsx
This displays a new error message to the user when they import a private key that has already been added
The useWalletPublicKeys hook was added to the ImportSecretKey component. The validateSecretKey function was changed to accept the existing keys as a parameter, and to throw an error if the key is invalid. Previously the validateSecretKey function would return false to indicate an invalid secret key but now it throws an error
Please let me know what additional information I should provide, changes that need to be made to the code, or additional screens that need to have this check added to them
> When validating secret key throw error if has already been added

- packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx
Noticed that when I had a bad internet and I tried approving a transaction, the popup that should appear would not appear and I would only see a `close` button at the bottom 
This would happen because `useTransactionData` is async and the component wouldn't render until the hook returns - https://github.com/coral-xyz/backpack/blob/master/packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx#L305
The PR fallbacks the UI to the transaction popup with buttons disabled and a loader until the hook returns.
> Fixed stuck popups while approving requests

- packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
This removes the minimum height on the inner image and adds flexbox centering to the container image
The image was previously squished because the inner image had a minimum height the same as the container. An image with a wide aspect ratio needs to have a smaller height than its container or the edges overflow. In this case the edges did not overflow and the image got squished because the image also has a width set to 100%.
Images with a small aspect ratio are not affected by this change as their height will be larger than the container when their width is 100%.
> fix squished NFTs

- packages/recoil/src/hooks/useTransactionData.tsx
Closes https://github.com/coral-xyz/backpack/issues/992
Turns out this happens because the `populateTransaction` call [here](https://github.com/coral-xyz/backpack/blob/master/packages/recoil/src/hooks/useTransactionData.tsx#L90) fails in `ethers.js` [here](https://github.com/ethers-io/ethers.js/blob/01aea705ce60b1c42d2f465b162cb339a0e94392/packages/abstract-signer/src.ts/index.ts#L301). 
I've added a default `gas limit` which we anyways overwrite later on [here](https://github.com/coral-xyz/backpack/blob/master/packages/recoil/src/hooks/useTransactionData.tsx#L118).
> Fixed eth error when `estimateGas` fails

- packages/provider-injection/package.json
This PR updates the Wallet Standard wrapper for Backpack. Internally, there are some API changes, and I've updated the Backpack icon to the same as the one used by Wallet Adapter. This has no effect on `window.backpack` or its consumers.
> Update @wallet-standard/wallets-backpack to 0.1.0-alpha.7

- .github/workflows/pull_request.yml
- packages/xnft-cli/package.json
- remove manual github actions build steps for `common-public` and `common`
- add `react-xnft` as a devDependency of `xnft-cli` so that it and its dependencies are registered in the turborepo dependency graph (turborepo ignores peerDependencies)
> fix deps so that packages/common* gets built before being used

- packages/provider-injection/package.json
- packages/provider-injection/src/index.ts
This updates to the latest `@wallet-standard/wallets-backpack` release. This may be the final test release of the package before it will be inlined with Backpack in this repo. The guard around the register function is no longer needed (it does this internally now). Everything works in testing so far.
> Update wallet standard wrapper

- packages/provider-core/src/provider-ethereum.ts
Closes https://github.com/coral-xyz/backpack/issues/1044
The PR converts `handleEthAccounts` to an arrow fn as it was being bound to this before https://github.com/coral-xyz/backpack/pull/925 . 
Wasn't able to reproduce the error locally but I think this should fix it. @tomlinton could you help me confirm the fix if you can still recreate this locally?
> Make all fns in ethereum-provider arrow fns

- examples/xnft/custom-components/package.json
- examples/xnft/custom-components/src/app.tsx
- examples/xnft/custom-components/src/components/Audio.tsx
- examples/xnft/custom-components/src/components/Centralize.tsx
- examples/xnft/custom-components/src/components/Video.tsx
- examples/xnft/custom-components/src/index.tsx
- packages/react-xnft-renderer/src/Component.tsx
- packages/react-xnft/src/elements.tsx
- packages/react-xnft/src/reconciler.ts
The PR adds a new `Custom` type in our renderer that allows users to define their own custom components.
I've kept this slightly different from the `createElement` approach that `react-native-web` uses so that we can contain all custom components in the `Custom` node type. That way if we have native renderers in the future, we can chose to either ignore these components completely or write native renderers based on the `component` property. This'll ensure that the xnfts don't completely break when rendering it on a native mobile device.
This will unblock users that are building xnfts for now, but we would need to figure out the best way to integrate this in native once we have RN support.
Closes https://github.com/coral-xyz/backpack/issues/1030 , …
> Custom types in reconciler

- packages/provider-core/src/request-manager.ts
This commit fixes issue (#1081 ). I tried to fix it by saving url, in case parent object is true. Maybe this is not the best solution for other cases.
> window.xnft object unable to sign transactions after changing urls fix.

- packages/background/src/backend/keyring/index.ts
Closes https://github.com/coral-xyz/backpack/issues/1092
An incorrect password input [would update](https://github.com/coral-xyz/backpack/blob/master/packages/background/src/backend/keyring/index.ts#L357) `lastUsedTs` which made the keyring think it was unlocked even though no data had been loaded from the encrypted store. On the next unlock it would try and access data it expected to be there but the `blockchains` map would be empty.
> incorrect password keyring load state fix

- packages/app-extension/src/components/Unlocked/Settings/YourAccount/ChangePassword.tsx
Resolves #250
If you want we could modify line 60 to remove `newPw1.trim() === ""` but I figured it doesn't hurt to leave it in.
> chore: disable change password button when password empty

- packages/background/src/backend/core.ts
- packages/background/src/backend/solana-connection.ts
Pass activeWallet with the connection url event (which will be null if blockchain is disabled) and don't restart polling if it is disabled.
> proper handling of connection url changes if blockchain disabled

- packages/react-xnft-dom-renderer/.npmignore
The `dist` folder isn't being published now since it's part of `.gitignore`. 
`.npmignore` overrides it.
> Added npmignore

- packages/app-extension/src/components/Unlocked/Settings/Preferences/TrustedSites.tsx
- packages/app-extension/src/components/Unlocked/Settings/Preferences/index.tsx
- packages/app-extension/src/components/Unlocked/Settings/index.tsx
Fixes #1129 
- Changed "Trusted Apps" to "Trusted Sites" everywhere in the UI
- renamed preferences text and files to reflect the above
> Copy update refactor from "Trusted apps" to "Trusted sites"

- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ConnectHardware/ConnectHardwareImport.tsx
- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ConnectHardware/index.tsx
- packages/app-extension/src/options/Options.tsx
Adds a wrapper component around `<ConnectHardware />` that does imports into the keyring store so we can reuse the `<ConnectHardware />` component for the onboarding flow where the account should not be imported immediately but at keyring store creation.
> add an import accounts wrapper around the ledger flow for reuse

- packages/common-public/src/utils.ts
Ensure when we're proxying images, we use `fit` resizing vs `fill` to avoid pixelating/stretching the image
Closes #1175
> fill => fit for proxying images

- packages/xnft-cli/index.js
xnft-quickstart has `xnft-cli` as a dependency. Now `xnft-cli` expects a `renderer.js` file from `react-xnft-dom-renderer` which isn't a dependency of `xnft-quickstart` (rightfully so, since we dont want users to write their own renderers).
This PR fallsback to the latest renderer inside `xnft-cli` if `renderer.js` isn't found.
> Fixed xnft-quickstart

- packages/provider-injection/package.json
- packages/wallet-standard/package.json
Changes package version for `@coral-xyz/wallet-standard` so that `provider-injection` uses the version from the repo.
cc @jordansexton having alphabets (`rc`) seems to be confusing the mono repo to include `@coral-xyz/wallet-standard` hence changed the version to `0.1.0`
> Fixed CI/CD

- packages/react-xnft/src/ReactDom.ts
Closes https://github.com/coral-xyz/backpack/issues/1202
This happens because the `onRender` function doesn't get set immediately, and hence we throw the `render fn not found` error. 
The PR adds a queue where we queue these up and only throw if the render fn doesn't get set of over a second.
> Fixes renders

- examples/xnft/app/src/app.tsx
- examples/xnft/mango/src/app.tsx
- packages/app-extension/src/components/Unlocked/Apps/Plugin.tsx
- packages/app-extension/src/plugin/Renderer.tsx
- packages/common/src/plugin.ts
- packages/common/src/types.ts
- packages/provider-core/src/index.ts
- packages/provider-core/src/provider-ethereum-xnft.ts
- packages/provider-core/src/provider-solana-xnft.ts
- packages/provider-core/src/root-provider-xnft.ts
- packages/provider-injection/src/index.ts
- packages/react-xnft-dom-renderer/src/App.tsx
- packages/react-xnft-dom-renderer/src/Context.tsx
- packages/react-xnft/package.json
- packages/react-xnft/src/EVENTS.ts
- packages/react-xnft/src/hooks.tsx
- packages/react-xnft/src/index.ts
- packages/react-xnft/src/reconciler.ts
Closes https://github.com/coral-xyz/backpack/issues/1162 
Closes https://github.com/coral-xyz/backpack/issues/929
Added an example to show the new `username` and `avatarUrl` functionality (username is empty because I tested it locally) - 
This will be a breaking change for folks using `window.xnft.send`, they'll need to replace these with `window.xnft.solana.send`.
Will have a few follow up PRs in this repo for `gh-pages` branch and [xnft-program-library](https://github.com/coral-xyz/xnft-program-library) to fix those for our internal examples
> Fixed root provider, added metadata

- packages/recoil/src/hooks/useTransactionData.tsx
fix `Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber", value="13437519875157330", code=NUMERIC_FAULT, version=bignumber/5.7.0)`
when try to sign ETH tx
> fix BigNumber formatting decimal number

- packages/common-public/src/types.ts
- packages/common/src/plugin.ts
- packages/common/src/types.ts
- packages/provider-core/package.json
- packages/provider-core/src/root-provider-xnft.ts
- packages/react-xnft-dom-renderer/package.json
- packages/react-xnft-dom-renderer/src/App.tsx
- packages/react-xnft-dom-renderer/src/Context.tsx
- packages/react-xnft/package.json
- packages/react-xnft/src/hooks.tsx
The PR moves `XnftMetadata` to common public to remove `@coral-xyz/common` dependency from `react-xnft`
> XnftMetadata to common-public

- packages/provider-core/src/chained-request-manager.ts
Issue raised by user here - https://discord.com/channels/985994296337498182/1011846320677462137/1034115909532536832
When using `react-xnft` natively, we don't need to pass in `iframeIdentifier` of the parent iframe
> Fixed chain requests

- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx
- packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/index.tsx
1) Clicking on the created wallet correctly takes you back to the Balances tab
2) Removes triple dots menu from "Wallet Created":
3) Continues to show triple dots menu from "Your Account / Edit Wallets":
> wallet create fixes

- packages/app-extension/src/components/common/Layout/Router.tsx
This was happening because `pluginProps` would linger as a query param in the URL causing the xnft opened from `xnft.gg` to keep lingering even after being closed.
Closes https://github.com/coral-xyz/backpack/issues/1275
Closes https://github.com/coral-xyz/backpack/issues/1273
> Fixes redirects

- packages/app-extension/src/components/Onboarding/pages/OnboardAccount.tsx
Don't prompt for signing when there is nothing to sign (because usernames/invite codes are disabled).
Closes https://github.com/coral-xyz/backpack/issues/1300
> disable hardware signing if username feature is disabled

- packages/app-extension/src/components/Onboarding/pages/HardwareOnboard.tsx
If require signature is disabled the import accounts component is the last step, so it should call onComplete instead of next step.
> fix import flow with require signature disabled in onboarding

- .github/workflows/pull_requests_and_merges.yml
if this works, we could consider changing references in the project and external examples from `@coral-xyz/xnft-cli` to `xnft`
> publish xnft-cli package to `xnft` on npm

- packages/app-extension/src/components/Onboarding/pages/InviteCodeForm.tsx
Follow up from https://github.com/coral-xyz/backpack/pull/1345 to use the new `TextInput` designs and show error messages when there is an erroneous input
> New text input for invite code

- packages/app-extension/src/components/Onboarding/pages/RecoverAccountUsernameForm.tsx
Found another input where we were using the old design when I went through the recovery flow.
> Moved username input to new design

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
- packages/app-extension/src/components/common/Inputs.tsx
- packages/app-extension/src/components/common/TokenInput.tsx
Closes https://github.com/coral-xyz/backpack/issues/1343.
Note: We should probably get rid of the MUI `margin="dense"` everywhere to avoid more pain with undesired padding. I tried this but it causes more UI regressions so punting for now.
> fix form margin

- packages/common/src/ethereum/background-provider.ts
The provider will query the network itself if its not provided. Hard coding it can lead to connection URL/network mismatches.
> remove hardcoded mainnet chain id from ethereum xnft provider

- README.md
The updated link was found from this [tweet](https://tinyurl.com/yx8z8exr)
closes #1374
> `[docs]`: update discord invite link

- packages/background/src/frontend/server-injected.ts
Closes https://github.com/coral-xyz/backpack/issues/1371
Note: This fix now allows app developers to go through the normal `wallet connect` flow inside an `xnft` (vs using window.xnft.solana.xyz). 
Currently on sending transactions we get popups like these when the user is inside an xnft (and not native popups)
Maybe we should add logic to detect if a `solana-provider` call is made via an xnft and show native popups?
The good thing about this change is that dapps can migrate as an xnft out of the box without the need to replace their transaction calls.
> Tab exception fix

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Ethereum/index.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Solana/index.tsx
- packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
Closes https://github.com/coral-xyz/backpack/issues/1368 and some misc cleanup of unused functions/variables.
Blocked by figuring out https://github.com/coral-xyz/backpack/issues/1390
> navigate to root on send or burn nft and confirmation drawer closes

- packages/app-extension/src/components/Unlocked/Nfts/Collection.tsx
- packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
- packages/app-extension/src/components/Unlocked/Nfts/index.tsx
- packages/recoil/src/hooks/navigation.tsx
From Discord report and @euclidestesticle 
NFTs with no name parameter cause URLs like 
`popup.html#/nfts/detail?props=%7B%22nftId%22%3A%22CS6M8LDbj48jfVYiNxkx3mD449kJCrQSvEVL4RTQQhd6%22%7D&title=undefined`
JSON parsing fails on the `title=undefined` query param. This PR uses an empty string if nft name is undefined but also adds a try/catch to the query param parser so the wallet doesn't crash on bad URLs.
> fix undefined nft name crash

- packages/app-extension/src/hooks/useIsONELive.ts
Entrypoint should not show up at all when solana is disabled.
> hide ONE entrypoint when solana blockchain disabled.

- packages/react-xnft-dom-renderer/src/Component.tsx
- packages/react-xnft/src/ReactDom.ts
- packages/react-xnft/src/reconciler.ts
The PR cleans up the reconciler. 
We now pass down all props that the user gives us to the renderer. This isn't a problem anymore since all this code runs inside an IFRAME. The renderer can chose to use/throw the props it doesn't need.
This also ensures that we propagate updates for all props to the reconciler. Until now we were cherrypicking the props whose updates we want to propagate based on the NodeKind (onClick, style ...)
> Reconciler cleanup

- packages/react-xnft-dom-renderer/src/Component.tsx
`props.tw` is inaccessible when props are undefined. 
This shouldn't happen (props should always be defined), but recently saw a case where we were rendering a Button inside the `BalancesTableHead` w/o passing in props causing an exception to occur.
This PR fixes the issue in `BalancesTableHead` , also adds optional chaining to `props.tw` just to be safe.
> Made props optional

- packages/app-extension/src/components/Unlocked/Apps/Plugin.tsx
- packages/app-extension/src/components/Unlocked/Settings/Xnfts/Detail.tsx
- packages/app-extension/src/plugin/Renderer.tsx
- packages/background/src/backend/core.ts
- packages/background/src/backend/store/index.ts
- packages/background/src/backend/store/xnft-preferences.ts
- packages/background/src/frontend/server-ui.ts
- packages/common/src/constants.ts
- packages/common/src/plugin.ts
- packages/common/src/types.ts
- packages/recoil/src/atoms/preferences/index.tsx
- packages/recoil/src/atoms/preferences/xnft-preferences.tsx
- packages/recoil/src/context/Notifications.tsx
- packages/recoil/src/hooks/index.tsx
- packages/recoil/src/hooks/useXnftPreferences.tsx
The PR adds a new `toggle` to `xnft settings`. 
A user who wants to use an xnft that wants camera/mic/display access will need to enable it in these settings. 
Since the `camera/mic` permission in chrome is given on a `URL` level, once a user approves camera for the `extension`, all xnfts inside it would have camera access unless we limit it.
> Added xnft level camera/mic permissions

- backend/workers/rpc-proxy/package.json
- backend/workers/rpc-proxy/src/index.ts
- backend/workers/rpc-proxy/tsconfig.json
- backend/workers/rpc-proxy/wrangler.toml
a simple proxy for switching RPC providers remotely
only uses https://api.mainnet-beta.solana.com when RPC_URL secret is missing, i.e. local testing
> add rpc proxy worker

- README.md
- package.json
no longer tries to start code inside `./examples` dir
`yarn start` from root will now only start what's inside `./packages`
if you want to start other packages inside the workspace, go into the package directory (where there is a package.json) and run `yarn start` or `yarn dev` depending on what's available
> filter `yarn start` to only start `./packages/*`

- examples/xnft/recoil/package.json
- packages/xnft-cli/index.js
- packages/xnft-cli/package.json
Useful for users that want to polyfill node constructs.
Should make this the default in ~1 week after letting it sit for a while.
The PR also makes the build use esbuild for the `recoil` example which is breaking currently.
EDIT: Workflow is failing on the `recoil` example so will add that as a follow up when this gets merged in and deployed
> Adds esbuild to xnft-cli

- package.json
- packages/app-mobile/metro.config.js
- packages/app-mobile/package.json
- patches/expo+45.0.6.patch
- yarn.lock
- adds patch-package for expo package until its merged into master
- adds extra metro config settings to speed up mobile builds via extraNodeModules
- adds `disableHierarchicalLookup` that will allow us to upgrade to expo sdk 47 without react v18 everywhere else
> expo final monorepo changes

- packages/app-extension/src/components/Unlocked/Apps/Plugin.tsx
Previews on xnft.gg broke in https://github.com/coral-xyz/backpack/pull/1451
The PR fixes them. 
Need to figure out a better way to define preferences for xnfts that aren't yet installed (so no way of giving camera permissions currently since they wont appear in your `xnfts` section)
> Fixed preview

- packages/common/src/plugin.ts
- packages/provider-core/src/root-provider-xnft.ts
Follow up from https://github.com/coral-xyz/backpack/pull/1452 
Provides a way for xnft developers to pop out the extension.
Closes https://github.com/coral-xyz/backpack/issues/1359
> Finished popout api

- packages/react-xnft-dom-renderer/src/Component.tsx
More details here - https://discord.com/channels/985994296337498182/1011846320677462137/1041780817191514223
tl;dr is this error was thrown https://reactjs.org/docs/error-decoder.html/?invariant=137&args[]=input when we would pass in children to `input`.
> Children to undefined if no children are present

- packages/app-extension/src/components/Unlocked/Balances/Balances.tsx
- packages/common-public/src/utils.ts
Bug stemmed from commas in string values, i.e. Number("1,234.231") is NaN. Also removed error in trim failure because it's a common case and not really an error.
Closes #1015
> fix nan bugs

- packages/common/src/solana/programs/token.ts
This is a common failure for accounts with spam tokens, and is a source of red herrings for other issues, so we should hide it in the production build.
> convert tokenmetdata fetch failure into a debug log

- backend/workers/auth/src/index.ts
- packages/app-extension/src/components/Onboarding/pages/UsernameForm.tsx
fixes #1489
- just shows validation error provided from the worker to reduce duplication or confusion
- removes local MIN and MAX length constraints. They were added to avoid unnecessary network requests, but it's probably better to have the flexibility of setting those from the server anyway
- will show a generic error message so something is shown if there is a server or network issue, hopefully this never gets seen
> show error from auth worker in username form

- package.json
- yarn.lock
for the sake of ushering forward (and still giving it a shot), reduced scope to: `@babel @mui @typescript-eslint`
...expo has various issues with babel. reducing the versions reduces the time to debug
> yarn-deduplicate part 1

- backend/workers/xnft-wrapper/src/index.ts
Xnfts that haven't deployed have been hidden from xnft.gg for a while. Removing this logic that would conditionally render a warning when they were opened.
> Removed backward compatibility from existing renderer xnfts

- packages/app-extension/src/components/common/Account/ImportAccounts.tsx
- packages/background/package.json
- packages/background/src/backend/keyring/crypto.ts
- packages/common/src/crypto.ts
- yarn.lock
Adds the original derivation path used by sollet, which some people still have. Note that the path in the UI menu list item is a bit inconsistent, because the changing index is not the last one (it's the first zero). Also note, this is hidden behind a local storage flag. It's expected users run `window.localStorage.setItem('sollet', true)` to enable this feature. This derivation path was only used by a very small set of, mostly technical, early solana people.
> add deprecated derivation path

- examples/clients/simple/src/SolanaWallet.tsx
`http://api.mainnet-beta.solana.com/` is returning 403 so the simple client isn't working for testing.
> change default rpc url for mainnet in simple client

- backend/native/backpack-api/package.json
- backend/native/backpack-api/src/index.ts
- backend/native/backpack-api/src/routes/v1/notifications.ts
- backend/native/backpack-api/src/routes/v1/preferences.ts
- backend/native/backpack-api/src/routes/v1/proxy.ts
- packages/app-extension/src/api/preferences.ts
- packages/common/src/solana/programs/token.ts
Gets rid of the big red warning by proxying metadata requests from our backend servers.
Closes https://github.com/coral-xyz/backpack/issues/1227
> Proxy metadata requests to get rid of `Deceptive site warning`

- .gitignore
- examples/xnft/network-monitor/package.json
- package.json
- packages/app-extension/package.json
- packages/app-mobile/package.json
- packages/background/package.json
- packages/blockchains/common/package.json
- packages/blockchains/evm/package.json
- packages/blockchains/keyring/package.json
- packages/blockchains/solana/package.json
- packages/common-public/.eslintrc.js
- packages/common-public/package.json
- packages/common-public/src/index.ts
- packages/common-public/src/logging.ts
- packages/common-public/src/utils.ts
- packages/common/package.json
- packages/eslint-config-custom/index.js
- packages/provider-core/package.json
- packages/react-xnft-dom-renderer/package.json
- packages/react-xnft/package.json
- packages/recoil/package.json
- packages/themes/package.json
- packages/wallet-standard/.eslintignore
- packages/wallet-standard/.eslintrc
- packages/wallet-standard/package.json
- yarn.lock
eslint was very slow on save. for vscode folks, slow is the norm. for vim/emacs folks, slow is not the norm. this isn't a silver bullet, but it's an improvement
running `TIMING=1 yarn lint` resulted in discovering that `prettier/prettier` takes up a whopping second on every save (or every time eslint runs, so all the time).
`eslint-plugin-prettier` will run prettier on the underlying code first, causing the slow-down. By moving towards `eslint-config-prettier` we're able to prevent that from happening and only check prettier styles.
BEFORE:
```
@coral-xyz/wallet-standard:lint: Rule                                            | Time (ms) | Relative
@coral-xyz/wallet-standard:lint: :-----------------------------------------------|----------:|--------:
@coral-xyz/wallet-standard:lint: …
```
> eslint + prettier caching & speed improvements

- package.json
- packages/app-mobile/package.json
Removes the semicolons for windows compatability. `&&` has different semantics on windows but it should be fine.
Closes https://github.com/coral-xyz/backpack/issues/1539
> remove semicolons from postinstall commands

- package.json
Runs out of memory while running for some reason, will exclude for now and make an issue.
> exclude app-mobile from linting

- backend/workers/auth/src/index.ts
- backend/workers/auth/src/jwt.ts
if you're already testing the jwt cookie you probably want to quit and reopen your browser before testing these changes, as that will clear old cookies
- makes `jwt` cookie persist if browser is closed and reopened (it only lasted for the session before)
- fixes hono complaint about `DELETE /authenticate` not completing the response correctly
- specifies `path="/"` on the jwt cookie
- just returns an "ok" message and not the jwt in the response body
cc: @tomlinton
> ensure jwt cookie remains after ending session

- packages/background/src/backend/core.ts
This request being sent out was wrong. Noticed this today when testing that the wallet wouldn't unlock.
Might be what was causing https://github.com/coral-xyz/backpack/issues/1697 . cc @armaniferrante since you're working on that one
> Fix unlocking wallet

- backend/native/xnft-api-server/src/auth/middleware.ts
- backend/native/xnft-api-server/src/db/users.ts
- backend/native/xnft-api-server/src/v1/index.ts
- backend/native/xnft-api-server/src/v1/users.ts
Adds a new route to the `xnft-api-server` (API server that'll be used to expose things like notifications, fetching user data to xnft developers) for fetching a users details given their pubkey
> xnft api server more routes

- backend/workers/data/src/index.ts
- backend/workers/data/wrangler.toml
- backend/workers/swr-data-cache/src/index.ts
- backend/workers/swr-data-cache/src/swr.ts
- backend/workers/swr-data-cache/wrangler.toml
swr-data is a proxy cache service:
`https://swr-data.xnfts.dev/[worker]/[path]` will cache `https://[worker].backpack.workers.dev/[path]`
iE: 
-   image service: https://data.xnfts.dev/metaplex-nft/3ewQC8f3o3k7B14eWyFKTWS67axLdm9pY3XkrCBvve9E/image
- cached: https://swr-data.xnfts.dev/data/metaplex-nft/3ewQC8f3o3k7B14eWyFKTWS67axLdm9pY3XkrCBvve9E/image
The proxy looks at the Cache-Control headers of the worker response and cache the results accordingly including adhering to the stale-while-revalidate directive.
With some tweaks (POST requests are usually not cached) this works for our rpc-proxy: https://swr-data.xnfts.dev/rpc-proxy/
The cache is kept really short for the rpc : `max-age=1, s-maxage=1, stale-while-revalidate=5` so this might just work out of the box, but we might also have …
> Setup swr-data cache proxy for cf workers

- packages/background/src/backend/core.ts
- packages/background/src/backend/keyring/index.ts
- packages/background/src/backend/store/keyring.ts
Any issue with passing the uuid in instead of grabbing it from the stored keyring JSON @armaniferrante? That way there is only a single source of truth for the active uuid.
I ran into a problem with the store and the json active user uuids getting out of sync (admittedly it was some dev foolery with the service worker dying so probably not a real bug but it seems like we could avoid this class of bugs altogether).
> use a single source of truth for active user uuid

- backend/native/backpack-api/src/auth/middleware.ts
- backend/native/backpack-api/src/auth/util.ts
- backend/native/backpack-api/src/routes/v1/authenticate.ts
- backend/native/backpack-api/src/routes/v1/users.ts
- packages/app-extension/src/components/Onboarding/pages/Finish.tsx
- packages/app-extension/src/components/Unlocked/WithAuth.tsx
- packages/app-extension/src/hooks/useAuthentication.tsx
- packages/background/src/backend/core.ts
- packages/background/src/backend/keyring/index.ts
- packages/background/src/backend/store/usernames.ts
- packages/background/src/frontend/server-ui.ts
- packages/common/src/constants.ts
- packages/recoil/src/atoms/preferences/index.tsx
- Save the JWT in the store for each user.
- In the call to check if a user is authenticated in the `WithAuth` wrapper the backend will check the JWT in the header for authentication first, and if it's valid the cookie will be set (overwriting a possibly incorrect cookie if the cookie that exists has a JWT that is different from the JWT in the header).
Closes https://github.com/coral-xyz/backpack/issues/1735
> add jwt storage for users

- packages/app-extension/package.json
- packages/app-extension/src/index.tsx
- packages/app-extension/src/options/index.tsx
- packages/app-extension/tsconfig.json
- packages/app-extension/webpack.config.js
- yarn.lock
related #1591
lazily importing files should help with loading times and the resource usage of backpack
these initial changes provide a couple of modest improvements by reducing -
- the amount of time to open backpack from clicking the icon to get to the lock screen by approx 20-25% on my m1
- the size of popup.js from 4.53 MiB to 1.76 MiB (by creating some extra chunked files that get loaded in parallel)
I am using the regular profiler as there are some issues with the react devtools and chrome extensions due to content security issues, looking into it.
next up is doing some chunking inside the router, with a view to moving away from webpack to a faster and modern tool with more intelligent and aggressive code-splitting, although depending on the amount of work involved that might not be …
> add lazy imports in extension

- packages/app-extension/src/components/common/Account/ImportAccounts.tsx
- packages/app-extension/src/hooks/useConflictQuery.tsx
Adds a lookup query to the import accounts component to disable imports for wallets that are already used on other accounts.
Closes https://github.com/coral-xyz/backpack/issues/1824
Closes https://github.com/coral-xyz/backpack/issues/1823
> use a public key lookup to disable imports for wallets used on other accounts

- backend/native/notifications-worker/src/Redis.ts
- backend/native/notifications-worker/src/index.ts
- backend/native/notifications-worker/src/worker.ts
Fly seems to unable to create a persistent connection to redis, so replacing `blPop` with `lPop` (blocking vs non blocking)
also adding some logs
> Socket errors in redis

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Solana/index.tsx
- packages/common/package.json
- packages/common/src/solana/index.ts
- yarn.lock
@gchatz22
Trying to reduce network calls here on transfer and also adding cardinal-creator-standard token transfer.
Ideally backpack can maybe become a transfer interface for tokens and I'm happy to help contribute to this as token standards evolve
Opening a draft since first time contributing and just want to see how tests and CI works and show @gchatz22...will take another look and followup on anything
Seems like `mintInfo` (or equivalent from new spl-token client) should be passed intro transfer since the data is likely fetched. CCS tokens should require no additional network calls from client on transfer
> Add CCS tokens, reduce network calls on transfer

- packages/react-common/src/components/base/ProxyImage.tsx
In ref to https://github.com/coral-xyz/backpack/issues/1896 
Unsure why `cloudflare images` are unable to render this one. Working fine with `image-proxy` which we had earlier.
For now I've added logic to fallback to original if the proxy fails
> Fallback to original image if proxy fails

- backend/native/backpack-api/src/routes/v1/users.ts
- packages/app-extension/src/components/Unlocked/Settings/Preferences/Blockchains.tsx
- packages/app-extension/src/components/Unlocked/Settings/index.tsx
- packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx
- packages/background/src/backend/core.ts
- packages/background/src/backend/keyring/index.ts
- packages/background/src/frontend/server-ui.ts
- API call to server to add public key to backpack account when a new blockchain is enabled
- Moved the state reverts out of the main API call function in the backend to allow for different types of state reverts
- Updated the API to not error when attempting to add a public key to an account that already has it
Relevant https://github.com/coral-xyz/backpack/issues/1821
Closes https://github.com/coral-xyz/backpack/issues/1820
> add public key to server on enable blockchain

- backend/native/zeus/package.json
- yarn.lock
if contributors have different versions of graphql-zeus it might generate different types, this will just ensure the output is deterministic
> add `graphql-zeus` as a devDependency to pin version

- backend/workers/rpc-proxy/src/index.ts
sanitizes rpc request headers and includes the rpc hostname in the response headers
> update rpc proxy headers

- package.json
adds 2 scripts:
```
- start:ext
- build:ext
```
turbo repo allows you to watch/build based on your required dependencies. by including `...` at the end of the extension we're saying "build the extension and the dependencies the extension relies on"
i could update the main start/build scripts, but i'm not sure what repercussions that would have
i've used this technique for mobile and it has been a substantial improvement in speed
https://turbo.build/repo/docs/core-concepts/monorepos/filtering#include-dependencies-of-matched-workspaces
> adds turbo filtering logic to extension

- backend/native/notifications-worker/package.json
- backend/native/notifications-worker/src/index.ts
- docker/notifications-worker/Dockerfile
- docker/notifications-worker/fly.toml
`notifications-workers` are not deploying, I think because fly is checking the internal port and isn't getting a response from it. 
The PR exposes an HTTP server on the internal port just to make fly happy.
> Added handler on port so fly healthcheck succeeds

- package.json
This PR adds `nohoist` to all `example/` packages:
The goal is to continue to make use of yarns package linking (installing local packages as dependencies) while managing dependencies independently.
- Keeping examples standalone / closer to real life.
- Enabling examples to have iE outdated dependencies without affecting the rest of the workspaces.
Also adding `nohoist` to `app-mobile` since `react-native` dependencies are sensitive and the dependency trees between mobile and the rest of the app have larger differences so hoisting becomes less valuable.
> Add nohoist to examples/**

- backend/workers/rpc-proxy/src/index.ts
adds support for HTTP Upgrade requests so that websocket connections can be opened
I don't think this works with the swr-proxy URL right now, but merging so that the code can go live and be tested
> add websocket support to rpc proxy

- packages/recoil/src/atoms/solana/jupiter.tsx
- packages/recoil/src/context/Swap.tsx
v4 has many bugfixes and new DEX integrations for best pricing. It also handle u64 as string at the interface to prevent any js `number` explosions.
Remove `onlyDirectRoutes` as v4 guarantees a single transaction.
`asLegacyTransaction` guarantees routing that fit in a legacy transaction, then request a legacy transaction calling `/swap`
https://docs.jup.ag/integrating-jupiter/backend-bot-integration/using-the-api
I don't fully understand  the comment 
```
// The Jupiter API returns between 1 and 3 transations to perform a swap
// (setupTransaction, swapTransaction, cleanupTransaction). Additionally
// the wrapping of SOL (if required) is handled here by the wrapTransaction
// step at the beginning.
```
as `wrapUnwrapSOL` is true, but i think it is simply a stale comment as …
> chore: Update to jupiter api v4 for bugfixes and more dexes

- backend/workers/nft-data/src/index.ts
RPC is returning 415 for `getAccountInfo` , adding the header fixes it.
> Added `application/json` header to RPC call

- backend/native/backpack-api/package.json
- yarn.lock
fixes missing chat-zeus error when running `npx turbo run start --filter=backpack-api` from root
> add missing dependencies to api

- packages/blockchains/solana/src/keyring/index.ts
> allow removal of last key in solana keyring

- packages/provider-injection/package.json
When setting up my environment & running `start:fresh` or `start`, I kept getting these errors:
Did a bit of investigating and I believe the problem stems from the lack of a `start` command in the `provider-injection` package for turborepo to run.
After adding the command, the error no longer shows up: 
Can also verify that the command is being invoked properly by turborepo:
> Add missing node script to provider-injection package

- packages/app-extension/package.json
- packages/chat-sdk/src/components/Message.tsx
- yarn.lock
Makes links in messages clickable, using [`linkifyjs`](https://github.com/Hypercontext/linkifyjs) and its React wrapper (licensed under MIT).
A simple stopgap solution until link unfurling (#2148) is properly supported.
> Add support for links in messages

- packages/recoil/src/atoms/friendship.tsx
require cycles are allowed in JS, but they can mess up react native bc of the metro bundler
> removes recoil require cycle

- backend/native/zeus/src/zeus/const.ts
- backend/native/zeus/src/zeus/index.ts
- backend/reef/hasura/metadata/databases/databases.yaml
- backend/reef/hasura/metadata/databases/default/functions/dropzone_user_dropzone_public_key.yaml
- backend/reef/hasura/metadata/databases/default/functions/functions.yaml
- backend/reef/hasura/metadata/databases/default/tables/auth_users.yaml
- backend/reef/hasura/migrations/default/1674856382237_add_user_dropzone_public_key_function/down.sql
- backend/reef/hasura/migrations/default/1674856382237_add_user_dropzone_public_key_function/up.sql
adds a convenience method for returning the first solana public key owned by a user
slightly confusingly the value is an array due to a current limitation of hasura https://github.com/hasura/graphql-engine/issues/6562
future work will allow users to pick their dropzone public key and warn them if they try to remove it with unclaimed drops
> add users.dropzone_public_key helper to hasura

- packages/app-extension/src/components/common/Layout/Router.tsx
- packages/background/src/backend/core.ts
- packages/background/src/frontend/server-ui.ts
- packages/message-sdk/src/ParentCommunicationManager.ts
- packages/message-sdk/src/components/MessageList.tsx
- packages/message-sdk/src/components/ProfileScreen.tsx
- packages/message-sdk/src/components/RequestsScreen.tsx
- packages/recoil/src/hooks/navigation.tsx
In full screen mode, we keep pushing messages on the stack as we navigate. This causes the stack to fill up. If you now open chat in small mode, you have to pop through a bunch of screens to reach the root
This PR solves this by always being at `root + 1` state if you're in full screen mode in chats.
That way as you navigate, the stack doesn't get filled up
We also hide the `back button` in full screen mode
Longer term soln might be to have a full screen nav stack
> Fixed navigation in full screen chat mode

- packages/app-extension/src/components/Unlocked/Messages/MessageOptions.tsx
- packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
- packages/app-extension/src/components/common/PopoverMenu.tsx
closes #2306 
Custom `PopoverMenu` and related children components were designed to look and operate like the current avatar popover menu.
> standardize popover menu into common custom component

- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ImportSecretKey.tsx
- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx
- packages/app-extension/src/components/Unlocked/Settings/SettingsNavStackDrawer.tsx
- packages/app-extension/src/components/Unlocked/index.tsx
- packages/app-extension/src/components/common/WalletList.tsx
Removes render problems by rendering the wallet list higher up the component tree and standardises closing behaviour when wallet is clicked on after creation.
Closes #1992
> fix extra rerenders closing wallet list

- backend/native/backpack-api/src/routes/v1/users.ts
order of routes is significant, /users/:username is a catch-all route so /users/me needs to be before it
> fix /users/me API endpoint

- README.md
- packages/app-extension/.gitignore
- packages/app-extension/webpack.config.js
This should stop these errors from flooding your console when running `yarn start`
It involves some manual steps with creating and installing a self-signed certificate for localhost, here they are for mac OS
```
cd packages/app-extension
brew install mkcert
mkcert localhost
mkcert -install
yarn start
```
If you don't do these steps things will continue to work as before. If this solves an issue for other people we can probably automate it in some way.
These errors exist because the automatically created `webpack-dev-server` certificate is considered [invalid](https://github.com/webpack/webpack-dev-server/issues/2957), at least with the mac OS & openssl versions I am using [office-addin-dev-certs](https://www.npmjs.com/package/office-addin-dev-certs) are also invalid.
---
it also changes …
> fix webpack-dev-server websocket connection

- packages/eslint-config-custom/index.js
Stops warning on immediate execution in `useEffect` blocks
> add ignoreIIFE to no-floating-promises

- packages/app-extension/src/app/DbRecoilSync.tsx
- packages/background/src/backend/core.ts
- packages/common/src/constants.ts
- packages/recoil/src/atoms/preferences/index.tsx
- packages/recoil/src/context/Notifications.tsx
- packages/recoil/src/hooks/preferences/index.tsx
Adds recoil state for the currently authenticated user and updates sync code to use that state instead of the client active user.
Closes https://github.com/coral-xyz/backpack/issues/2570
Closes https://github.com/coral-xyz/backpack/issues/2556
> fix auth race due to auth delay

- backend/reef/docker-compose.yml
This doesn't include the sha256 checksums because this docker-compose is only being used locally and it would lock the platform of the images.
For example, if we pin it to the arm build for m1&2 macs, then there will be errors on amd64 systems and vice versa
> update local hasura and postgres versions

- packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RemoveWallet.tsx
if a user is trying to remove their dropzone wallet AND they have unclaimed drops
they will see this final confirmation screen before removing the wallet
after the wallet is removed the next available solana wallet will be the designated dropzone wallet
> add warning if removing dropzone wallet

- backend/native/backpack-api/src/db/notifications.ts
order by notification id, becomes problematic when you have more than 50 notifications
> Fixed notification cursor

- packages/app-extension/src/components/Unlocked/Nfts/NftTable.tsx
Probably broke when we removed ONE check from here which early returned
> Dont post nfts to db

- packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RemoveWallet.tsx
This reverts commit 4eecd718693f06edd3e3bd79d6a10955b43ae5e0.
No longer needed because of the primary wallet setup.
> Revert "add warning if removing dropzone wallet (#2676)"

- packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
Loader should display while burning transaction being sent.
> fix order of burn token drawer transition

- packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx
Fixes Issue [#2499](https://github.com/coral-xyz/backpack/issues/2499)
Problem - Notification avatar should be at the top left of the notification list item #2499
Solution - Added alignItems: "flex-start"
> Fixed notification avatar position to the top left of the notification list item

- packages/app-extension/src/index.tsx
- packages/app-extension/src/options/index.tsx
- packages/app-extension/src/permissions/index.tsx
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis
TLDR by not using createRoot, the app will function like a v17 app
> switch back from createRoot to render

- packages/app-extension/src/components/Unlocked/Balances/TransferWidget.tsx
- packages/recoil/src/atoms/solana/jupiter.tsx
- packages/recoil/src/hooks/solana/useJupiter.tsx
Fixes #3015 
Wraps SwapProvider in Suspense so that it the Swap button is semi-transparent and unclickable until Jupiter route maps have loaded.
I decided to make it the button semi-transparent instead of hidden so that the UI doesn't jump, hopefully it most cases it should become active within a few seconds and not really be noticeable.
This might also provide a minor speed boost when loading balances as it moves this loading into an async process that doesn't block rendering.
Light Mode while loading | Dark Mode while loading
------------|------------
> don't block UI when loading jupiter routes

- packages/app-extension/src/components/Unlocked/Balances/TransferWidget.tsx
follow up to #3036
now the swap button is always clickable with full opacity
if the routes haven't loaded before the user clicks, they will see a loading spinner on the Swap page
if they have already loaded then the Swap page will open immediately
> async jupiter route loading follow-up

- packages/app-extension/src/options.html
- packages/app-extension/src/permissions.html
- packages/app-extension/src/popup.html
tiny improvement that updates the title of the tabs and popup window to `Backpack`
a future improvement could include the active username in the title like `@username - Backpack`
> add "Backpack" title to popup and tabs

- packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx
addresses (but may not close) #3078
> fix chat drawer image skeletons

- packages/app-extension/src/components/Unlocked/Nfts/EntryONE.tsx
- packages/recoil/src/atoms/solana/isONELive.tsx
Could help with #3079 and #3052
#3079: recheck isLive when authenticatedUser changes since new JWT should be guaranteed at that point. -> expected to reduce undefined JWTs
#3052: Rearrange hidden elements to make sure no clicks happen on them. Some Windows/chrome versions might swallow those clicks
> Change zIndexes for madlist banner + add check for AuthenticatedUser in isLive check

- packages/app-extension/src/components/Unlocked/Swap.tsx
- packages/recoil/src/atoms/solana/jupiter.tsx
- packages/recoil/src/context/Swap.tsx
Fixes #416
Uses https://cache.jup.ag/top-tokens to order the available output tokens in order of popularity. Tokens that are not included in that list will maintain their original order.
before | after
-------|---------
> sort swap output tokens by their popularity on jupiter

- packages/message-sdk/src/components/ProfileScreen.tsx
fix #2551 
Issue: The send button feature has not been implemented on the profile page yet
fix: added the **CSS cursor property 'not-allowed'** to indicate that the functionality is not currently available.
> fix : Send button on contact profile page is not functional

- packages/app-extension/src/index.tsx
Issue: https://github.com/coral-xyz/backpack/issues/3077
Problem: ctrl+g popout mode keyboard shortcut does not work on windows pc #3077 
Solution: Used keydown instead of keypress and added event.preventDefault();
https://user-images.githubusercontent.com/82360525/222441735-bc1ad419-c4a6-4dd7-8b4e-864188178c81.mp4
> Fixed ctrl+g popout mode keyboard shortcut on windows

- packages/chat-sdk/src/components/messageInput/MessageInput.tsx
Issue: Textbox overflow needs to be constrained for longer words #3159
Solution: Added wordBreak: "break-word"
https://user-images.githubusercontent.com/82360525/222877087-9c7d675c-7d38-4daa-b26b-67340c061dde.mp4
> Fixed message input text overflow

- packages/chat-sdk/src/components/messageInput/MessageInput.tsx
Issue: Staff/verified badge should show up in tagged usernames popover too #3183
> Added staff badge to tag usernames popover

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Ethereum/index.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Solana/index.tsx
- packages/app-extension/src/components/common/CopyablePublicKey.tsx
- packages/app-extension/src/components/common/TransactionData.tsx
fixes #2802 
fixes #3198
> **Note**
> usernames and wallet names could be indistinguishable if users put an @ symbol in their wallet names
another solana user | a different wallet owned by the user
----|----
another solana user | another ethereum user | a different wallet owned by the user
-------|------|-------
> show usernames in send confirmation drawer

- packages/app-extension/src/components/common/index.tsx
Fix #1150 
Problem: The tick mark was not visible in dark mode.
Solution: Check the current theme mode and change the checkbox's checked color when in dark mode.
Dark Mode :
Ligh Mode :
> Fix : checkbox not visible in darkmode

- packages/app-extension/src/components/Unlocked/Balances/RecentActivity.tsx
fixes #3197
A quick fix to get in the next release, a bigger more robust fix would involve changing more code and adding some types to ensure that all expected properties are available.
Also adds a timestamp in the user's locale for some more information. Longer term it might be better to replace with time ago like "10 minutes ago" but perhaps this is better than only showing the date for now?
eth|sol
----|-----
> fix dates in ethereum recent activity

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
fixes a bug where it looked like the public key you are sending to was the .sol domain
before | after
-----|-----
> fix ui issue when sending to .sol domains

- backend/workers/auth/src/index.ts
fixes #3229
hono's api had changed, `onError` now takes precedence over custom middleware
> fix auth worker error responses

- packages/app-extension/src/index.tsx
Closes other instances of backpack upon opening, for both extension and popout mode.
When a user has multiple backpack windows open it can lead to unpredictable behaviors.
https://user-images.githubusercontent.com/101902546/223525604-5350f328-c075-4ce1-b3b0-32be6d728e50.mov
I don't yet know what the implications of this would be, it needs more testing before being merged.
There could be unforeseen issues with the autolock timer not being restarted for instance
> close any existing backpack windows when opening a new one

- backend/native/backpack-api/src/db/users.ts
- backend/native/backpack-api/src/routes/v1/nft.ts
- backend/native/backpack-api/src/routes/v1/public-keys.ts
- backend/native/backpack-api/src/routes/v1/users.ts
Instead of restricting to primary public keys only, just strip the user id from the response. We still need to know if they exist on any accounts to allow for conflict checking.
> fix public key conflict endpoint

- packages/recoil/src/hooks/useTransactionData.tsx
network fee for message on devnet solana is returned as `null` from the rpc method, and was not properly handled causing an uncaught data parsing error.
> fix devnet sol tx data hook

- packages/common/src/browser/extension.ts
fixes #547
popout on right of regular extension window, it's slightly shorter and a lot thinner
sizes now match
> fix size of popout for windows users

- packages/app-extension/src/components/Unlocked/Approvals/ApproveMessage.tsx
- packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx
- packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx
- packages/app-extension/src/components/Unlocked/Balances/BalanceSummaryWidget.tsx
- packages/app-extension/src/components/Unlocked/Balances/Balances.tsx
- packages/app-extension/src/components/Unlocked/Balances/RecentActivity.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Deposit.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
- packages/app-extension/src/components/Unlocked/Nfts/EntryONE.tsx
- packages/app-extension/src/components/Unlocked/Settings/Preferences/index.tsx
- packages/app-extension/src/components/common/ApproveTransactionDrawer.tsx
- packages/app-extension/src/components/common/Layout/Drawer.tsx
- packages/app-extension/src/components/common/Layout/Tab.tsx
- packages/app-extension/src/components/common/TransactionData.tsx
- packages/app-extension/src/components/common/WalletList.tsx
- packages/app-extension/src/components/common/index.tsx
- packages/app-mobile/src/hooks/index.ts
- packages/app-mobile/src/screens/Unlocked/DepositScreen.tsx
- packages/app-mobile/src/screens/Unlocked/RecentActivityScreen.tsx
- packages/app-mobile/src/screens/Unlocked/Settings/PreferencesScreen.tsx
- packages/app-mobile/src/screens/Unlocked/WalletListScreen.tsx
- packages/app-mobile/src/screens/Unlocked/components/index.tsx
- packages/eslint-config-custom/package.json
- packages/recoil/src/hooks/useBlockchain.tsx
- yarn.lock
unused css classes weren't being picked up by  `eslint-plugin-mui-unused-classes` anymore because the function name had changed from `makeStyles` to `styles`
on reflection it might've been easier to either change the eslint rule to pick up blocks called `styles` or renamed `styles` to `makeStyles` but then there's a chance people might import the wrong function. For now I changed `import { styles }` to `import { styles as makeStyles }`
I had to add some other changes because of eslint errors, when it involved requiring changes that might affect the functionality of backpack without testing them I put eslint ignores for now, but they should be addressed at some point
> remove unused css classes

- backend/reef/hasura/migrations/default/1678649211108_create_index_public_keys_user_id_idx/down.sql
- backend/reef/hasura/migrations/default/1678649211108_create_index_public_keys_user_id_idx/up.sql
adds index to `auth.public_keys.user_id`
reduces total cost of 
```graphql
query {
auth_users(where:{username:{_eq:"backpack_dev"}}) {
id
public_keys {
public_key
}
}
}
```
from `20,500` to `17`
before | after
-------|------
> add index to public_keys.user_id

- backend/native/backend-common/package.json
- backend/native/backend-ws/package.json
- backend/native/notifications-worker/package.json
- packages/common/package.json
- packages/db/package.json
- yarn.lock
Adds some missing, removes some unused deps.
The motivation behind this is that it can take anywhere between 10-30 minutes to build this repo from scratch and in CI, I think we can reduce this by at least 10x by using pnpm instead, but to do that the dependencies need to be correct for each package (99% done) and some bugs and circular dependencies that yarn is hiding need to be addressed.
> dependencies cleanup

- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ConnectHardware/index.tsx
- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/CreateMenu.tsx
- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ImportMenu.tsx
- packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ImportSecretKey.tsx
- packages/background/src/frontend/server-ui.ts
- packages/common/src/constants.ts
This should be a more reliable way to ensure we don't attempt to create a blockchain keyring if it has already been created. Should resolve the race condition that caused https://github.com/coral-xyz/backpack/issues/3357.
Closes https://github.com/coral-xyz/backpack/issues/3357
> use recoil state for keyring exists checks

- packages/app-extension/src/components/Locked/index.tsx
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
- packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx
- packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
- packages/chat-sdk/src/components/Message.tsx
- packages/chat-sdk/src/components/barter/BarterHeader.tsx
- packages/common/src/utils.ts
- packages/message-sdk/src/components/MessageList.tsx
- packages/message-sdk/src/components/ProfileScreen.tsx
- packages/message-sdk/src/components/UserList.tsx
- packages/react-common/src/components/base/LocalImage.tsx
- packages/react-common/src/components/base/ProxyImage.tsx
- packages/react-common/src/components/base/UserIcon.tsx
PR asks for small images when small image is needed
PR modifies the `skeleton loader` logic a little to fallback to original image after 1.5s. This is done because the `onLoad` event doesn't seem to fire sometimes on the image causing the loader to stay up indefinitely
> Fix image loads

- backend/native/zeus/src/zeus/const.ts
- backend/native/zeus/src/zeus/index.ts
- backend/reef/hasura/metadata/databases/default/tables/auth_public_keys.yaml
- backend/reef/hasura/migrations/default/1679016121566_add_public_key_is_primary_function/down.sql
- backend/reef/hasura/migrations/default/1679016121566_add_public_key_is_primary_function/up.sql
adds an `is_primary: boolean` computed field to `public_keys`, it effectively does the same as `user_active_publickey_mappings` but in a more optimized way
before (~10s query) | after (~50ms query)
---|---
> add auth.public_keys.is_primary computed field

- packages/eslint-config-custom/index.js
example | is valid?
-----|----
publickey|❌
publickeys|❌
PUBLICKEY|❌
PUBLICKEYS|❌
public_key|✅
public_keys|✅
publicKey|✅
publicKeys|✅
related:
- https://github.com/coral-xyz/backpack/pull/1298#discussion_r1006879977
- https://github.com/coral-xyz/backpack/pull/1296
> eslint warn if "publickey" is one word

- backend/native/backend-ws/src/db/users.ts
- backend/native/backpack-api/src/db/friendships.ts
- backend/native/backpack-api/src/db/users.ts
sometimes these userIds arrays are empty and zeus strips the filter, so the query gets converted into something like `query getUsersMetadata {auth_users(where: {id: {}})  {id
username}}` which fetches the id and username of all users
> return empty array if userIds.length === 0

- docker/backend-ws/Dockerfile
- docker/backpack-api/Dockerfile
- docker/notifications-worker/Dockerfile
- docker/xnft-api-server/Dockerfile
yarn log 13 is a cache miss. cache misses always happen bc these are fresh builds. no need to show all of them bc otherwise we don't see the other logs
> discard yarn cache miss logs bc they take up too much

- package.json
my terminal randomly started having issues with `yarn start` because of the asterisk in `env-cmd --silent turbo run start --concurrency=100% --filter=./packages/*`, so I wrapped everything in single quotes for consistency
> wrap yarn script filters in quotes

- packages/app-extension/src/components/common/Account/PrivateKeyInput.tsx
- yarn.lock
Closes https://github.com/coral-xyz/backpack/issues/3476
This happens when the user enters a space and then pastes the private key, the fix I've added is to trim off the spaces from the input while setting the state variable.
> Fixed whitespace causes invalid private key 

- packages/app-extension/src/components/Unlocked/Balances/TransferWidget.tsx
fixes "token name value - undefined in send flow"
closes #3484 
**Steps to reproduce:**
Balances -> click on "Send" -> select a token -> header displays "Send undefined"
**bug** - token name was not being pushed in `NavStackProvider` for `select-user` route
**Screen recording(post fix):**
https://user-images.githubusercontent.com/13575704/229135383-37ebc018-2576-422b-8aac-e4f2ec5510cd.mov
> bug: fix missing token name

- packages/app-extension/src/components/common/Layout/Nav.tsx
Header was using `ProxyImage` which uses swr-cache which is refreshed after 1 hour
Made it use `LocalImage` instead
> Fixes #3507

- backend/native/backpack-api/src/index.ts
sometimes `res.status is not a function` would show without this final unused parameter, will look into why in future, merging now as a fix
> fix backend-api sometimes throwing res.status is not a function

- packages/app-extension/src/components/common/Layout/Nav.tsx
After the resolution of Issue #3507 by #3524, we are no longer using the
`ProxyImage` Component in the `Nav.tsx`Module. Therefore, we no longer
need to import the Component.
> Remove the Import of ProxyImage Component from Nav.tsx 

- packages/provider-core/src/provider-solana.ts
This fixes a bug where the connect function is not called properly on a reconnect, as #publicKey is already defined
Specifically this is because of this condition in the wallet-standard wrapper (https://github.com/coral-xyz/backpack/blob/master/packages/wallet-standard/src/wallet.ts#L149):
```
#connect: ConnectMethod = async ({ silent } = {}) => {
if (!silent && !this.#backpack.publicKey) {
await this.#backpack.connect();
}
this.#connected();
return { accounts: this.accounts };
};
```
On the first connect, `this.#backpack.publicKey` is undefined and `this.#backpack.connect()` is called correctly
However, on the second connect `this.#backpack.publicKey` was already set and so `this.#backpack.connect()` was not called. `this.#connected()` was called, and since this uses …
> Clear backpack.#publicKey on disconnect

- backend/native/backpack-api/package.json
- backend/native/backpack-api/src/routes/v1/users.ts
- yarn.lock
a bit of maintenance that i wanted to keep separate from another branch i'm working on
> remove unused express-rate-limit from backpack-api

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Solana/index.tsx
- packages/app-mobile/src/components/BottomDrawerSolanaConfirmation.tsx
- packages/common/src/solana/index.ts
This PR enables the transfer of `pNFT`s from a token (non-ATA) account. It uses the token address as the source account.
> Specify source token account on transfer

- packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx
[Backpack.webm](https://user-images.githubusercontent.com/128965067/230313527-04552f2e-bf9a-4452-8999-5a941908490b.webm)
> fix - allow notifications screen doesn't display on account recovery #3619

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Solana/index.tsx
- packages/app-mobile/src/components/BottomDrawerSolanaConfirmation.tsx
- packages/common/src/solana/index.ts
- packages/common/src/solana/send-helpers.ts
- packages/recoil/src/hooks/solana/index.tsx
- packages/recoil/src/hooks/solana/useSolanaTransaction.tsx
> consolidate token/nft send functions between extension/mobile

- .actrc
- .github/actions/backend-tests/action.yml
- .github/workflows/pull_requests_and_merges.yml
- backend/native/backpack-api/package.json
- backend/native/backpack-api/src/db/users.ts
- backend/native/backpack-api/src/routes/v1/__tests__/_constants.ts
- backend/native/backpack-api/src/routes/v1/__tests__/_setup.ts
- backend/native/backpack-api/src/routes/v1/__tests__/authenticate.test.ts
- backend/native/backpack-api/src/routes/v1/__tests__/friends.test.ts
- backend/native/backpack-api/src/routes/v1/__tests__/referrals.test.ts
- backend/native/backpack-api/src/routes/v1/__tests__/users.test.ts
- backend/native/backpack-api/src/routes/v1/users.ts
- backend/native/backpack-api/tsconfig.json
- backend/native/backpack-api/vite.config.ts
- backend/native/xnft-api-server/package.json
- backend/native/xnft-api-server/src/db/users.ts
- backend/native/xnft-api-server/src/v1/__tests__/users.test.ts
- backend/native/xnft-api-server/src/v1/users.ts
- backend/native/xnft-api-server/tsconfig.json
- backend/native/xnft-api-server/vite.config.ts
- backend/native/zeus/src/zeus/const.ts
- backend/native/zeus/src/zeus/index.ts
- backend/reef/docker-compose.yml
- backend/reef/hasura/metadata/databases/default/tables/auth_users.yaml
- yarn.lock
uses public_keys.is_primary to use the db indexes when checking if public keys are primary or not
added tests for all the endpoints it might affect, to try and ensure it doesn't introduce any regression bugs. These could probably be reduced or removed eventually if we added something like zod and trpc to our api endpoints for typing guarantees
also adds redis in docker-compose so that `xnft-api-server` can be run locally
> use auth_users.public_keys.is_primary in all relevant queries

- backend/native/backpack-api/src/db/users.ts
- backend/native/backpack-api/src/routes/v1/__tests__/_constants.ts
- backend/native/backpack-api/src/routes/v1/__tests__/users.test.ts
- backend/native/backpack-api/src/routes/v1/users.ts
- backend/native/zeus/src/zeus/const.ts
- backend/native/zeus/src/zeus/index.ts
- backend/reef/hasura/metadata/databases/databases.yaml
- backend/reef/hasura/metadata/databases/default/functions/auth_users_whose_username_matches.yaml
- backend/reef/hasura/metadata/databases/default/functions/dropzone_user_dropzone_public_key.yaml
- backend/reef/hasura/metadata/databases/default/functions/functions.yaml
- backend/reef/hasura/migrations/default/1680874984983_add_users_whose_username_matches_function/down.sql
- backend/reef/hasura/migrations/default/1680874984983_add_users_whose_username_matches_function/up.sql
- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx
- packages/app-mobile/src/screens/Unlocked/SendTokenScreen2.tsx
fixes #3645
- re-adds `public_keys.publicKey` and adds some tests to make refactoring possible if we choose to stick to a convention of snake case or camel case for data served from the API
- merges #3641 which returns the exact username match as the first result
- adds & before limit url search param so `blockchain=solanalimit=6` becomes `blockchain=solana&limit=6`
> fix users missing in search results when sending tokens

- backend/workers/feature-gates/package.json
- backend/workers/feature-gates/src/index.ts
- backend/workers/jupiter-proxy/package.json
- backend/workers/jupiter-proxy/src/index.ts
- backend/workers/version/.eslintrc.js
- backend/workers/version/package.json
- backend/workers/version/src/index.ts
- backend/workers/version/wrangler.toml
- yarn.lock
while debugging some issues that some windows users seem to be facing, this updates cors settings for the following workers -
- feature-gates
- jupiter-proxy
- version
for now it ignores the following workers
- avatars
- invites
- nft-data
> update cors settings for some workers

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Token.tsx
hides the absolute USD value and 24hr percentage change value if there's no coingecko data available for that token
before | after
---|---
> hide token price change if no data is available

- packages/app-extension/src/components/Unlocked/Balances/TransferWidget.tsx
- packages/recoil/src/context/Swap.tsx
fixes #3075 
hides the swap button if it's an unsupported token
token that can be swapped | token that _cannot_ be swapped
---|----
NOTE: the `$0 0%` subheading on unsupported tokens has now been removed in https://github.com/coral-xyz/backpack/pull/3658
> hide swap button for token if it can't be swapped

- packages/app-extension/src/options/index.tsx
related #1496 
Firefox will not accept any source files > 4MB
This shrinks options.js from 6.2MB to 143KB and doesn't create any new chunk files that are over 4MB
> add another lazy import in options.js to reduce bundle size

- packages/app-extension/src/components/common/Account/ImportWallets.tsx
- packages/common/src/crypto.ts
Easy to test, go to metamask, see some addresses for "Ledger live", go to backpack see some other addresses.
Also source https://github.com/MetaMask/metamask-extension/blob/6439551075e585c9ec27667e68df0cca9d4ef468/ui/pages/create-account/connect-hardware/index.js#L39
> fix: Ledger live EVM incorrect derivation path

- packages/message-sdk/src/components/ChatScreen.tsx
The friend request notifications weren't updating when the friend request was accepted through the chat. This was primarily because when sending or accepting a request through the chat window, only `requested` was being updated in the recoil state.
Check if `friendshipValue.remoteRequested` is set to true for the `ChatScreen`, in that case, update state to set `areFriends` to true. If `remoteRequested` is false, then update `requested` to true.
https://user-images.githubusercontent.com/20705464/234343554-2ef92cba-679e-46f2-8915-41615f9dbf62.mov
Fixes #3710
> Fixes friend request notification not updating

- packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
This PR attempts at improving, mainly, the desktop experience of using Backpack, that is currently like this: https://github.com/coral-xyz/backpack/issues/3778
It stretches small images as width: 100% is always enforced
This PR changes width: 100% to maxWidth: 100%; and center the item (which is useful if the NFT image is small, like SMB). Mobile version remains unaffected by the changes as it is a really small window, so continue to prob just use 100%.
https://www.loom.com/share/0364a5513b44446caad0e7c085f43050 (non-popup mode didnt record lol, i guess i need to record entire desktop for it to show).
> fix: streched image dimensions

- packages/background/src/frontend/server-ui.ts
- packages/background/src/index.ts
Querying the keyring store state was preventing the extension from locking in pop out mode. Querying the keyring store state is not a user action so it should not extend the timer.
> fix popout mode not locking

- packages/app-extension/src/components/Unlocked/Approvals/ApproveOrigin.tsx
This PR removes the Hover Styling from the texts "View wallet balance…"
and "Request approval…" as these are not interactive.
closes  #2013
> Remove Hover Styling from Wallet Connect Request

- packages/chat-sdk/src/components/Message.tsx
- packages/chat-sdk/src/components/NftStickerRender.tsx
Fixed #3843
Screenshot before fix:
Screenshot after fix:
p.s. Had to remove two style classes that are not being used to pass the es-lint check
> Adds username to the stickers tooltip in chatrooms

- packages/recoil/src/atoms/solana/nft.tsx
- packages/recoil/src/utils.ts
During the async data fetch for the `customSplTokenAccounts` atom, the selector `solanaMetadataMap` was not able to propagate the "loading" state when the request was still evaluated as pending. This is because the exception (thrown as an unfulfilled Promise) was caught and returned as a null value, causing recoil to set the loadable state of the selector as "hasValue" instead of "loading". As a result, the component displayed an empty state before recoil successfully retried the evaluation.
To address this, a solution is to throw the exception if it is a promise, so that it propagates up the state to the component as "loading". Open to suggestions on how to improve this as this is my first PR!
https://github.com/coral-xyz/backpack/assets/33209733/18e6c49d-9376-4ed2-b39d-36cbad3de760 …
> fix: empty nft screen loads before nfts load

- packages/app-extension/webpack.config.js
injects the description and version specified in app-extension/package.json into the manifest.json
it was using `process.env.npm_package_description` before but I don't think that works with monorepos
> use description and version from package.json

- packages/background/src/index.ts
places this inside the IS_MOBILE block to prevent it from breaking on mobile
> fix service worker on mobile

- packages/wallet-standard/package.json
- packages/wallet-standard/src/wallet.ts
- yarn.lock
Some Wallet Standard feature types were renamed. This updates to the latest versions and uses the non-deprecated imports. There are no functional or runtime changes.
> Fix deprecated imports

- package.json
- packages/chat-xplat/.parcelrc
- packages/chat-xplat/package.json
- packages/chat-xplat/tsconfig.json
- yarn.lock
if it's gonna build, it should build
my requirements were:
- types and autocomplete still works with path alises import { A } from '~src/A'
- proper build targets for react-native/the extension with ESM support for the latter
- speed (since its built as a lbrary, less work for the extension)
> (expirement) adds parcel build to chat-xplat

- packages/app-extension/src/components/Unlocked/Nfts/NftDetail.tsx
- packages/background/src/backend/solana-connection.ts
- packages/background/src/frontend/solana-connection.ts
- packages/common/src/solana/background-connection.ts
- packages/common/src/solana/index.ts
- packages/common/src/solana/programs/token.ts
- packages/common/src/solana/send-helpers.ts
- packages/common/src/solana/types.ts
- packages/recoil/src/atoms/solana/nft.tsx
- packages/recoil/src/atoms/solana/token.tsx
- packages/recoil/src/atoms/solana/wallet.tsx
- packages/recoil/src/hooks/solana/index.tsx
- packages/recoil/src/hooks/solana/useSolanaConnection.tsx
- packages/recoil/src/hooks/solana/useSolanaTransaction.tsx
Token-2022 has been out for some time, but backpack doesn't support it.
Add basic support for Token-2022! This PR boils down to a few things:
* fetch accounts for token-2022
* store the program id on accounts and mints after they're fetched
* use the program id for ATA derivation, transfers, and burns
Since the `Program` type from Anchor doesn't allow modifying the program id, I've gone with a `TokenInterface` intermediate type, which contains a `withProgramId` function, to expose a `Program<SplToken>` with the correct program id. This may be a little heavy, so let me know if you prefer something else. You could also modify instructions as they're created, but going through the `TokenInterface` makes it hard to get wrong, which I wanted to prioritize.
Note that this PR doesn't touch …
> feat: support token-2022 accounts, transfers, and burns

- packages/eslint-config-custom/shared/react.js
- packages/recoil/package.json
- packages/recoil/src/hooks/useIsValidAddress.tsx
- yarn.lock
Eliminate race condition in `useIsAddressValid`
In general, async code in React effects is unsafe. To be precise, _setting state_ after an awaitable is unsafe unless you track whether the effect that triggered you is still ‘relevant’ (ie. its dependencies haven't changed _and_ the component in which it lives has not unmounted).
```ts
useEffect(() => {
(async () => {
const result = await somethingThatTakesTime(foo);
setResult(result); // `foo` might have changed by now!
})();
}, [foo]);
// 1. `foo` gets set to `bar`
// 2. `somethingThatTakesTime` gets called for `bar`
// 3. `foo` changes to `baz`
// 4. `somethingThatTakesTime` gets called for `baz`
// 5. `somethingThatTakesTime` returns a result for `baz` and `setResult` gets called
// 6. `somethingThatTakesTime` returns a result for `bar` …
```
> Eliminate race condition in `useIsAddressValid`

- packages/common/src/plugin.ts
- packages/provider-core/src/root-provider-xnft.ts
- add `allow-popups` permission to the plugin sandbox
- remove the `window.xnft.openWindow` wrapper since standard `window.open` will now work
> allow popups sandbox permission

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Token.tsx
> fix USD formatting on token detail screen

- packages/app-mobile/eas.json
- packages/app-mobile/src/components/BottomSheetWalletPicker.tsx
- packages/app-mobile/src/components/CollectionAttributesList.tsx
- packages/app-mobile/src/components/CollectionListItem.tsx
- packages/app-mobile/src/graphql/apollo.tsx
- packages/app-mobile/src/navigation/WalletsNavigator.tsx
- packages/app-mobile/src/navigation/types.ts
- packages/app-mobile/src/screens/CollectionDetailScreen.tsx
- packages/app-mobile/src/screens/CollectionItemDetailScreen.tsx
- packages/app-mobile/src/screens/CollectionListScreen.tsx
- packages/app-mobile/src/screens/HomeWalletListScreen.tsx
- packages/app-mobile/src/screens/RecentActivityScreen.tsx
- packages/app-mobile/src/screens/TokenListScreen.tsx
- packages/app-mobile/src/screens/Unlocked/components/BalanceSummaryWidget.tsx
- packages/recoil/src/context/OnboardingProvider.tsx
- packages/recoil/src/hooks/useAuthentication.tsx
- packages/recoil/src/hooks/useRpcRequests.tsx
- packages/tamagui-core/package.json
- packages/tamagui-core/src/components/ProxyImage.native.tsx
- yarn.lock
- loads the correct balances based on tapping the wallet picker button inside the bottom sheet
- fixes token auth for fetching data from onboarding
- adds private key import in onboarding
- points testflights build to latest service worker
- updates graphql query for balances queries
- set a consistent navigator color (fontColor right now, but this is old design system)
- consistently removes back title from wallets navigator (tokens / collections / activity)
- consistent NFT image loading
- removes vertical scroll indicator for a bunch of views
- adds useCallback to various hooks
- fixes collection detail screen styles (edited)
> auth fixes, graphql migration, navigator updates

- packages/common/src/plugin.ts
fixes `Cannot assign to read only property 'negative' of object` error which I believe is related to storing and retrieving PublicKey objects (rather than base58 strings) around in recoil
before | after
----|----
it also restores a bit of metadata about the xnft in the top of the transaction signing drawer for production xNFTs
before | after
----|----
There are some incorrect `PublicKey` vs `string` types in recoil and common which makes this a little tricky to debug but it'd be good to circle back and get them all sorted out soon
> fix issue with storing xnftAddress object in recoil

- packages/app-extension/src/components/Unlocked/Nfts/NftDetail.tsx
- packages/app-extension/src/components/Unlocked/Settings/Xnfts/Detail.tsx
- packages/background/src/backend/solana-connection.ts
- packages/background/src/frontend/solana-connection.ts
- packages/chat-sdk/src/components/SimpleTransaction.tsx
- packages/common/src/solana/background-connection.ts
- packages/recoil/src/hooks/solana/useSolanaTransaction.tsx
fixes #3978 
`window.xnft.solana.sendAndConfirm` fails at the confirmation stage because versioned transactions aren't supported in the getParsedTransaction config, this adds support by adding `maxSupportedTransactionVersion: 0`
> fix checking versioned transaction status

- packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
before vs after
https://github.com/coral-xyz/backpack/assets/101902546/f8acadeb-bb75-474f-90e4-213675bf8def
makes send input a lot stricter so it only accepts valid positive integers or decimals that are larger that the minimum possible fraction of a token
> make send input validation stricter

- packages/data-components/package.json
- packages/data-components/src/components/TransactionHistory/TransactionDetails/TransactionDetailsTable.tsx
- packages/data-components/src/components/TransactionHistory/TransactionListItem.tsx
- packages/data-components/src/components/TransactionHistory/TransactionListItemIcon.tsx
- packages/tamagui-core/src/index.tsx
- yarn.lock
`export * as TamaguiIcons from "@tamagui/lucide-icons";` breaks mobile, so imported the icons as TamaguiIcons directly
> fix tamagui/lucide icons for mobile

- packages/app-extension/src/components/Locked/LockedMenu.tsx
> fix locked menu background in dark mode

- packages/app-mobile/src/navigation/GlobalDrawerContent.tsx
removes the settings gear icon from the side menu header
> remove gear icon from mobile side drawer

- packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx
- packages/app-mobile/src/screens/ResetWarningScreen.tsx
- packages/app-mobile/src/screens/Unlocked/YourAccountScreen.tsx
- tapping the `Settings > Your Account > Log out` button and agreeing to the reset warning will now clear all the data stored on the device
- removes Delete account button for now
> **Note**
> Once we support multiple accounts, the reset button will need to change to a remove account button, which only removes data for a single user
> fix resetting mobile app data from settings

- packages/app-mobile/src/screens/Unlocked/EditWalletsScreen.tsx
removes the check next to the active wallet name in the settings view
> hide checkmark in mobile wallets settings

- packages/background/src/backend/core.ts
- packages/recoil/src/types.ts
by extracting a function from `@coral-xyz/recoil` and effectively removing it as a dependency (only importing a type now) from `@coral-xyz/background`, the mobile service worker bundle size is reduced from 9.61MB to 3.67MB
> reduce mobile service worker bundle size
