packages/app-extension/src/components/Onboarding/OnboardingWelcome.tsx
=> fix menu container in onboarding flow

packages/provider-injection/src/index.ts
=> Inject providers to `window` in such a way they can't be reassigned

packages/app-extension/src/components/Locked/Reset/ResetWelcome.tsx
Small change for forget password flow when deciding to try more passwords.
Fixes: https://github.com/coral-xyz/backpack/issues/869
https://user-images.githubusercontent.com/97734034/192414324-8460c926-38e6-49bd-9317-db4dc28aa846.mov
=> Fix forget password flow for locked and unlocked

.github/workflows/pull_request.yml, backend/reef/hasura/metadata/databases/default/tables/public_images.yaml, backend/reef/hasura/migrations/default/1664301242943_create_invitation_for_image_record_trigger/down.sql, backend/reef/hasura/migrations/default/1664301242943_create_invitation_for_image_record_trigger/up.sql, backend/reef/hasura/migrations/default/1664301421183_set_fk_public_images_invite_code/down.sql, backend/reef/hasura/migrations/default/1664301421183_set_fk_public_images_invite_code/up.sql
I might rename `invite_code` to `invitation_id` later for consistency but this should work for now @callensm
=> auto-create an invitation for each image record

backend/reef/hasura/metadata/databases/default/tables/auth_invitations.yaml, backend/reef/hasura/metadata/databases/default/tables/public_images.yaml, backend/reef/hasura/metadata/databases/default/tables/public_invitations.yaml
with limited scope, used by internal tooling
=> add mod role to gql api

packages/app-extension/src/app/Router.tsx, packages/app-extension/src/components/Unlocked/Approvals/ApproveOrigin.tsx, packages/background/src/frontend/server-injected.ts, packages/common/src/browser/extension.ts, packages/recoil/src/hooks/useBlockchain.tsx
Pass blockchain to the approve origin popup so we can display the active wallet address for the correct blockchain.
Closes https://github.com/coral-xyz/backpack/issues/910
=> detect blockchain/display correct wallet on approve origin popup

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx, packages/provider-core/src/provider-ethereum.ts
This seems to be mostly deprecated but one site I was testing on wanted it.
=> add net_version to injected ethereum provider

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
Also moved some blockchain spaghetti out of the JSX.
Closes https://github.com/coral-xyz/backpack/issues/884
=> normalize address in send input validation

packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ConnectHardware/ConnectHardwareFailure.tsx
Closes https://github.com/coral-xyz/backpack/issues/868
=> fix hardware help link

packages/app-extension/src/components/common/Account/CreatePassword.tsx, packages/react-xnft-renderer/src/Component.tsx
Closes https://github.com/coral-xyz/backpack/issues/874
=> add password show/hide on create password form

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/912
=> Added name truncation to Edit profile section

packages/app-extension/src/components/Unlocked/Settings/Preferences/Solana/ConnectionSwitch.tsx
The PR handles non-URL friendly URLs slightly more gracefully to avoid crashing the app
Closes https://github.com/coral-xyz/backpack/issues/831
=> Handled faulty custom rpc url gracefully

packages/app-extension/src/components/common/Account/SetupComplete.tsx
=> add appropriate fill colors to onboard icons

packages/app-extension/src/components/Onboarding/index.tsx, packages/app-extension/src/components/Unlocked/Settings/YourAccount/ChangePassword.tsx, packages/app-extension/src/components/common/Account/CreatePassword.tsx, packages/app-extension/src/components/common/Account/SetupComplete.tsx
closes #945 
closes #944
closes #943
=> various ticketed styling changes

.github/workflows/pull_request.yml
The build issue is that the package dependencies don't get built in the right order.
=> fix build with hack

packages/background/src/backend/solana-connection.ts, packages/background/src/frontend/solana-connection.ts, packages/common/src/constants.ts, packages/common/src/solana/background-connection.ts
This pull request aims to add support for `getTokenLargestAccounts` from Backpack's RPC connection.
=> Implement `getTokenLargestAccounts` RPC method

backend/reef/hasura/metadata/databases/default/tables/public_images.yaml
gives mod role permissions to read images.winner column, this change is live in prod
@callensm
=> let mod role read winner column

yarn.lock
root lockfile is getting out of sync, will come back to ensuring this doesn't happen in future
=> run yarn install from root

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
Closes https://github.com/coral-xyz/backpack/issues/963
=> fix solana address validation

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx, packages/recoil/src/atoms/balance.tsx, packages/recoil/src/atoms/ethereum/token.tsx, packages/recoil/src/atoms/solana/token.tsx
Percentage change was out by factor of 100. 
Closes https://github.com/coral-xyz/backpack/issues/961
=> percentage change calculation fix

packages/app-extension/src/components/Unlocked/Settings/Preferences/Ethereum/Connection.tsx
The PR fixes a lint issue that was introduced recently.
=> Fixes lint

backend/reef/hasura/metadata/databases/default/tables/auth_users.yaml, backend/reef/hasura/metadata/databases/default/tables/public_images.yaml, backend/workers/auth/package.json, backend/workers/auth/src/index.ts, backend/workers/auth/src/zeus/const.ts, backend/workers/auth/src/zeus/index.ts, packages/app-extension/src/components/Onboarding/index.tsx, packages/app-extension/src/components/Onboarding/pages/Finish.tsx, packages/app-extension/src/components/Onboarding/pages/InviteCodeForm.tsx, packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx, packages/app-extension/src/components/Onboarding/pages/RecoveryPhrase.tsx, packages/app-extension/src/components/common/Account/MnemonicInput.tsx, packages/background/src/backend/core.ts, yarn.lock
enables users to recover their username if they reset their wallet by searching for their public pubkey is in the list of derived keys from a mnemonic
=> account recovery onboarding flow

packages/app-extension/src/components/Unlocked/Swap.tsx
Closes https://github.com/coral-xyz/backpack/issues/1033
=> fix swap overflow in token input field

packages/app-extension/src/components/common/Account/ImportAccounts.tsx
Closes https://github.com/coral-xyz/backpack/issues/1031
=> fix hardcoded blockchain in eth ledger loading

packages/app-extension/src/components/Unlocked/Nfts/index.tsx, packages/common/src/solana/background-connection.ts, packages/common/src/solana/programs/token.ts, packages/common/src/solana/types.ts, packages/recoil/src/atoms/solana/nft.tsx, packages/recoil/src/atoms/solana/token.tsx, packages/recoil/src/hooks/solana/useLoadSplTokens.tsx, packages/recoil/src/types.ts
Extracted and shared types for everything token related
~~This might fix, we were sorting on id, thinking `publicKey` was a string while it isn't~~
#983
=> feat: Arrange types from the bottom for customSplTokenAccounts related stuff

packages/recoil/src/atoms/solana/token.tsx
We lost priceMint [here](https://github.com/coral-xyz/backpack/pull/1028/files#diff-c010c08096c39369ac278db5eb115b124c6da45a4f17dbc2563ddf497581bbe6L106-L118). The comment was relevant, not sure of the intent here.
Closes https://github.com/coral-xyz/backpack/issues/1049
=> add priceMint back to fix price display

packages/background/src/backend/core.ts, packages/background/src/backend/solana-connection.ts, packages/background/src/frontend/solana-connection.ts, packages/common/src/solana/background-connection.ts, packages/common/src/solana/transaction-helpers.ts, packages/recoil/src/hooks/useTransactionData.tsx
Closes https://github.com/coral-xyz/backpack/issues/1050
Closes https://github.com/coral-xyz/backpack/issues/1048
The PR makes all transactions `Versioned` in the codebase (except provider APIs since they need to conform the solana spec)
The PR also adds fee estimation for V0 transactions.
=> Follow ups versioned transactions

packages/app-extension/src/components/Onboarding/pages/Finish.tsx, packages/app-extension/src/components/Onboarding/pages/SetPassword.tsx
=> encode pass for memoryrouter during onboarding

packages/background/src/backend/keyring/index.ts
Closes https://github.com/coral-xyz/backpack/issues/1068
=> add missing save on blockchain keyring init

docker/image-proxy/Dockerfile, docker/image-proxy/fly.toml, packages/app-extension/src/components/Unlocked/Approvals/index.tsx, packages/app-extension/src/components/Unlocked/Apps/index.tsx, packages/app-extension/src/components/Unlocked/Nfts/Common.tsx, packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/app-extension/src/components/Unlocked/Settings/Xnfts/Detail.tsx, packages/app-extension/src/components/Unlocked/Settings/Xnfts/index.tsx, packages/app-extension/src/components/common/ProxyImage.tsx, packages/common-public/src/constants.ts, packages/common-public/src/utils.ts, packages/react-xnft-renderer/src/Component.tsx
The PR adds - 
1. Logic to proxy all image requests through our in-house imageproxy instance, we fallback to original if the request fails
2. Adds docker files and fly configuration file to the codebase that we should hook up to CI/CD (Right now I've manually deployed to fly)
TODO: Add a CDN in front of the proxy to further cache URLs
=> Adds image proxying using imageproxy

packages/common-public/src/constants.ts
For now its a naked cloudfront URL. 
Follow up to add a cert in AWS and make it a custom domain
=> Added cdn to image proxies

packages/app-extension/src/components/Locked/index.tsx
=> fix:alpha logo in extension

packages/app-extension/src/components/Unlocked/Settings/YourAccount/ShowRecoveryPhrase.tsx
=> make enter to submit work on show recovery phrase form

packages/app-extension/src/components/Unlocked/Settings/YourAccount/ShowPrivateKey.tsx
Ref https://github.com/coral-xyz/backpack/issues/392
=> make enter to submit work on show private key password form

packages/app-extension/src/components/Unlocked/Settings/Preferences/Blockchains.tsx, packages/app-extension/src/components/Unlocked/Settings/Preferences/Ethereum/index.tsx, packages/app-extension/src/components/Unlocked/Settings/Preferences/Solana/index.tsx, packages/app-extension/src/components/Unlocked/Settings/Preferences/index.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/app-extension/src/components/common/WithCopyTooltip.tsx
Closes https://github.com/coral-xyz/backpack/issues/1109
=> blockchain toggle ui changes

packages/provider-core/src/provider-ethereum.ts
Found this wrong return type while testing curve.fi
=> eth_chainId should return a string

packages/react-xnft-dom-renderer/README.md, packages/react-xnft-dom-renderer/package.json
Adds `files` to package.json that'll publish dist to npm.
Also adds README
=> Added files, README to dom renderer

packages/xnft-cli/index.js, packages/xnft-cli/package.json
=> xnft-cli init <dapp-name>

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RenameWallet.tsx
Ref https://github.com/coral-xyz/backpack/issues/392
=> make enter to submit work on rename wallet form

packages/app-extension/src/components/Unlocked/Nfts/Common.tsx
Closes https://github.com/coral-xyz/backpack/issues/726
=> fix truncation on collection name in nft grid

.github/workflows/pull_request.yml
Creates a comment listing changes to the root `yarn.lock` in PRs
I'll keep an eye on PRs over the next few days, if it becomes annoying we can remove it
=> add PR comment containing yarn.lock changes

.github/workflows/pull_requests.yml, .github/workflows/pull_requests_and_merges.yml
follow-up to #1148 
should fix the broken test in master https://github.com/coral-xyz/backpack/actions/runs/3262075397/jobs/5358389657
=> split GH actions files into PR-only and PR+master-merge actions

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
=> turned off spellcheck for account address

backend/workers/xnft-wrapper/src/index.ts
Updates the renderer to fetch all the changes deployed recently in https://github.com/coral-xyz/backpack/pull/1090
=> Updated renderer to use the latest

examples/xnft/prices/src/App/TokenList.tsx, examples/xnft/recoil/src/app.tsx, examples/xnft/table-anchor/src/app.tsx, packages/react-xnft-dom-renderer/src/Component.tsx, packages/react-xnft/src/reconciler.ts
Closes https://github.com/coral-xyz/backpack/issues/1165
Change API to `e.target.value` vs `e.data.value`. Added this change to the migration doc that'll be shared with devs
=> Fixes onChange event handlers on Input boxes

.github/workflows/pull_requests_and_merges.yml
Adds offset, deploys a workflow on `open PR ` to test it out
=> Adds version number offset

backend/workers/xnft-wrapper/src/index.ts
Originally made here - https://github.com/hkirat/backpack/pull/1/files
Adds logic to show warnings to users when there is a version collision b/w an xnft and extension version.
=> Added logic to show warnings for broken xnfts

.github/workflows/pull_requests_and_merges.yml
Don't see this workflow running after this got merged in so gonna revert for now.
=> Revert "Adds version number offset"

backend/workers/xnft-wrapper/src/index.ts
Follow up from https://github.com/coral-xyz/backpack/pull/1194 to fix ipfs links
=> Fixed ipfs links

packages/provider-core/src/provider-ethereum.ts
Never return a null chain id, default to 0x1. Closes #1178.
=> dont allow null chain id return in eth_chainId

packages/common-public/src/utils.ts
Potentially closes https://github.com/coral-xyz/backpack/issues/1186 , will follow up with the user
=> Fixes proxy images

packages/app-extension/src/app/App.css, packages/react-xnft-dom-renderer/src/Component.tsx
Closes https://github.com/coral-xyz/backpack/issues/1185
=> Fixes scrolls

backend/reef/hasura/metadata/databases/default/tables/appstore_pending_curator_reviews.yaml, backend/reef/hasura/migrations/default/1666186069950_alter_table_appstore_pending_curator_reviews_add_column_transaction/down.sql, backend/reef/hasura/migrations/default/1666186069950_alter_table_appstore_pending_curator_reviews_add_column_transaction/up.sql
Reverts coral-xyz/backpack#1203
=> Revert "add byte array column to review table"

packages/react-xnft/src/ReactDom.ts
Must be coding w/o my coffee. This needs to be a timeout and not an interval
=> interval->timeout

packages/xnft-cli/index.js
Since this is only used by developers (and not in production on the app-extension) , for now I'm making the latest renderer show up for developers
=> Open latest renderer for users testing locally

iframe-example.html
Follow up from https://github.com/coral-xyz/backpack/pull/1217 to fix the iframe example
=> Fix iframe example with the new provider API

backend/workers/xnft-wrapper/src/index.ts
These two have been updated - 
https://www.xnft.gg/app/C6rEseVodzAebN11CHLNLZtYZf9E5XtycbBSDPmYWFb
https://www.xnft.gg/app/DFiTps6Xp6hKGE2AWMYveNQ6mqA9TjFa6WJiWG9smHr6
=> Updated list of pending xnfts

backend/workers/xnft-wrapper/src/index.ts
Version is right after the scrollbars were fixed
=> New renderer version

packages/background/src/frontend/server-injected.ts
Used to enable twitter authentication flow to reopen backpack when done.
=> Allows whitelisted origins to make RPC calls to backpack

packages/background/src/frontend/solana-connection.ts, packages/common/src/solana/background-connection.ts
Closes https://github.com/coral-xyz/backpack/issues/1253
=> Fixed raw transactions

.github/workflows/pull_requests.yml
adds a comment using https://github.com/Fieldguide/action-hasura-change-summary
if [metadata](https://hasura.io/docs/latest/migrations-metadata-seeds/manage-metadata/) is changed
=> add PR comment if hasura metadata changes

packages/provider-core/src/root-provider-xnft.ts
Closes https://github.com/coral-xyz/backpack/issues/1233
=> Added backward compatibility to root xnft

packages/app-extension/src/components/Unlocked/Balances/StripeRamp.tsx
Closes https://github.com/coral-xyz/backpack/issues/1266
=> Fixed designs during onramp

backend/reef/hasura/metadata/databases/default/tables/auth_publickeys.yaml, backend/reef/hasura/metadata/databases/default/tables/auth_publickeys_history.yaml, backend/workers/auth/package.json, backend/workers/auth/src/zeus/const.ts, backend/workers/auth/src/zeus/index.ts
additional suggestions for #1223
=> one to many pubkeys suggestions

packages/react-xnft-dom-renderer/package.json, packages/react-xnft-dom-renderer/src/Component.tsx, packages/react-xnft-dom-renderer/src/components/Scrollbar.tsx
Closes https://github.com/coral-xyz/backpack/issues/1244
After trying out a bunch of things found https://github.com/xobotyi/react-scrollbars-custom that did the trick
We were originally using `react-custom-scrollbars` (very similar names amongst the two libraries). The old one has an issue on hover/if you have a connected mouse device where a white background shows up similar to https://github.com/coral-xyz/backpack/issues/1244 . 
This PR gets rid of those scrollbars.
Still need to decide how we change these scrollbars when the host theme changes. Right now it's an opaque black that works well on both light and dark but would be good to get design to help us figure out what the right thing to do here is.
=> Fixes scrollbars

backend/workers/xnft-wrapper/src/index.ts
Updates the prod renderer with fixes in the scrollbar, theming
=> Updated renderer

backend/workers/auth/src/index.ts
Worker updates for https://github.com/coral-xyz/backpack/pull/1257
- Support for both the old and new onboarding data styles
- Support for validating Solana signatures using a dummy transaction for hardware wallet support
=> updates to worker for multichain onboarding

backend/reef/hasura/metadata/databases/default/tables/auth_publickeys_history.yaml
Mistakenly removed in https://github.com/coral-xyz/backpack/pull/1289
=> add user_id permission to publickey history

packages/app-extension/src/components/Onboarding/pages/OnboardAccount.tsx
Closes https://github.com/coral-xyz/backpack/issues/1307
=> invalidate blockchain keyring init parameters if they are no longer valid

packages/wallet-standard/package.json, packages/wallet-standard/src/wallet.ts, yarn.lock
We've finally released the stable version. This PR updates Backpack to it. Expect semver updates only from here on out, and expect no more breaking changes for a while!
=> Wallet Standard v1.0.0

package.json, turbo.json, yarn.lock
https://turbo.build/repo/docs/reference/command-line-reference#--concurrency
=> increase turborepo concurrency & upgrade version

examples/xnft/tailwind/src/app.tsx, packages/react-xnft-dom-renderer/src/Component.tsx
Closes https://github.com/coral-xyz/backpack/issues/1316
Added example to show how we can support adornments using tailwind.
=> Added tw example, fixed tw classNames

packages/app-extension/src/components/Onboarding/pages/InviteCodeForm.tsx
Closes https://github.com/coral-xyz/backpack/issues/1344
=> fix invite code entry

packages/app-extension/src/components/common/Inputs.tsx
Adds multiline to new `TextInput` API.
=> Fixed multiline inputs

packages/react-xnft/src/reconciler.ts
Closes https://github.com/coral-xyz/backpack/issues/1338
=> Better error message from reconciler

packages/app-extension/src/components/Unlocked/Swap.tsx
Closes https://github.com/coral-xyz/backpack/issues/1361
=> fix scaling bug when decimal difference is negative

packages/app-extension/src/components/Unlocked/Balances/Balances.tsx, packages/app-extension/src/components/Unlocked/Balances/StripeRamp.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Ramp.tsx, packages/app-extension/src/components/Unlocked/Balances/TransferWidget.tsx
- Fix title casing on blockchain title in ramp table
- Use muted text for currency name to match other token table
- Misc cleanup of unused variables/imports
Closes https://github.com/coral-xyz/backpack/issues/1301
=> styling fixes for ramp buy table and misc cleanup

packages/app-extension/src/components/Unlocked/Apps/index.tsx, packages/app-extension/src/components/Unlocked/Settings/Preferences/index.tsx, packages/background/src/backend/core.ts, packages/background/src/backend/keyring/index.ts, packages/background/src/backend/store/preferences.ts, packages/background/src/frontend/server-ui.ts, packages/common/src/constants.ts, packages/recoil/src/atoms/preferences/index.tsx, packages/recoil/src/atoms/solana/xnft.tsx, packages/recoil/src/context/Notifications.tsx, packages/recoil/src/hooks/preferences/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/1322
=> add developer mode and only display simulator when it is enabled

packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/common/src/solana/index.ts
Closes https://github.com/coral-xyz/backpack/issues/1390
=> fix burning with multiple token amounts

packages/app-extension/src/components/Onboarding/pages/OnboardAccount.tsx
Closes https://github.com/coral-xyz/backpack/issues/1406
=> remove back button from onboarding success

packages/app-extension/src/components/Locked/index.tsx
=> feat: option to show password to unlock wallet

packages/app-extension/src/components/Unlocked/Settings/Preferences/AutoLock.tsx, packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RenameWallet.tsx
Ref https://github.com/coral-xyz/backpack/issues/392
=> make enter to submit work on auto-lock form

packages/app-extension/src/hooks/useIsONELive.ts
Fixes [issue 1411
](https://github.com/coral-xyz/backpack/issues/1411)
=> Fix useIsONELive.ts 

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RenameWallet.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/app-extension/src/components/common/Inputs.tsx
Also some misc cleanup.
Closes https://github.com/coral-xyz/backpack/issues/392
=> make enter to submit work on import private key

packages/app-extension/src/components/Unlocked/Balances/StripeRamp.tsx
Updated since we've updated the existing one to make stripe work in `0.4.0`
=> Updated stripe bundle link

packages/common/src/plugin.ts, packages/react-xnft-dom-renderer/src/Component.tsx
Fetching `style` from `viewData` for ReactXnfts that don't use the recent reconciler update
=> Adds backward reconciler cleanup

examples/xnft/media-streams/README.md, examples/xnft/media-streams/package.json, examples/xnft/media-streams/src/app.tsx, examples/xnft/media-streams/src/index.tsx, packages/app-extension/src/assets/iframe.html, packages/app-extension/src/assets/iframe.js, packages/react-xnft-dom-renderer/src/Component.tsx, packages/react-xnft/src/elements.tsx, packages/react-xnft/src/reconciler.ts
Useful specially for use cases where we have a `MediaStreamTrack` vs `src url` (eg camera and mic).
Also added `iframe.html` that users will have to open one time to give camera and mic permissions to the extension.
=> Added `Audio` and `Video` components

packages/wallet-standard/src/account.ts
This PR fixes the feature name for message signing.
=> wallet-standard: fix signMessage feature name

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RemoveWallet.tsx
Closes https://github.com/coral-xyz/backpack/issues/1427
=> Fixed remove active wallet

backend/workers/xnft-wrapper/src/index.ts
Adds tw and updates to the latest renderer
=> Update to latest renderer, adds tw

examples/xnft/provider-test/src/app.tsx, packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx, packages/app-extension/src/components/Unlocked/XnftPopovers/ErrorTransaction.tsx, packages/app-extension/src/components/Unlocked/XnftPopovers/Sending.tsx, packages/app-extension/src/components/Unlocked/XnftPopovers/Success.tsx, packages/common/src/plugin.ts, packages/provider-core/src/common/solana.ts, packages/recoil/src/atoms/transaction-request.tsx
Closes https://github.com/coral-xyz/backpack/issues/1085
=> Makes xnft.sendAndConfirm block UI until confirmation

packages/react-xnft/src/sdk/index.tsx
Follow up from https://github.com/coral-xyz/backpack/commit/cd96e23660550a380d8ef5dce2330cd4a4cdd744 . 
Removes an extra import I added
=> Permissions follow up

packages/app-extension/src/components/Unlocked/Apps/Plugin.tsx, packages/common/src/plugin.ts, packages/recoil/src/hooks/solana/usePlugins.tsx
`usePreference` uses the `xnft install address` vs the `xnft address`
=> Fix xnft address used in `usePreference`

examples/xnft/custom-components/src/app.tsx, packages/common/src/constants.ts, packages/common/src/plugin.ts, packages/provider-core/src/root-provider-xnft.ts
Useful for apps that need more real estate than just the popup width and height.
TODO: Add a parameter here that lets developers pop out video (small size, but popped out)
=> Expose fullscreen functionality to xnfts

packages/recoil/src/context/Notifications.native.tsx, packages/recoil/src/hooks/navigation.native.tsx
- creates notifications.native.tsx and navigation.native.tsx to stub out specific calls on mobile-only
=> native navigation/notification file stubs

packages/app-extension/src/components/Locked/LockedMenu.tsx, packages/app-extension/src/components/Locked/Reset/ResetWarning.tsx, packages/app-extension/src/components/Locked/Reset/ResetWelcome.tsx, packages/app-extension/src/components/common/Icon/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/1358
=> reset copy updates

packages/background/src/backend/solana-connection.ts, packages/background/src/frontend/solana-connection.ts, packages/common/src/solana/background-connection.ts
fixes the solana serialization between mobile app and service worker, originally implemented by armani
=> solana connection serialization fix between service worker / mobile app

packages/xnft-cli/index.js
Helps debug/verify version mismatches
=> add --version to xnft-cli

examples/xnft/recoil/package.json
More details in https://github.com/coral-xyz/backpack/pull/1468
=> Added esbuild to recoil example

packages/common/src/plugin.ts
Follow up from https://github.com/coral-xyz/backpack/pull/1473. 
Close the extension when popped out.
=> Close original window on popup

packages/app-mobile/package.json
=> disable tests in `app-mobile` package

backend/workers/feature-gates/src/FEATURES.ts
Since 0.4.0 was released we can enable stripe now.
=> Enabled stripe

examples/clients/simple/package.json, examples/clients/simple/src/SolanaWallet.tsx, yarn.lock
before:
```
import {
PhantomWalletAdapter,
BackpackWalletAdapter,
} from "@solana/wallet-adapter-wallets";
```
after:
```
import { PhantomWalletAdapter } from "@solana/wallet-adapter-phantom";
import { BackpackWalletAdapter } from "@solana/wallet-adapter-backpack";
```
=> installs specific wallets for simple client example

.github/workflows/pull_requests_and_merges.yml
to avoid name conflicts with existing tags
=> add 0.2.0 prefix to tags and releases

packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/app-extension/src/components/common/TokenAmountHeader.tsx
Also proxied an image request.
Closes https://github.com/coral-xyz/backpack/issues/1402
=> fix crash on nft burn

yarn.lock
no yarn.lock changes from #1505 so this adds em
=> updates yarn.lock file from #1505

examples/xnft/prices/package.json, packages/app-extension/src/components/Unlocked/Apps/index.tsx, packages/recoil/package.json, packages/recoil/src/atoms/solana/xnft.tsx, packages/recoil/src/hooks/solana/usePlugins.tsx, yarn.lock
- fixes One Entrypoint https://github.com/coral-xyz/backpack/issues/1524
=> Clean up appIcons vs xnfts vs plugins

yarn.lock
there are some minor yarn.lock changes that crept in too (removing unused packages). one day we'll be free of this yarn.lock purgatory lol
=> remove .gitmodules

packages/app-extension/src/components/common/index.tsx
=> fixing hover state of danger button in dark mode

packages/app-extension/src/app/App.tsx, packages/app-extension/src/app/ErrorBoundary.tsx, packages/app-extension/src/components/common/Layout/Router.tsx, packages/background/src/backend/core.ts, packages/background/src/frontend/server-ui.ts, packages/common/src/constants.ts
Filed https://github.com/coral-xyz/design-issues/issues/32 for a better design for this.
Closes https://github.com/coral-xyz/backpack/issues/1543
=> Adds error boundary

packages/app-mobile/src/components/Unlocked/Balances/TransferWidget.tsx, packages/app-mobile/src/screens/Unlocked/BalancesScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/Balances.tsx, packages/app-mobile/src/screens/Unlocked/components/index.tsx, yarn.lock
=> balance screen updates

packages/app-extension/src/app/ErrorBoundary.tsx, packages/app-extension/src/permissions/NotificationPermissions.tsx
Closes https://github.com/coral-xyz/design-issues/issues/32
Closes https://github.com/coral-xyz/design-issues/issues/23
=> New design for error boundary, notifications permissions

packages/app-extension/src/components/Unlocked/Settings/YourAccount/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/1573
=> hide show secret recovery phrase menu item for ledger keyrings

packages/recoil/src/atoms/prices.tsx
=> fix: catch API request fails

backend/workers/feature-gates/src/FEATURES.ts, packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/Unlocked/Balances/RecentActivity.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/common/src/feature-gates.ts, packages/common/src/index.ts, packages/common/src/notifications.ts, packages/common/src/solana/programs/xnft.ts, packages/recoil/src/atoms/index.tsx, packages/recoil/src/atoms/notifications.ts, packages/recoil/src/hooks/index.tsx, packages/recoil/src/hooks/useRecentNotifications.tsx, packages/themes/src/index.tsx
Also feature gates this so we can release independently
TODO: Add JWT to make the fetching of the notifications secure.
=> Adds new notification UI

backend/native/backend-ws/src/index.ts, backend/native/backpack-api/src/auth/middleware.ts, backend/native/backpack-api/src/index.ts, packages/app-extension/src/api/preferences.ts, packages/app-extension/src/app/Router.tsx, packages/recoil/src/atoms/notifications.ts
The PR adds
1. A bunch of try catches in the backend
2. removes username args from everywhere since we're using JWT now
=> Added backend fallbacks, removed usernames from everywhere

packages/app-extension/src/components/Unlocked/Nfts/Experience.tsx
Follow up https://github.com/coral-xyz/backpack/pull/1555
=> Fixed type warnings 

backend/workers/auth/src/onramp/db.ts
=> fix zeus import path in auth/onramp worker

backend/workers/auth/src/index.ts
=> fix jwt domain

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/WalletDetail.tsx, packages/blockchains/evm/src/keyring/index.ts, packages/blockchains/keyring/src/blockchain.ts, packages/blockchains/keyring/src/ledger.ts, packages/blockchains/keyring/src/types.ts, packages/blockchains/solana/src/keyring/index.ts
- Fix attempt to remove public key from undefined keyring.
- Fix some inconsistent menu casing
- Fix bug where you could attempt to remove the last public key for a hardware wallet which resulted in a crash
Closes https://github.com/coral-xyz/backpack/issues/1594
=> fix delete public key bug for hardware only onboard

backend/native/backend-ws/src/auth/index.ts, backend/native/backpack-api/src/auth/middleware.ts, backend/native/backpack-api/src/db/preference.ts, backend/native/backpack-api/src/routes/v1/preferences.ts, backend/native/xnft-api-server/src/controllers/notifications.ts, backend/native/xnft-api-server/src/db/index.ts, backend/native/xnft-api-server/src/express-app.ts, backend/native/xnft-api-server/src/index.ts, backend/native/xnft-api-server/src/v1/notifications.ts, packages/app-extension/src/permissions/NotificationPermissions.tsx
The PR adds a few follow ups to jwts for chats related to auth
=> Follows ups to chat and notification jwts

backend/native/xnft-api-server/src/db/index.ts
Fixes bug in put notifications to use uuid vs username
=> username -> uuid

packages/app-mobile/src/components/NavHeader.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx
=> nav header fixes

backend/native/backpack-api/src/db/notifications.ts, backend/native/xnft-api-server/src/db/index.ts, packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/Unlocked/Settings/Xnfts/Detail.tsx, packages/common/src/notifications.ts, packages/common/src/solana/programs/xnft.ts, packages/recoil/src/atoms/notifications.ts
=> More follow ups in notifications

backend/workers/auth/src/index.ts, backend/workers/auth/src/jwt.ts, backend/workers/auth/src/util.ts, backend/workers/auth/src/validation.ts
Just splitting up some functions into different files.
=> split up auth worker into files

backend/native/zeus/package.json
=> add prettier to output of zeus

backend/workers/auth/src/index.ts
an endpoint that returns details about the user linked to the jwt cookie or querystring param
=> add /me endpoint to auth worker

packages/recoil/src/atoms/feature-gates.ts, packages/recoil/src/atoms/notifications.ts
Using selectors for state variables that don't need to be updated.
=> atom -> selector

packages/background/src/backend/core.ts
Closes https://github.com/coral-xyz/backpack/issues/1658
=> fix uuid regressions

package.json
Temporarily remove this while figuring out some linting bugs.
=> remove eslint lint-staged command

packages/recoil/src/atoms/index.tsx, packages/recoil/src/atoms/preferences/connection-urls.tsx, packages/recoil/src/atoms/preferences/index.tsx, packages/recoil/src/atoms/solana/xnft.tsx
There is a circular dependency b/wt
preferences/etherum.ts
preferences/index.ts
in `packages/recoil`
causing the following error.
=> Removes circular dependency 

.github/workflows/backend-backpack-api.yml, backend/native/backpack-api/src/config.ts, package.json
Fix CI/CD flow for backpack-api. Also calls `patch-package` conditionally only if `app-mobile` is present. cc @peterpme
=> Fix CI/CD flow for backpack-api

packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx
closes https://github.com/coral-xyz/backpack/issues/1676
=> fix recovery on add account

packages/background/src/backend/core.ts, packages/common/src/constants.ts, packages/recoil/src/atoms/feature-gates.ts, packages/recoil/src/context/Notifications.tsx
Closes https://github.com/coral-xyz/backpack/issues/1688
=> Update recoil state for feature gates

backend/native/zeus/src/zeus/const.ts, backend/native/zeus/src/zeus/index.ts
Updated @coral-xyz/zeus to incorporate recent changes
=> Updated zeus

backend/native/zeus/src/zeus/const.ts, backend/native/zeus/src/zeus/index.ts
Reverts coral-xyz/backpack#1691
=> Revert "Updated zeus"

backend/native/backpack-api/src/db/friendships.ts, backend/native/backpack-api/src/routes/v1/friends.ts, backend/reef/hasura/migrations/default/1670240775235_alter_table_auth_users_add_column_spam_count/down.sql, backend/reef/hasura/migrations/default/1670240775235_alter_table_auth_users_add_column_spam_count/up.sql, backend/reef/hasura/migrations/default/1670240819706_alter_table_auth_friendships_add_column_user1_spam_user2/down.sql, backend/reef/hasura/migrations/default/1670240819706_alter_table_auth_friendships_add_column_user1_spam_user2/up.sql, backend/reef/hasura/migrations/default/1670240832448_alter_table_auth_friendships_add_column_user2_spam_user1/down.sql, backend/reef/hasura/migrations/default/1670240832448_alter_table_auth_friendships_add_column_user2_spam_user1/up.sql, backend/reef/hasura/migrations/default/1670240838082_alter_table_auth_friendships_alter_column_user1_spam_user2/down.sql, backend/reef/hasura/migrations/default/1670240838082_alter_table_auth_friendships_alter_column_user1_spam_user2/up.sql, backend/reef/hasura/migrations/default/1670241860627_alter_table_auth_users_drop_column_spam_count/down.sql, backend/reef/hasura/migrations/default/1670241860627_alter_table_auth_users_drop_column_spam_count/up.sql, packages/app-extension/src/components/Unlocked/Messages/ChatScreen.tsx, packages/chat-sdk/src/components/Banner.tsx, packages/chat-sdk/src/components/ChatContext.tsx, packages/chat-sdk/src/components/ChatRoom.tsx, packages/chat-sdk/src/components/EmptyChat.tsx, packages/chat-sdk/src/components/FullScreenChat.tsx
PR adds functionality to block users, mark them as spam and UI features along with it.
=> Added blocked, spam functionality

packages/app-extension/src/components/Onboarding/pages/Finish.tsx, packages/background/src/backend/keyring/index.ts
Mitigates https://github.com/coral-xyz/backpack/issues/1731
=> persist username account create with unlock

backend/native/backpack-api/src/routes/v1/proxy.ts, backend/native/backpack-api/src/routes/v1/users.ts
Closes https://github.com/coral-xyz/backpack/issues/1747
=> clean up error handling in backpack-api

backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/routes/v1/users.ts, backend/native/backpack-api/src/validation/user.ts
Adds the endpoints required for https://github.com/coral-xyz/backpack/issues/1599
=> add methods to add/remove public keys from users

backend/native/backpack-api/src/routes/v1/users.ts, packages/recoil/src/context/Notifications.tsx
Use copies to fix read only errors
Closes https://github.com/coral-xyz/backpack/issues/1761
Closes https://github.com/coral-xyz/backpack/issues/1760
=> fix wallet create and delete

backend/native/backpack-api/package.json, backend/native/backpack-api/src/db/xnftSecrets.ts, backend/native/backpack-api/src/routes/v1/users.ts, packages/app-extension/src/plugin/Renderer.tsx, packages/common-public/src/types.ts, packages/recoil/src/atoms/preferences/index.tsx, packages/recoil/src/hooks/preferences/index.tsx
A way to expose xnft jwts that app developers to verify users identity on the backend.
=> Adds xnft jwts

packages/app-extension/src/components/Unlocked/WithAuth.tsx
=> fix race condition in WithAuth and rename variables for clarity

packages/app-extension/src/app/Router.tsx
=> fix bug that opened two onboarding pages

packages/background/src/backend/core.ts
Followup for https://github.com/coral-xyz/backpack/pull/1787
=> send active user updated notification on jwt update

packages/app-extension/src/components/Locked/Reset/ResetWarning.tsx, packages/app-extension/src/components/Unlocked/Settings/YourAccount/index.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/background/src/backend/core.ts, packages/background/src/backend/keyring/index.ts, packages/background/src/backend/store/preferences.ts, packages/background/src/backend/store/usernames.ts, packages/background/src/frontend/server-ui.ts, packages/common/src/constants.ts, packages/recoil/src/atoms/preferences/index.tsx, packages/recoil/src/context/Notifications.tsx
closes https://github.com/coral-xyz/backpack/issues/1694
TODO:
=> username logout part 1

packages/background/src/backend/core.ts, packages/recoil/src/context/Notifications.tsx
Closes https://github.com/coral-xyz/backpack/issues/1796.
=> fix enabled blockchains on user account switch

packages/app-extension/src/components/Unlocked/Messages/ProfileScreen.tsx
Right now it showed `Loading...`
=> Added loader before profile screen

backend/native/backpack-api/src/routes/v1/users.ts, backend/native/backpack-api/src/validation/user.ts, packages/app-extension/src/components/Locked/Reset/ResetWarning.tsx, packages/app-extension/src/components/Onboarding/pages/HardwareDefaultAccount.tsx, packages/app-extension/src/components/Onboarding/pages/HardwareOnboard.tsx, packages/app-extension/src/components/Onboarding/pages/HardwareSearch.tsx, packages/app-extension/src/components/Onboarding/pages/OnboardAccount.tsx, packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx, packages/app-extension/src/components/Onboarding/pages/RecoverAccountUsernameForm.tsx, packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ConnectHardware/index.tsx, packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx, packages/app-extension/src/components/Unlocked/Settings/Preferences/Blockchains.tsx, packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RemoveWallet.tsx, packages/app-extension/src/components/Unlocked/WithAuth.tsx, packages/app-extension/src/hooks/useAuthentication.tsx, packages/app-extension/src/options/Options.tsx, packages/background/src/backend/core.ts, packages/background/src/backend/keyring/index.ts, packages/background/src/frontend/server-ui.ts, packages/blockchains/keyring/src/blockchain.ts, packages/common/src/index.ts, packages/recoil/src/atoms/preferences/index.tsx
Attempts to add and remove public keys on the server every time a change happens on the client. Also a fair bit of cleanup and reuse of components (particularly the hardware bits).
Errors on public key conflicts are not handled gracefully yet, this will be dealt with in subsequent PRs.
Closes https://github.com/coral-xyz/backpack/issues/1599
=> update username associations everytime a pubkey is created or deleted

packages/app-extension/src/components/Unlocked/Settings/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/1751
Also removes duplicate setting of active wallet which backend handles automatically.
=> dont use html5 validation on import secret key

backend/native/backpack-api/src/routes/v1/authenticate.ts, backend/native/backpack-api/src/routes/v1/users.ts, backend/native/backpack-api/src/validation/signature.ts, backend/native/backpack-api/src/validation/user.ts, packages/background/src/backend/core.ts
Includes some cleanup of validation functions and a generic function that accepts a blockchain parameter.
Closes https://github.com/coral-xyz/backpack/issues/1818
=> validate add public key signature

backend/native/backpack-api/src/routes/v1/users.ts, packages/app-extension/src/components/Unlocked/Settings/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/1822
=> display an error on public key in use during private key import

backend/native/xnft-api-server/src/db/users.ts, backend/native/xnft-api-server/src/v1/users.ts
Compiling backend api docs on gitbook, these made sense to include along with the others.
=> Added more routes to `xnft-api-server`

packages/app-extension/src/components/Unlocked/Balances/Balances.tsx, packages/background/src/frontend/solana-connection.ts, packages/common/package.json, packages/common/scripts/config.sh, packages/common/src/solana/background-connection.ts, packages/common/src/solana/programs/token.ts, packages/common/src/solana/programs/xnft.ts, packages/common/src/solana/types.ts, packages/recoil/package.json, packages/recoil/src/atoms/solana/token.tsx, packages/recoil/src/hooks/useTransactionData.tsx, yarn.lock
replaces https://github.com/coral-xyz/backpack/pull/1388
=> use token metadata properly

backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/index.ts, backend/native/backpack-api/src/routes/v1/public-keys.ts
Closes https://github.com/coral-xyz/backpack/issues/1726
=> add an api endpoint to query user ids based on blockchain/public key

packages/app-mobile/package.json, packages/app-mobile/src/components/BottomDrawerCards.tsx, packages/app-mobile/src/components/BottomDrawerEthereumConfirmation.tsx, packages/app-mobile/src/components/BottomDrawerSolanaConfirmation.tsx, packages/app-mobile/src/components/Icon.tsx, packages/app-mobile/src/components/TokenAmountHeader.tsx, packages/app-mobile/src/components/TransactionData.tsx, packages/app-mobile/src/components/Unlocked/Balances/TransferWidget.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/hooks/index.ts, packages/app-mobile/src/hooks/useIsValidAddress.tsx, packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/screens/Unlocked/BalancesScreen.tsx, packages/app-mobile/src/screens/Unlocked/DepositScreen.tsx, packages/app-mobile/src/screens/Unlocked/SendTokenScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/ChangePasswordScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsMenuList.tsx, packages/app-mobile/src/screens/Unlocked/YourAccountScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/Balances.tsx, yarn.lock
- balance detail fixes
- fix detail vs. list receive screen
- some nice extras i think
- update routes
- fix send token flow
- updatesz hehe
=> balance and a bunch of other stuff lol

packages/app-extension/src/components/Unlocked/Settings/YourAccount/ChangePassword.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/1841
=> fix forgot password screen from settings

packages/app-extension/src/components/Unlocked/Nfts/Collection.tsx, packages/background/src/backend/solana-connection.ts, packages/background/src/frontend/solana-connection.ts, packages/common/src/constants.ts, packages/common/src/solana/background-connection.ts, packages/common/src/solana/programs/token.ts, packages/common/src/solana/types.ts, packages/recoil/src/atoms/balance.tsx, packages/recoil/src/atoms/prices.tsx, packages/recoil/src/atoms/solana/nft.tsx, packages/recoil/src/atoms/solana/token.tsx, packages/recoil/src/context/Notifications.tsx, packages/recoil/src/hooks/solana/useLoadSplTokens.tsx, yarn.lock
Should make the extension load a bit faster.
=> fetch nft uri data lazily

packages/app-extension/src/components/common/Account/ImportAccounts.tsx
Closes https://github.com/coral-xyz/backpack/issues/1859
=> remove public key conflict check if not using jwt

packages/app-extension/src/components/Unlocked/Nfts/NftTable.tsx, packages/app-extension/src/components/Unlocked/Nfts/index.tsx
This PR fixes: 
#1870 
#1866 
#1865
=> Virtual list: Loading indicators and styling fixes

packages/app-extension/src/components/Unlocked/Balances/RecentActivity.tsx, packages/app-extension/src/components/common/EmptyState.tsx
Closes https://github.com/coral-xyz/backpack/issues/1887
=> Empty state for `recent activity`

packages/app-mobile/src/components/Form.tsx, packages/app-mobile/src/components/TokenInputField.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/screens/ImportPrivateKeyScreen.tsx, packages/app-mobile/src/screens/Unlocked/SendTokenScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/Balances.tsx
- fix send and token input
- adjust prop
=> send flow updates

packages/app-extension/src/components/Onboarding/pages/CreateOrImportWallet.tsx, packages/app-mobile/src/navigation/OnboardingNavigator.tsx
This is better as a wallet, to not confuse it with a Backpack account.
=> account to wallet wording tweak

packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx, packages/app-extension/src/components/Unlocked/Approvals/index.tsx, packages/app-extension/src/components/common/TransactionData.tsx, packages/react-common/src/components/base/Inputs.tsx
some cosmetic updates to the tx approval screen to match figma
=> tx approval styles

packages/app-extension/src/app/Router.tsx, packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx, packages/app-extension/src/components/common/TransactionData.tsx, packages/app-extension/src/utils/solana.ts, packages/common/src/types.ts, packages/react-common/src/components/base/Inputs.tsx, packages/recoil/src/hooks/useTransactionData.tsx
Closes https://github.com/coral-xyz/backpack/issues/1918
Notice that `network fee` now already contains the `priority fee` if a platform already adds it to their transactions upfront.
=> Disable priority fee if already present in tx

packages/app-mobile/app.config.js, packages/app-mobile/index.js, packages/app-mobile/src/App.tsx, packages/app-mobile/src/hooks/useLoadedAssets.tsx, packages/app-mobile/src/navigation/OnboardingNavigator.tsx
=> app loading frame fixes so no null screen

packages/common/src/browser/extension.ts
=> Reuse popup window if available else create new.

packages/app-extension/src/components/Unlocked/Nfts/Collection.tsx, packages/app-extension/src/components/Unlocked/Nfts/Common.tsx, packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/app-extension/src/components/Unlocked/Nfts/NftTable.tsx, packages/app-extension/src/components/Unlocked/Nfts/index.tsx, packages/app-extension/src/components/Unlocked/Settings/AvatarHeader/UpdateProfilePicture.tsx, packages/common/src/types.ts, packages/recoil/src/atoms/nft.tsx, packages/recoil/src/equals.ts, packages/recoil/src/hooks/index.tsx, packages/recoil/src/hooks/useNftMetadata.tsx
- New Collections atom that uses effects to decouple polling updates from UI
- Update Avatar dashed border radius
- Removes need of useLoader hook and fixes 
- #1888 
- #1870
=> New nftCollections Atoms (& remove useLoader)

packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/app-extension/src/index.tsx, packages/common/src/browser/extension.ts
=> Fix popout race-condition -> wait for popup to be fully opened

packages/app-extension/src/components/Unlocked/Nfts/Collection.tsx
=> Fix Collections

backend/native/backend-ws/src/index.ts
Initialises redis on startup to avoid subscribing before redis is connected
=> Fixes race condition

packages/app-extension/src/components/Unlocked/Balances/Balances.tsx
Closes https://github.com/coral-xyz/backpack/issues/1972
=> fix negative change percent font size

packages/background/.eslintrc.js, packages/chat-sdk/.eslintrc.js, packages/common-public/.eslintrc.js, packages/common/.eslintrc.js, packages/db/.eslintrc.js, packages/deptool/.eslintrc.js, packages/ledger-injection/.eslintrc.cjs, packages/message-sdk/.eslintrc.js, packages/provider-core/.eslintrc.js, packages/provider-injection/.eslintrc.js, packages/react-xnft-dom-renderer/.eslintrc.js, packages/react-xnft/.eslintrc.js, packages/recoil/.eslintrc.js, packages/themes/.eslintrc.js
Parsing Error: Eslint was configured to run
=> fixes "eslint was configured to run"

packages/message-sdk/src/components/Inbox.tsx
=> feat: debounce results for contact search

packages/app-mobile/src/components/Icon.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/screens/Unlocked/BalancesScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsRow.tsx, packages/app-mobile/src/screens/Unlocked/WalletListScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/Balances.tsx
- adds icon to wallet list
- activating a new wallet should work
=> wallet list changes

packages/app-mobile/src/navigation/LockedNavigator.tsx, packages/app-mobile/src/navigation/OnboardingNavigator.tsx, packages/app-mobile/src/navigation/RootNavigator.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/screens/Unlocked/NftCollectiblesScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsRow.tsx
- clean up the onboarding
- fix bottom sheet
=> fixes onboarding navigator

packages/message-sdk/src/components/Inbox.tsx
Search doesnt work for 3 lettered people
=> update debounce filter

packages/common-public/src/utils.ts
Reverts a part of the change made here - https://github.com/coral-xyz/backpack/commit/4cd4c482f29f712569b85e3c07c057b4221b5838
cc @peterpme this may break mobile if your changes depended on it
=> Reverts isMobile variable

packages/app-extension/src/app/Router.tsx, packages/app-extension/src/components/Unlocked/Messages/Contacts.tsx, packages/app-extension/src/components/Unlocked/Messages/MessageOptions.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/app-extension/src/components/common/Layout/Router.tsx, packages/chat-sdk/src/components/Banner.tsx, packages/chat-sdk/src/components/FullScreenChat.tsx, packages/chat-sdk/src/components/ScrollbarImpl.tsx, packages/common/src/constants.ts, packages/message-sdk/src/components/ProfileScreen.tsx, packages/react-common/.eslintrc.js, packages/react-common/src/components/toasts/Success.tsx, packages/react-common/src/components/toasts/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/2053
Closes https://github.com/coral-xyz/backpack/issues/2038
Closes https://github.com/coral-xyz/backpack/issues/2037
Closes https://github.com/coral-xyz/backpack/issues/2025
=> Messsage polishes

packages/common/src/browser/common.ts, packages/common/src/browser/extension.ts
TLDR mozilla supports chrome.runtime
=> removes browser.runtime

packages/app-mobile/.eslintrc.js, packages/eslint-config-custom/native.js, packages/eslint-config-custom/shared/core.js, packages/eslint-config-custom/shared/react.js, packages/eslint-config-custom/web.js
- add comments
- some debugging
- eslint config changes
=> eslint config changes

packages/background/src/backend/core.ts, packages/background/src/backend/keyring/index.ts, packages/background/src/backend/store/preferences.ts, packages/background/src/frontend/server-ui.ts, packages/background/src/types.ts, packages/common/src/index.ts, packages/common/src/preferences.ts, packages/common/src/types.ts, packages/recoil/src/atoms/preferences/index.tsx, packages/recoil/src/context/Notifications.tsx
some of the types that were being used for preferences were wrong
=> fix and consolidate preferences types

packages/background/src/types.ts
This type was wrong.
Should probably be renamed to KeyringType or similar.
=> fix public key type

packages/app-extension/src/components/Unlocked/Nfts/Experience.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/SendMessage.tsx, packages/db/src/hooks/chats.tsx
More message polishes/bug fixes
Related https://github.com/coral-xyz/backpack/issues/2107
=> Messaging polishes

packages/app-extension/src/components/Onboarding/index.tsx, packages/app-extension/src/components/Onboarding/pages/AlreadyOnboarded.tsx, packages/app-extension/src/components/Onboarding/pages/OnboardAccount.tsx, packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx
Closes https://github.com/coral-xyz/backpack/issues/2086
=> display error if trying to onboard with an already onboarded wallet

packages/chat-sdk/src/components/SendMessage.tsx
Closes https://github.com/coral-xyz/backpack/issues/2127
=> autofocus send on chat open

backend/native/backpack-api/src/db/nft.ts, backend/native/backpack-api/src/routes/v1/nft.ts, packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx, packages/app-extension/src/components/common/Layout/Router.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/SendMessage.tsx
1. fixes replies
2. Closes https://github.com/coral-xyz/backpack/issues/2108
=> Message polishes

package.json, packages/app-mobile/.eslintrc.js, packages/app-mobile/src/App.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/hooks/recoil.tsx, packages/app-mobile/src/screens/Unlocked/BalancesScreen.tsx, packages/app-mobile/src/screens/Unlocked/RecentActivityScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/BalanceSummaryWidget.tsx, packages/app-mobile/src/screens/Unlocked/components/Balances.tsx, packages/recoil/src/hooks/wallet.tsx, yarn.lock
- adds working selectors
- fix recent activity screen
- fix
=> mobile working again

packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/screens/Unlocked/BalancesScreen.tsx, packages/app-mobile/src/screens/Unlocked/NftCollectiblesScreen.tsx
- move wallet list to top level navigator
- re-enable nft and apps tabs and start fixing
=> re-enable nft / apps tabs

backend/native/backpack-api/src/routes/v1/nft.ts, packages/app-extension/src/app/Router.tsx, packages/db/src/api/friendships.ts, packages/db/src/signaling/Signaling.ts, packages/db/src/signaling/SignalingManager.ts
User account switching
Nokiamon appearing when it shouldn't
=> Chat fixes

backend/reef/hasura/metadata/databases/default/tables/auth_collections.yaml, backend/reef/hasura/metadata/databases/default/tables/auth_user_nfts.yaml
The permissions are causing the backpack chat to not open up
=> Fixed DB permissions

packages/app-extension/src/components/Unlocked/Settings/Preferences/TrustedSites.tsx, packages/app-extension/src/components/common/WalletList.tsx
=> feat: shorten long  wallet names

packages/app-extension/src/app/App.css, packages/app-extension/src/components/common/Layout/Router.tsx, packages/chat-sdk/src/components/SendMessage.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx
increases size
placeholder
close emoji on message box click
=> tagging follow ups

packages/app-extension/src/components/Unlocked/WithSyncAccount.tsx, packages/background/src/backend/core.ts
Closes https://github.com/coral-xyz/backpack/issues/2179
=> fix key removal bug

packages/app-extension/src/components/Onboarding/pages/HardwareSign.tsx, packages/ledger-injection/src/index.ts
Closes https://github.com/coral-xyz/backpack/issues/1562
Closes https://github.com/coral-xyz/backpack/issues/2119
=> add error to hardware onboarding if blind signing disabled

packages/app-extension/src/components/Onboarding/pages/HardwareSearch.tsx, packages/app-extension/src/components/Onboarding/pages/MnemonicSearch.tsx, packages/app-extension/src/components/Unlocked/WithSyncAccount.tsx, packages/app-extension/src/components/common/Account/ImportAccounts.tsx, packages/background/src/backend/core.ts, packages/background/src/backend/keyring/index.ts, packages/background/src/backend/store/keyname.ts, packages/background/src/frontend/server-ui.ts, packages/blockchains/evm/src/keyring/index.ts, packages/blockchains/keyring/src/blockchain.ts, packages/blockchains/keyring/src/types.ts, packages/blockchains/solana/src/keyring/index.ts, packages/common/src/constants.ts
Adds a call to the WithSync component to lookup any remaining dehydrated wallets and sync them if they exist on the mnemonic.
Closes https://github.com/coral-xyz/backpack/issues/2149
=> sync dehydrated wallets with mnemonic

packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ImportSecretKey.tsx
Closes https://github.com/coral-xyz/backpack/issues/2202
=> disable import private key button while loading

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/RemoveWallet.tsx
Closes https://github.com/coral-xyz/backpack/issues/2182
=> disable remove wallet button while loading

packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/ImportSecretKey.tsx
Closes https://github.com/coral-xyz/backpack/issues/2203
=> fix already imported private key error

packages/app-extension/src/components/Unlocked/Nfts/EntryONE.tsx, packages/app-mobile/src/screens/Unlocked/AppListScreen.tsx, packages/common/src/solana/programs/xnft.ts, packages/recoil/src/atoms/solana/xnft.tsx, packages/recoil/src/hooks/solana/usePlugins.tsx
Updates
- program ID
- inline IDL
- object paths for data in metadata blobs
- injected installations public keys / data
- minor adjustments to data fetching flow
=> xNFT Migration to New Program

packages/app-extension/src/app/Router.tsx
Fixes a crash when connecting to a lock wallet.
=> check for unlock prior to connect so unlock screen is correctly displayed

examples/clients/simple/package.json, examples/clients/simple/src/App.tsx, examples/clients/simple/src/EthereumWallet.tsx, examples/clients/simple/src/ethereum/SendWeiButton.tsx, examples/clients/simple/src/ethereum/SignMessageButton.tsx, examples/clients/simple/src/index.tsx, examples/clients/simple/src/solana/SendAllButton.tsx, examples/clients/simple/src/solana/SendLamportButton.tsx, examples/clients/simple/src/solana/SendTokenButton.tsx, examples/clients/simple/src/solana/SignMessageButton.tsx, examples/clients/simple/tsconfig.eslint.json
- Remove SRM in favour of USDC
- Add an extra transaction for testing send all
- Linting setup
=> updates to simple client

packages/app-extension/src/components/Unlocked/Swap.tsx, packages/recoil/src/context/Swap.tsx
Closes https://github.com/coral-xyz/backpack/issues/2095
=> display an error if insufficient fee to make swap

packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx
=> #2233 changes user to account in ui

packages/app-extension/src/components/Unlocked/Approvals/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/2242
=> fix alignment of long wallet names on approval screens

examples/clients/simple/src/solana/SendLamportButton.tsx, examples/clients/simple/src/solana/SendTokenButton.tsx, packages/background/src/backend/core.ts, packages/background/src/backend/solana-connection.ts, packages/background/src/frontend/server-injected.ts, packages/background/src/frontend/server-ui.ts, packages/recoil/src/hooks/useTransactionData.tsx
- Adds native SOL support to simulation
- Adds versioned transaction support by looking up the correct keys and passing them to simulate
- Fixes a bug where only the wallet public key was passed to simulate so balance changes to ATAs would not be found
Closes https://github.com/coral-xyz/backpack/issues/753
=> balance change simulation improvements (sol and versioned transaction support)

packages/app-mobile/src/components/BottomDrawerCards.tsx, packages/app-mobile/src/components/BottomDrawerEthereumConfirmation.tsx, packages/app-mobile/src/components/BottomDrawerSolanaConfirmation.tsx, packages/app-mobile/src/components/BottomSheetModal.tsx, packages/app-mobile/src/components/TransactionData.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/screens/Unlocked/SendTokenScreen.tsx
- ethereum transaction modal
- dismiss keyboard and fix
=> better bottom modal

packages/recoil/package.json, yarn.lock
fixes builds in master but I don't know if the version difference will cause other issues
=> add metaplex with specific version to fix build

.gitignore, backend/workers/jupiter-proxy/package.json, backend/workers/jupiter-proxy/src/feeAccounts.json, backend/workers/jupiter-proxy/src/index.ts, backend/workers/jupiter-proxy/wrangler.toml, packages/recoil/src/atoms/solana/jupiter.tsx, packages/recoil/src/context/Swap.tsx, turbo.json, yarn.lock
Indexes live swaps for calculating referral payments
I'll add more details in a follow up PR
Using supabase right now to allow rapid changes and getting something up and running ASAP. It can be moved to hasura if that makes more sense but the frontend code would remain the same regardless.
=> add swap indexing

backend/native/backend-ws/src/db/nfts.ts, backend/native/backpack-api/src/routes/v1/friends.ts, backend/native/notifications-worker/src/db/nft.ts, packages/app-extension/src/components/Unlocked/Messages/Requests.tsx, packages/app-extension/src/components/Unlocked/Settings/SettingsNavStackDrawer.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/background/src/backend/push-notifications.ts, packages/chat-sdk/src/components/MediaContent.tsx, packages/react-common/src/chat/SignalingManager.ts
also adds foundation for requests
=> Fixes Bunch of small bugs in chats

backend/native/backpack-api/src/auth/middleware.ts, backend/native/backpack-api/src/config.ts, backend/native/backpack-api/src/db/nft.ts, backend/native/backpack-api/src/index.ts, backend/native/backpack-api/src/routes/v1/tx-parsing.ts
Proxy requests so we dont have to expose our API secret on the frontend
Related - https://github.com/coral-xyz/backpack/pull/2051
=> added proxy requests for tx parsing

yarn.lock
brings root yarn.lock up to date
=> yarn from root

backend/native/backend-ws/src/db/nfts.ts, backend/native/backend-ws/src/users/User.ts, backend/native/backpack-api/src/auth/middleware.ts, backend/native/backpack-api/src/db/nft.ts, backend/native/notifications-worker/src/db/chats.ts, backend/native/notifications-worker/src/notifier.ts, packages/app-extension/src/app/Router.tsx, packages/common/src/messages/db.ts, packages/db/src/hooks/contacts.tsx, packages/react-common/src/chat/BackgroundChatsSync.tsx, packages/react-common/src/chat/index.ts
Adds background sync to messages, especially useful when you haven't visited the extension in a while and a bunch of messages have piled up.
v2 should probably be queueing similar to WA
=> Added bg sync

packages/react-common/src/chat/BackgroundChatsSync.tsx
small follow ups on https://github.com/coral-xyz/backpack/pull/2292
=> sync follow up

packages/chat-sdk/src/components/Message.tsx, packages/common/src/messages/fromServer.ts, packages/common/src/messages/index.ts, packages/db/src/api/users.ts, packages/react-common/src/hooks/useChatsWithMetadata.tsx, packages/react-common/src/hooks/useUserMetadata.tsx, packages/recoil/src/atoms/friendship.tsx
Closes https://github.com/coral-xyz/backpack/issues/2282
=> added new theme specific colors

backend/native/backpack-api/src/routes/v1/dropzone.ts, backend/native/zeus/src/zeus/const.ts, backend/native/zeus/src/zeus/index.ts, backend/reef/hasura/metadata/databases/default/tables/dropzone_distributors.yaml, backend/reef/hasura/migrations/default/1674937921205_alter_table_dropzone_distributors_add_column_mint/down.sql, backend/reef/hasura/migrations/default/1674937921205_alter_table_dropzone_distributors_add_column_mint/up.sql
- adds mint field to distributor table
- changes json structure for more efficient storage and lookups
- adds endpoint for fetching all a user's drops
=> dropzone updates

packages/blockchains/common/.eslintrc.js, packages/blockchains/evm/.eslintrc.js, packages/blockchains/keyring/.eslintrc.js, packages/blockchains/solana/.eslintrc.js
Closes https://github.com/coral-xyz/backpack/issues/2205
=> fix packages/blockchains linting config

backend/native/backpack-api/src/db/nft.ts, packages/chat-sdk/src/components/ChatRoom.tsx, packages/chat-sdk/src/components/FullScreenChat.tsx
=> added jump to bottom, unread counts

packages/chat-sdk/src/components/Banner.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/ParsedMessage.tsx, packages/message-sdk/src/components/UserList.tsx
closes #2101 
closes #2303 
closes #2310 
(hard to get screenshot of skeleton before the images load lol)
=> Fix various spacing issues

backend/native/notifications-worker/src/db/notifications.ts, backend/native/notifications-worker/src/processors.ts, packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/Unlocked/Messages/Contacts.tsx, packages/app-extension/src/components/Unlocked/Messages/Requests.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchUsers.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/db/src/db/friends.ts, packages/message-sdk/src/components/UserList.tsx, packages/react-common/src/components/base/DangerButton.tsx, packages/react-common/src/components/base/SuccessButton.tsx, packages/react-common/src/components/base/index.ts, packages/recoil/src/atoms/friendship.tsx, packages/recoil/src/atoms/notifications.ts, packages/themes/src/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/2317
=> moved requests, added request notification

packages/chat-sdk/src/components/FullScreenChat.tsx, packages/chat-sdk/src/components/MediaContent.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/ReplyContainer.tsx, packages/chat-sdk/src/components/SendMessage.tsx
this pr fixes some major UI bugs
- chat overflow
- reply container
- combined messages from single user
=> fixed chat overflow, reply bug, combined messages from single user

packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/app-extension/src/components/Unlocked/Settings/AvatarHeader/UpdateProfilePicture.tsx, packages/chat-sdk/src/components/MediaContent.tsx, packages/chat-sdk/src/components/Message.tsx, packages/message-sdk/src/components/MessageList.tsx, packages/message-sdk/src/components/ProfileScreen.tsx, packages/message-sdk/src/components/styles.tsx, packages/react-common/src/components/Icon/index.tsx
closes #2169 
closes #1931 
closes #2177
=> Various design polish fixes

packages/app-extension/src/app/Router.tsx, packages/background/src/frontend/server-injected.ts, packages/common/src/browser/extension.ts, packages/common/src/constants.ts
Closes https://github.com/coral-xyz/backpack/issues/2244
=> fix wallet connect when locked flows

packages/chat-sdk/src/components/Attatchment.tsx, packages/chat-sdk/src/components/EmojiPicker.tsx, packages/chat-sdk/src/components/FullScreenChat.tsx, packages/chat-sdk/src/components/GifPicker.tsx, packages/chat-sdk/src/components/SecureTransfer.tsx, packages/chat-sdk/src/components/SendMessage.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx, packages/chat-sdk/src/components/messageInput/MessageInputProvider.tsx
=> Update chat sdk message input

packages/app-extension/src/components/Unlocked/Messages/SearchBox.tsx, packages/app-extension/src/components/common/Layout/Nav.tsx, packages/app-extension/src/components/common/Layout/Router.tsx, packages/chat-sdk/src/components/ChatRoom.tsx, packages/chat-sdk/src/components/SendMessage.tsx, packages/message-sdk/src/components/MessageList.tsx, packages/themes/src/index.tsx
=> Various message page design fixes

backend/native/backpack-api/src/db/notifications.ts, backend/native/backpack-api/src/routes/v1/notifications.ts
Related https://github.com/coral-xyz/backpack/pull/2350
=> Expose clear notifications

packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/SendMessage.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx, packages/chat-sdk/src/components/messageInput/MessageInputProvider.tsx
closes https://github.com/coral-xyz/backpack/issues/2344
=> Added arrow keys to navigate tags

backend/native/backpack-api/src/routes/v1/dropzone.ts
splits result from dropzone indexer into array of claimed vs unclaimed drops
=> differentiate claimed vs unclaimed drops

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/Unlocked/Messages/Contacts.tsx, packages/app-extension/src/components/Unlocked/Messages/Requests.tsx, packages/message-sdk/src/components/UserList.tsx, packages/message-sdk/src/components/styles.tsx
=> adjust friend request notifications linking and actions

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx
closes #2377 
uses condition navstack based on breakpoint to allow linking to contacts page in both small and full screen window sizes due to the state of navigation.
the linking into `Contacts` is still done via drawer in full screen because of navigation contextual requirements.
=> update notifications navstack

packages/app-extension/src/app/DbRecoilSync.tsx, packages/db/src/api/RecoilSync.tsx
Closes https://github.com/coral-xyz/backpack/issues/2365
=> Added offline image refresh

backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/routes/v1/users.ts, backend/native/backpack-api/src/validation/publicKey.ts, packages/common/src/index.ts, packages/common/src/messages/toServer.ts, packages/message-sdk/src/components/Inbox.tsx, packages/message-sdk/src/components/UserList.tsx
Search in the searchbar by public key returns the user
Local simulation screenshot
=> Added reverse search by public key

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/WalletDetail.tsx
Fix for https://github.com/coral-xyz/backpack/issues/2380 but untested. Will test in morning if unmerged!
=> fix is cold bug

packages/app-extension/src/components/Unlocked/Apps/index.tsx, packages/react-common/src/components/base/EmptyState.tsx
=> add media query to empty state to determine optional button width constraints

backend/native/backpack-api/src/db/notifications.ts, backend/native/backpack-api/src/routes/v1/notifications.ts, backend/native/zeus/src/zeus/const.ts, backend/native/zeus/src/zeus/index.ts, backend/reef/hasura/metadata/databases/default/tables/auth_notification_cursor.yaml, backend/reef/hasura/metadata/databases/default/tables/auth_notifications.yaml, backend/reef/hasura/metadata/databases/default/tables/tables.yaml, backend/reef/hasura/migrations/default/1675247983228_create_table_auth_notification_cursor/down.sql, backend/reef/hasura/migrations/default/1675247983228_create_table_auth_notification_cursor/up.sql, packages/app-extension/src/app/DbRecoilSync.tsx, packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/common/Layout/Tab.tsx, packages/app-extension/src/components/common/NotificationIconWithBadge.tsx, packages/common/src/notifications.ts, packages/message-sdk/src/components/MessageList.tsx, packages/recoil/src/atoms/index.tsx, packages/recoil/src/atoms/unreadCount.tsx, packages/recoil/src/hooks/index.tsx, packages/recoil/src/hooks/useUnreadCount.tsx
=> Adds notification bubble and notification count 

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/Unlocked/Messages/Contacts.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchUsers.tsx, packages/app-extension/src/components/Unlocked/Settings/SettingsNavStackDrawer.tsx, packages/message-sdk/src/components/ProfileScreen.tsx, packages/message-sdk/src/components/UserList.tsx
=> Separate contacts and requests display pages

packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchBox.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchUsers.tsx, packages/message-sdk/src/components/UserList.tsx
=> Update chat room info menu

packages/app-extension/src/plugin/Renderer.tsx, packages/provider-core/src/root-provider-xnft.ts
please see comment below before merging
=> provide window.xnft.metadata to iframe & native xNFTs

backend/native/backpack-api/src/db/users.ts, packages/app-extension/src/components/Unlocked/Settings/AvatarHeader/UpdateProfilePicture.tsx
=> PFP selection border and revertion cleanup

backend/native/backpack-api/src/routes/v1/dropzone.ts, backend/native/zeus/src/zeus/const.ts, backend/native/zeus/src/zeus/index.ts, backend/reef/hasura/metadata/databases/default/tables/auth_users.yaml
returns usernames of users that were referred by the current jwt user
=> include referred users in dropzone api query

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx
=> fix notification list item icon skeletons

packages/chat-sdk/src/components/FullScreenChat.tsx
closes #2346 
Chose design option 2
=> add dropzone drag popup

packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx
=> hide the back button on the last page of recovery flow

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx
Closes https://github.com/coral-xyz/backpack/issues/2418
=> Updated notification time

packages/chat-sdk/src/components/FullScreenChat.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/ReplyContainer.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx, packages/themes/src/index.tsx
=> styling polish to messages and chat room screen

packages/react-common/src/components/base/LocalImage.tsx
Related to https://github.com/coral-xyz/backpack/issues/2419
=> Fixed image

packages/react-common/src/components/base/LocalImage.tsx
Closes https://github.com/coral-xyz/backpack/issues/2419
=> fixed local image

packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx
=> hide back button on last step of recovery onboarding

backend/native/backpack-api/src/routes/v1/dropzone.ts
skips using jwt to fetch user id during testing
=> dropzone backend tweaks

backend/native/backpack-api/src/db/notifications.ts, packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/chat-sdk/src/components/Message.tsx, packages/message-sdk/src/components/MessageList.tsx, packages/message-sdk/src/components/ProfileScreen.tsx, packages/message-sdk/src/components/UserList.tsx, packages/react-common/src/components/base/LocalImage.tsx
Closes https://github.com/coral-xyz/backpack/issues/2425
Closes https://github.com/coral-xyz/backpack/issues/2424
=> updates to chat

packages/app-extension/src/components/common/PopoverMenu.tsx
=> fix padding border to popover menu

backend/native/xnft-api-server/src/db/index.ts, packages/recoil/src/atoms/preferences/xnft-preferences.tsx
=> allow dropzone push notifications by default

packages/chat-sdk/src/components/FullScreenChat.tsx
=> fix drag drop zone in chat room

packages/chat-sdk/src/components/Message.tsx, packages/message-sdk/src/components/UserList.tsx, packages/message-sdk/src/components/styles.tsx
=> minor design fixes

backend/native/backpack-api/src/config.ts, backend/native/backpack-api/src/routes/v1/dropzone.ts
sends out push notifications to drop recipients in batches of 500, currently an arbitrary size that will be tuned with testing
=> send dropzone push notifications

packages/common/src/solana/programs/xnft.ts
not ready for prod yet, just testing things out
=> add dropzone behind feature flag

packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/2402
=> add loader on create new wallet

packages/app-extension/src/components/common/Layout/Router.tsx
Closes https://github.com/coral-xyz/backpack/issues/2435
=> Fixes navbar

backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/routes/v1/inbox.ts, packages/common/src/messages/db.ts, packages/message-sdk/src/components/Inbox.tsx
Reverse search doesn't work if you search someone who is your friend by public key
=> Fixes reverse address search

packages/react-common/src/components/base/List.tsx
=> Fix exception onclick

packages/chat-sdk/src/components/MediaContent.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx
New pr because the last one had a lot of issues
=> fixes video, mentions

packages/common/src/crypto.ts
Closes https://github.com/coral-xyz/backpack/issues/2476
=> remove sollet recovery paths

packages/app-extension/src/components/common/Account/MnemonicInput.tsx
=> feat: center invalid recovery phrase error

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/WalletDetail.tsx, packages/app-extension/src/components/common/WalletList.tsx, packages/background/src/backend/store/keyname.ts
https://github.com/coral-xyz/backpack/issues/2271
=> dehydrated wallet state design update

packages/app-extension/src/components/Unlocked/Settings/YourAccount/ShowPrivateKey.tsx, packages/app-extension/src/components/Unlocked/Settings/YourAccount/ShowRecoveryPhrase.tsx, packages/app-extension/src/components/common/Layout/NavStack.tsx, packages/app-extension/src/components/common/WaitingRoom.tsx, packages/app-extension/src/components/common/WalletList.tsx
continuing to inch closer to the react-native navigation api
=> use setOptions api for right nav btn

packages/app-extension/src/components/Unlocked/Balances/StripeRamp.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Token.tsx, packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx, packages/app-extension/src/components/Unlocked/Settings/AvatarHeader/AvatarHeader.tsx, packages/app-extension/src/components/common/Layout/NavStack.tsx
=> remove on close api for nav stack

web/.eslintrc.json, web/components/AppNoLink.tsx, web/components/CoralFooter.tsx, web/components/Nav.tsx, web/components/Partners.tsx, web/package.json, yarn.lock
Reverts coral-xyz/backpack#2484
=> Revert "fix lint and build issues for web vercel package"

packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/recoil/package.json, packages/recoil/src/atoms/solana/xnft.tsx, yarn.lock
add app store meta scraping recoil for xnft and move detail page buttons
----
**Update**
- `xNFT` top left title changed to `Application`
=> Update xNFT collectible open experience

backend/native/backpack-api/src/db/friendships.ts, backend/native/backpack-api/src/db/notifications.ts, backend/native/backpack-api/src/routes/v1/friends.ts, backend/native/backpack-api/src/routes/v1/notifications.ts, backend/native/notifications-worker/src/processors.ts, backend/native/notifications-worker/src/worker.ts, backend/native/zeus/src/zeus/const.ts, backend/native/zeus/src/zeus/index.ts, backend/reef/hasura/metadata/databases/default/tables/auth_notifications.yaml, backend/reef/hasura/migrations/default/1675655361236_alter_table_auth_notifications_add_column_viewed/down.sql, backend/reef/hasura/migrations/default/1675655361236_alter_table_auth_notifications_add_column_viewed/up.sql, packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/Unlocked/Messages/MessageOptions.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchUsers.tsx, packages/chat-sdk/src/components/FullScreenChat.tsx, packages/chat-sdk/src/components/MediaContent.tsx, packages/chat-sdk/src/components/ParsedMessage.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx, packages/common/src/api/friendship.ts, packages/common/src/index.ts, packages/common/src/notifications.ts, packages/db/src/api/friendships.ts, packages/db/src/db/friends.ts, packages/message-sdk/src/components/ChatScreen.tsx, packages/message-sdk/src/components/UserList.tsx, packages/recoil/src/atoms/friendship.tsx, packages/recoil/src/atoms/notifications.ts, packages/recoil/src/hooks/index.tsx, packages/recoil/src/hooks/useUpdateFriendship.tsx
Closes https://github.com/coral-xyz/backpack/issues/2461
Closes https://github.com/coral-xyz/backpack/issues/2492
Closes https://github.com/coral-xyz/backpack/issues/2325
Closes https://github.com/coral-xyz/backpack/issues/2322
=> Notification polishes

packages/app-extension/src/components/common/Layout/Router.tsx, packages/chat-sdk/src/components/Message.tsx, packages/themes/src/index.tsx
Closes #2491
Closes https://github.com/coral-xyz/backpack/issues/2487
=> message Polishes 

packages/message-sdk/src/components/MessageList.tsx
Closes https://github.com/coral-xyz/backpack/issues/2472
=> Fixes long message

packages/app-extension/src/components/common/Layout/Router.tsx
`WithMotion` was the root cause of the flash that shows up when you navigate chats in full screen mode.
The PR fixes it by removing motion when in full screen chat mode
=> Fixes full screen chat navigation flash

.github/workflows/docker-health-checks.yml, backend/chat-reef/docker-compose.yml, backend/reef/docker-compose.yml, docker/backend-ws/Dockerfile, docker/backpack-api/Dockerfile, docker/image-proxy/Dockerfile, docker/notifications-worker/Dockerfile, docker/xnft-api-server/Dockerfile, scripts/check-docker-pin.sh
- Does initial pinning of all known docker references
- Adds a script to ensure the Dockerfile examples are pinned
- Adds a CI workflow to ensure the script is run on every commit
=> Add Docker pinning expectations

packages/app-extension/src/components/common/WalletList.tsx
Closes https://github.com/coral-xyz/backpack/issues/2504
=> change header on blockchain selection

packages/common/src/solana/programs/xnft.ts
- uses the /users/me endpoint to get the list of the user's public keys
- determines if the user is in dropzone wallet by checking the wallet's public key against the user's first solana public key
this will change to a designated wallet in future but is a convenient shortcut to get things up and running for now
=> only show dropzone xnft in dropzone wallet

backend/native/xnft-api-server/src/controllers/notifications.ts, packages/app-extension/src/components/Unlocked/Apps/Plugin.tsx, packages/app-extension/src/components/Unlocked/Settings/Xnfts/Detail.tsx, packages/app-extension/src/components/common/Settings/List.tsx, packages/common/src/constants.ts, packages/react-common/src/components/base/List.tsx, packages/recoil/src/atoms/solana/xnft.tsx
`PublicKey.default.toString()` is throwing an error
Also closes https://github.com/coral-xyz/backpack/issues/2509 , adds notification redirects
=> Fixes #2505

packages/chat-sdk/src/components/Message.tsx
=> adjust message avatar padding and row spacing

packages/background/src/backend/core.ts
=> add xnft whitelist check to navigation push background rpc handler

backend/native/backpack-api/src/auth/middleware.ts, backend/native/backpack-api/src/auth/util.ts
Reverts coral-xyz/backpack#2541
=> Revert "remove cookie extension and add missing await"

packages/eslint-config-custom/index.js
will warn if you don't `await` promises
=> add `no-floating-promises` eslint rule

backend/native/backpack-api/src/auth/middleware.ts, backend/native/backpack-api/src/auth/util.ts
Reverts coral-xyz/backpack#2552
=> Revert "remove cookie extensions in backpack-api"

packages/app-extension/src/components/Unlocked/Swap.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/ReplyContainer.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx, packages/message-sdk/src/components/MessageList.tsx
closes #2560 
closes #2561 
closes #2566
=> various polish updates

packages/app-extension/src/components/Unlocked/Swap.tsx, packages/app-extension/src/components/common/Layout/NavStack.tsx
=> add style override to nav setOptions and fix dark mode swap background

packages/app-extension/src/components/Unlocked/Swap.tsx
=> fix token select navbar regression

packages/message-sdk/src/components/Inbox.tsx, packages/message-sdk/src/components/MessageList.tsx
=> fix message inbox bottom padding

backend/native/backend-ws/src/config.ts
=> Added port env variable

packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx
=> fix word break in message sign drawer

packages/app-extension/src/components/Onboarding/pages/NotificationsPermission.tsx
=> update notification onboarding page with new illustration

packages/app-extension/src/components/common/WalletList.tsx
Creates a common wrapper for wallet list buttons and resizes the ... button in the wallet list to 32px wide.
Closes https://github.com/coral-xyz/backpack/issues/2524
=> resize edit wallets button in wallet list

packages/react-common/src/components/Icon/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/2500
=> resize message unread circle

packages/app-extension/src/components/Unlocked/Settings/Preferences/index.tsx, packages/app-extension/src/components/common/Settings/List.tsx
Closes https://github.com/coral-xyz/backpack/issues/2626
=> fix blockchain icon placement

packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx
Related https://github.com/coral-xyz/backpack/issues/2609
=> fix eth only message err

packages/app-extension/src/components/Unlocked/Settings/Xnfts/index.tsx, packages/recoil/src/atoms/solana/xnft.tsx
xnft settings page breaks in eth only mode
=> fixed eth only err

backend/reef/docker-compose.yml, backend/reef/hasura/metadata/databases/databases.yaml
- adds read-replica
- removes logging restrictions in development
- removes metadata database url setting in development
=> add read-replica support to hasura

packages/app-extension/src/components/Unlocked/Nfts/Common.tsx, packages/app-extension/src/components/Unlocked/Nfts/NftTable.tsx
=> Fixed bubbles

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx
Closes https://github.com/coral-xyz/backpack/issues/2565
=> fix title on notifications nav

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
After discussion with design we dont want to have the txn history in messages
=> Removed message

backend/workers/rpc-proxy/.eslintrc.js, backend/workers/rpc-proxy/package.json, backend/workers/rpc-proxy/src/index.ts
also adds eslint config to pass linting check
=> allow content-encoding header in rpc proxy

README.md
=> Fix: anchor links in readme file

packages/app-extension/src/components/Unlocked/WithAuth.tsx, packages/background/src/backend/core.ts, packages/background/src/frontend/server-ui.ts, packages/common/src/constants.ts
Closes https://github.com/coral-xyz/backpack/issues/2573
=> implement mnemonic syncing again

packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx, packages/recoil/src/hooks/useTransactionData.tsx
Closes https://github.com/coral-xyz/backpack/issues/2583
=> remove zero balance changes from simulation results

packages/app-mobile/app.config.js, packages/app-mobile/src/App.tsx, packages/background/src/backend/core.ts
=> fixing mobile cors / server issue

packages/app-mobile/src/components/CheckBox.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/hooks/useTheme.tsx, packages/app-mobile/src/navigation/OnboardingNavigator.tsx
- fix various errors
- fix mnemonic input
=> onboarding fixes

packages/app-extension/src/components/Unlocked/WithAuth.tsx
Closes https://github.com/coral-xyz/backpack/issues/2720
=> fix account switching keyring bug

backend/native/xnft-api-server/src/db/users.ts
Hide non primary pubkeys from xnft-api-server
=> Gaurd public keys from xnft-api-server

packages/common/src/solana/programs/xnft.ts, packages/recoil/src/atoms/solana/xnft.tsx
replaces #2622 
Only shows the dropzone xnft in the user's primary solana wallet
=> only show dropzone xnft in primary wallet

packages/recoil/src/atoms/solana/jupiter.tsx, packages/recoil/src/context/Swap.tsx
Closes https://github.com/coral-xyz/backpack/issues/2731
=> fix bug with swapping and zero balance accounts and switch token bug when one token is sol

packages/app-extension/src/components/Unlocked/PrimaryPubkeySelector.tsx
https://github.com/coral-xyz/backpack/issues/2741
=> Closes #2741

packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
=> Added one remote gating

packages/common/src/feature-gates.ts, packages/recoil/src/atoms/solana/jupiter.tsx, packages/recoil/src/atoms/solana/xnft.tsx, packages/recoil/src/context/Swap.tsx
fixes issue with `SWAP_FEES_ENABLED` feature gate
before when `SWAP_FEES_ENABLED` was being imported it just imported the string `"SWAP_FEES_ENABLED"`
this now checks `featureGates.SWAP_FEES_ENABLED` properly
exporting featureGates `as const` gives it strict accessors for each key
some old unused code for table xnfts was autoremoved too
=> fix feature gate

packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/ListItem.tsx, packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/TransactionDetail.tsx, packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/detail-parser.ts, packages/recoil/src/atoms/solana/jupiter.tsx, packages/recoil/src/hooks/solana/useJupiter.tsx
addresses (by may not close) #2730 #2736
=> use jupiter token list and wsol for tx parse native

backend/chat-reef/hasura/metadata/databases/default/tables/public_barters.yaml, backend/chat-reef/hasura/metadata/databases/default/tables/public_room_active_chat_mapping.yaml, backend/chat-reef/hasura/migrations/default/1676588417663_set_fk_public_room_active_chat_mapping_barter_id/down.sql, backend/chat-reef/hasura/migrations/default/1676588417663_set_fk_public_room_active_chat_mapping_barter_id/up.sql
=> more migrations for bartering

packages/app-extension/src/components/Unlocked/Settings/YourAccount/index.tsx, packages/app-mobile/src/screens/Unlocked/YourAccountScreen.tsx
Closes https://github.com/coral-xyz/backpack/issues/2775
=> logout to log out

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx
Closes https://github.com/coral-xyz/backpack/issues/2738
=> update address selector designs

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx, packages/message-sdk/src/components/Inbox.tsx, packages/message-sdk/src/components/styles.tsx, packages/react-common/src/components/base/BubbleTopLabel.tsx, packages/react-common/src/components/base/index.ts
Closes https://github.com/coral-xyz/backpack/issues/2785
Closes https://github.com/coral-xyz/backpack/issues/2739
Closes https://github.com/coral-xyz/backpack/issues/2787
=> consistent headers and various design tweaks

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchBox.tsx
Closes https://github.com/coral-xyz/backpack/issues/2757
=> consistent placeholders for usernames/addresses

packages/app-extension/src/app/DbRecoilSync.tsx, packages/app-extension/src/app/Router.tsx, packages/app-extension/src/components/Unlocked/AuthenticatedSync.tsx, packages/background/src/backend/core.ts, packages/message-sdk/src/components/Inbox.tsx, packages/recoil/src/atoms/preferences/index.tsx, packages/recoil/src/context/Notifications.tsx
Closes https://github.com/coral-xyz/backpack/issues/2646
Closes https://github.com/coral-xyz/backpack/issues/2645
=> fix chat syncing

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
Closes https://github.com/coral-xyz/backpack/issues/2789
Closes https://github.com/coral-xyz/backpack/issues/2788
=> disable send button on no input or 0 input

packages/app-extension/src/components/Unlocked/Nfts/Common.tsx, packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
Adds launch Icon+ nft name to collection view so xnfts can be launched from a specific nft
=> Pass down mint address to collectible-xnft

packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/ListItem.tsx
=> update: token swap color

backend/native/backpack-api/src/auth/middleware.ts, backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/routes/v1/users.ts
if `alice` refers `bob` to backpack, and `bob` later creates the user `carol`, `carol` should be considered a referral for `alice`
```mermaid
flowchart LR
alice-. referred .->bob== created new account==>carol
alice-. referred .->carol
```
=> keep current user's referrer if they add a new account

packages/chat-sdk/src/components/messageInput/MessageInput.tsx
Closes https://github.com/coral-xyz/backpack/issues/2801
=> decrease font size of message input

packages/chat-sdk/src/components/ParsedMessage.tsx
Closes https://github.com/coral-xyz/backpack/issues/2810
=> fix user tagging breaking chat layout in long messages

packages/message-sdk/src/components/MessageList.tsx
Closes https://github.com/coral-xyz/backpack/issues/2806
=> add ellipsis on message preview

packages/chat-sdk/src/components/messageInput/MessageInput.tsx
Closes https://github.com/coral-xyz/backpack/issues/2809
=> center tag in message popup

packages/app-extension/src/components/Unlocked/Swap.tsx, packages/recoil/src/context/Swap.tsx
Closes https://github.com/coral-xyz/backpack/issues/2821
=> fix preselection of tokens in swapper

backend/native/backpack-api/src/db/users.ts
Closes https://github.com/coral-xyz/backpack/issues/2777
=> add asc order on username in by prefix query

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
Closes https://github.com/coral-xyz/backpack/issues/2773
=> fix width of send loader

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx
Closes https://github.com/coral-xyz/backpack/issues/2803
=> deduplicate friends from search results in send

packages/chat-sdk/src/components/AboveMessagePluginRenderer.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/SecureTransfer.tsx, packages/chat-sdk/src/components/SendMessage.tsx
=> Secure transfer new ui

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
=> update: place token cursor to the left

packages/app-extension/src/plugin/Component.tsx, packages/react-common/src/components/base/Inputs.tsx, packages/react-common/src/components/base/UserIcon.tsx
- fix avatar
- wip text input
- wip
=> extension text field / avatar fixes

packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx, packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/app-extension/src/components/Unlocked/index.tsx, packages/chat-sdk/src/components/ParsedMessage.tsx
Closes https://github.com/coral-xyz/backpack/issues/2874
Closes https://github.com/coral-xyz/backpack/issues/2854
Closes https://github.com/coral-xyz/backpack/issues/2850
Closes https://github.com/coral-xyz/backpack/issues/2836
=> Bunch of polishes

packages/app-extension/src/components/Unlocked/Settings/AvatarHeader/AvatarHeader.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx
=> remove avatar menu in settings

packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx
Closes https://github.com/coral-xyz/backpack/issues/2894
=> Dark mode fix

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx
Closes https://github.com/coral-xyz/backpack/issues/2906
=> fixes username issue

packages/app-extension/src/components/Onboarding/pages/OnboardAccount.tsx, packages/app-extension/src/components/Onboarding/pages/RecoverAccount.tsx, packages/recoil/src/context/OnboardingProvider.tsx, yarn.lock
testing
fixes https://github.com/coral-xyz/backpack/issues/2907
=> fix recover account 2nd username

packages/app-extension/src/components/Unlocked/Messages/SearchUsers.tsx
Closes https://github.com/coral-xyz/backpack/issues/2910
=> Fixed contact naming

packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/WalletDetail.tsx
=> fix: copy tooltip positioning

packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx, packages/app-extension/src/components/Unlocked/Settings/YourAccount/EditWallets/WalletDetail.tsx, packages/app-extension/src/components/common/Layout/BottomCard.tsx, packages/app-extension/src/components/common/Layout/Nav.tsx, packages/app-extension/src/permissions/PermissionsPage.tsx
- eslint fixes useless renders
- fix chat drawer render
=> eslint --fix some leaky renders

packages/app-extension/src/components/Onboarding/pages/NotificationsPermission.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx, packages/app-extension/src/components/Unlocked/Messages/Contacts.tsx, packages/app-extension/src/components/Unlocked/Messages/MessageOptions.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchUsers.tsx, packages/app-extension/src/components/Unlocked/Settings/index.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsList.tsx, packages/chat-sdk/src/components/Banner.tsx, packages/message-sdk/src/components/Inbox.tsx, packages/message-sdk/src/components/ProfileScreen.tsx, packages/message-sdk/src/components/RequestsScreen.tsx
=> change language around contacts to friends

scripts/npm_release.sh
xnft-cli got chopped out of here in https://github.com/coral-xyz/backpack/pull/2867
Also had tabs in it 👹
=> fix npm release script

packages/chat-sdk/src/components/ParsedMessage.tsx, packages/themes/src/index.tsx
Closes https://github.com/coral-xyz/backpack/issues/2941
...to be continued
=> Fixed link color

packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx
Closes https://github.com/coral-xyz/backpack/issues/2852
=> Update more members

packages/app-extension/src/components/Locked/index.tsx, packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/app-extension/src/components/Unlocked/Settings/AvatarHeader/UpdateProfilePicture.tsx, packages/db/src/api/LocalImageManager.ts, packages/db/src/api/RecoilSync.tsx, packages/db/src/api/index.ts, packages/react-common/src/components/base/LocalImage.tsx
Closes https://github.com/coral-xyz/backpack/issues/2817
Closes https://github.com/coral-xyz/backpack/issues/2815
=> Fixed username loading

backend/native/backend-ws/src/index.ts, backend/native/backpack-api/src/index.ts
=> Fixes healthchecks

packages/app-extension/src/app/Router.tsx, packages/app-extension/src/components/Unlocked/Approvals/ApproveMessage.tsx, packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx, packages/app-extension/src/components/Unlocked/ApproveTransactionRequest.tsx
Can't query the wallet states until we unlock.
Closes https://github.com/coral-xyz/backpack/issues/2975
=> fix approve transaction crash on locked wallet

backend/chat-reef/hasura/metadata/databases/default/tables/public_chats.yaml, backend/chat-reef/hasura/metadata/databases/default/tables/public_nft_sticker_metadata.yaml, backend/chat-reef/hasura/metadata/databases/default/tables/tables.yaml, backend/chat-reef/hasura/migrations/default/1677442588772_create_table_public_nft_sticker_metadata/down.sql, backend/chat-reef/hasura/migrations/default/1677442588772_create_table_public_nft_sticker_metadata/up.sql, backend/chat-reef/hasura/migrations/default/1677442650059_set_fk_public_nft_sticker_metadata_chat_client_generated_uuid/down.sql, backend/chat-reef/hasura/migrations/default/1677442650059_set_fk_public_nft_sticker_metadata_chat_client_generated_uuid/up.sql, backend/native/chat-zeus/src/zeus/const.ts, backend/native/chat-zeus/src/zeus/index.ts
- Added db changes for stickers
- Updated zeus
=> Updates db for stickers

packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/index.tsx
=> add skeleton style to new wallet connect drawer

backend/native/backend-common/src/db/chats.ts, backend/native/backpack-api/src/db/chats.ts, backend/native/backpack-api/src/routes/v1/nft.ts, backend/native/backpack-api/src/utils/metaplex.ts, packages/chat-sdk/src/MessagePluginRenderer.tsx, packages/chat-sdk/src/components/AboveMessagePluginRenderer.tsx, packages/chat-sdk/src/components/ChatContext.tsx, packages/chat-sdk/src/components/ChatRoom.tsx, packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/NftSticker.tsx, packages/chat-sdk/src/components/NftStickerRender.tsx, packages/chat-sdk/src/components/SendMessage.tsx, packages/chat-sdk/src/components/barter/SelectPage.tsx, packages/chat-sdk/src/components/barter/SwapPage.tsx, packages/chat-sdk/src/components/plugins/NftStickerPlugin.tsx, packages/chat-sdk/src/utils/constants.ts, packages/common/src/messages/toServer.ts, packages/db/src/api/RecoilSync.tsx
=> Adds nft stickers

backend/workers/invites/.eslintrc.js, backend/workers/invites/src/index.ts
=> fix invites gql mutation

packages/app-extension/src/components/Unlocked/Balances/TransferWidget.tsx
This reverts commit 9fa0c8d594d61e3fa696114ec4b788401add0ddb.
it created a regression in the swapper where it wasn't possible to change tokens
=> Revert "async jupiter follow-up (#3040)"

backend/reef/hasura/migrations/default/1677623768540_alter_table_auth_twitter_users_drop_constraint_twitter_users_twitter_id_key/down.sql, backend/reef/hasura/migrations/default/1677623768540_alter_table_auth_twitter_users_drop_constraint_twitter_users_twitter_id_key/up.sql, backend/reef/hasura/migrations/default/1677623775206_alter_table_auth_twitter_users_drop_constraint_twitter_users_twitter_username_key/down.sql, backend/reef/hasura/migrations/default/1677623775206_alter_table_auth_twitter_users_drop_constraint_twitter_users_twitter_username_key/up.sql, backend/reef/hasura/migrations/default/1677623781396_drop_index_twitter_users_twitter_id_key/down.sql, backend/reef/hasura/migrations/default/1677623781396_drop_index_twitter_users_twitter_id_key/up.sql, backend/reef/hasura/migrations/default/1677623781397_drop_index_twitter_users_twitter_username_key/down.sql, backend/reef/hasura/migrations/default/1677623781397_drop_index_twitter_users_twitter_username_key/up.sql
Reverts coral-xyz/backpack#3056
=> Revert "Remove twitter_user restrictions"

packages/chat-sdk/src/components/messageInput/MessageInput.tsx
Yooo new heree, I am a Open source dev. Created web3 gh account for now. 
**Changes**
1. Autofocus the message input, added the flag to prevent autofocus in case its needed
2. Fixed lint issues & minor refactor
Fixes: #3032
=> autofocus message input

backend/chat-reef/hasura/metadata/databases/default/tables/public_chats.yaml, backend/chat-reef/hasura/migrations/default/1677706678436_alter_table_public_chats_add_column_deleted/down.sql, backend/chat-reef/hasura/migrations/default/1677706678436_alter_table_public_chats_add_column_deleted/up.sql, backend/native/backend-common/src/db/chats.ts, backend/native/backend-ws/src/subscriptions/RedisSubscriptionManager.ts, backend/native/backend-ws/src/users/User.ts, backend/native/backpack-api/src/db/chats.ts, backend/native/backpack-api/src/routes/v1/chats.ts, backend/native/chat-zeus/src/zeus/const.ts, backend/native/chat-zeus/src/zeus/index.ts, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchUsers.tsx, packages/chat-sdk/src/components/Message.tsx, packages/common/src/messages/ToPubsub.ts, packages/common/src/messages/fromServer.ts, packages/common/src/messages/toServer.ts, packages/db/src/db/chats.ts, packages/db/src/db/exports.ts, packages/react-common/src/chat/Signaling.ts, packages/react-common/src/chat/SignalingManager.ts
Closes https://github.com/coral-xyz/backpack/issues/3022
Closes https://github.com/coral-xyz/backpack/issues/2804
Closes https://github.com/coral-xyz/backpack/issues/2786
=> some fixes, delete messages

packages/app-extension/src/components/Unlocked/Nfts/Common.tsx, packages/app-extension/src/components/Unlocked/Nfts/NftTable.tsx, packages/recoil/src/atoms/solana/nft.tsx
=> strip null bytes from nft account data name

packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/react-common/src/components/base/PrimaryButton.tsx
=> fix primary button invertion

packages/chat-sdk/src/components/messageInput/MessageInput.tsx
new day new PR 
GM GM!
Closes #2968
https://user-images.githubusercontent.com/126689039/222417249-a38521a4-c6b9-4669-8d53-669926061862.mov
=> fix(chat): dont show popover when no mentions present

packages/chat-sdk/src/components/ChatRoom.tsx
Fixes #2972 
https://user-images.githubusercontent.com/126689039/222422050-8cdf964e-6c40-42bd-b4ce-50f254d53148.mov
=> fix(chat): scroll to bottom when sending message

packages/app-extension/src/components/Unlocked/Swap.tsx, packages/recoil/src/context/Swap.tsx
Without fees | With fees
-------------|-----------
=> update swap ui to handle fees when they're enabled

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
=> update token input field to allow . -> 0. convertion

packages/recoil/src/hooks/solana/usePlugins.tsx
https://github.com/coral-xyz/backpack/issues/2866
=> Fix Simulator xNFT transaction popover

packages/app-extension/src/components/common/Layout/Router.tsx, packages/chat-sdk/src/components/Message.tsx, packages/db/src/db/index.ts, packages/message-sdk/src/components/MessageList.tsx, packages/message-sdk/src/components/UserList.tsx, packages/react-common/src/components/base/BackpackStaffIcon.tsx, packages/react-common/src/components/base/index.ts
Closes https://github.com/coral-xyz/backpack/issues/3035
=> Fixes design of verified icons backpack

backend/workers/feature-gates/src/FEATURES.ts, packages/common/src/feature-gates.ts, packages/recoil/src/atoms/solana/xnft.tsx
splits `SWAP_FEES_ENABLED` into `SWAP_FEES_ENABLED` AND `DROPZONE_ENABLED`
=> add dropzone remote feature gate

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx, packages/app-extension/src/components/Unlocked/Messages/SearchBox.tsx, packages/message-sdk/src/components/Inbox.tsx
Closes https://github.com/coral-xyz/backpack/issues/2693
Closes https://github.com/coral-xyz/backpack/issues/2692
=> Fixed double notifications

packages/app-extension/src/components/Onboarding/pages/RecoverAccountUsernameForm.tsx
Closes https://github.com/coral-xyz/backpack/issues/3115
=> disable recover username button if no username

packages/chat-sdk/src/components/FullScreenChat.tsx, packages/chat-sdk/src/components/ScrollbarImpl.tsx, packages/chat-sdk/src/components/SendMessage.tsx
=> translate messages up when plugin menu is open

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
Issue: clicking on profile pic or name from send SOL screen should take me to the user profile #3119 
Solution: Added an onClick function to the profile pic and username div, which navigates to the user profile.
https://user-images.githubusercontent.com/82360525/222733952-9bfaa1d8-eb6c-4c06-b2c3-031eb49b5196.mp4
=> On click profile pic or name from send SOL screen navigate to user profile page

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx
This reverts commit c2a5cabe2777d981ff5027f3387c0bdc8c98e27e.
=> Reverts profile click

backend/native/backpack-api/src/routes/v1/users.ts, backend/native/backpack-api/src/validation/publicKey.ts, backend/workers/auth/src/onramp/index.ts, backend/workers/auth/src/onramp/validate/index.ts
fixed typo errors from UpdatePulicKey to UpdatePublicKey in 4 places
=> fixed typo from UpdatePulicKey to UpdatePublicKey

packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/Icons.tsx, packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/ListItem.tsx
addresses (by may not close) #2811
=> remove space between swap amount and sign to prevent wrapping

packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx, packages/app-extension/src/components/common/Settings/List.tsx, packages/app-extension/src/components/common/TransactionData.tsx
=> add max height and scroll overflow to tx data

packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/ListItem.tsx, packages/common/src/utils.ts
=> custom sol amount reverse for scientific notation

packages/db/src/api/LocalImageManager.ts, packages/db/src/api/RecoilSync.tsx, packages/db/src/db/exports.ts, packages/db/src/db/images.ts, packages/db/src/db/index.ts, packages/react-common/src/components/base/LocalImage.tsx
Closes https://github.com/coral-xyz/backpack/issues/3134
=> Moves offline image storage to indexedDB

.github/workflows/backend-xnft-api-server.yml, backend/native/xnft-api-server/src/v1/users.ts, docker/xnft-api-server/docker-compose.yml
This reverts commit ca3c37ae2044f95e6d38aeb88001035afca074dc.
=> Revert "Fix routes (#3170)"

packages/chat-sdk/src/components/Message.tsx, packages/chat-sdk/src/components/messageInput/MessageInput.tsx
=> fix: reuse the chat message id

backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/routes/v1/users.ts
Closes https://github.com/coral-xyz/backpack/issues/3016
=> Fix metadata not loading in chat

packages/app-extension/src/components/common/Account/ImportWallets.tsx
fixes #2699
https://user-images.githubusercontent.com/101902546/223212611-0e8bea29-c002-4dd7-a745-9b88fba50292.mov
=> make import wallet selector scrollable

packages/app-mobile/src/navigation/OnboardingNavigator.tsx, packages/eslint-config-custom/native.js, packages/eslint-config-custom/shared/backpack.js
- recover account fixes
- adds eslint
=> onboarding recover flow stuff

packages/app-extension/src/components/Unlocked/Settings/AvatarPopover.tsx, packages/app-extension/src/components/Unlocked/Settings/Preferences/Solana/ConnectionSwitch.tsx
=> fix: settings close button not working after rpc change

packages/app-extension/src/components/Unlocked/Balances/Balances.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Token.tsx, packages/app-extension/src/components/common/TokenTable.tsx, packages/common/src/utils.ts, packages/recoil/src/atoms/ethereum/token.tsx, packages/recoil/src/atoms/prices.tsx, packages/recoil/src/atoms/solana/token.tsx
=> adjust calculation and rendering of usd and percentage of change

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx, packages/react-common/src/components/base/SearchBox.tsx
=> fix size of wallet select input in send

packages/app-extension/src/components/common/Layout/Tab.tsx
=> adjust sizing for unread vs read message bubble icon

backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/routes/v1/nft.ts, backend/native/backpack-api/src/routes/v1/users.ts
Closes https://github.com/coral-xyz/backpack/issues/2840
=> restrict api query user by public key to primary only

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/message-sdk/src/components/ProfileScreen.tsx
addresses (but may not close) #2507
=> adjust notifications loader

backend/native/zeus/package.json, packages/common/package.json, packages/themes/package.json, yarn.lock
I'm going to be opening mini maintenance PRs in an effort towards making the repo code more robust and easier to switch to faster build systems in future if we wanted to.
This PR adds some missing packages and removes tsc
=> package maintenance

backend/native/backend-common/src/db/enrichMessages.ts
Closes: Change "delete" to "remove" in removed message (shows up instead of the message being replied to) #3149
=> Changed "deleted" with "removed" in the reply to the removed message.

packages/app-extension/src/components/common/TokenTable.tsx
Maybe related to #2695
Before: 
https://user-images.githubusercontent.com/82360525/223791619-0da29553-4991-4b1d-876c-605546823a36.mp4
After: 
https://user-images.githubusercontent.com/82360525/223791681-63a7d6c5-65cb-4c68-af6a-722a70192d36.mp4
=> Fixed wallet token table height

backend/native/notifications-worker/src/processors.ts
This has been moved to the backpack-api
=> Remove DB entry for friend request accepts

packages/chat-sdk/src/components/Message.tsx
=> fix replying to deleted messages

packages/app-extension/src/components/Unlocked/Settings/AddConnectWallet/CreateMenu.tsx
Closes https://github.com/coral-xyz/backpack/issues/3255
=> FIx primary key bug

packages/app-extension/src/app/App.tsx
=> add ascii logo and warning to console on load

packages/recoil/src/atoms/solana/nft.tsx
=> fix null bytes in solana nfts being displayed

packages/common/src/browser/extension.ts
fixes #3276
This reverts commit e0c66c0050001cec1d86c2f5924c9d04238ac39e.
=> Revert "fix popout size in windows (#3249)"

packages/common/src/browser/extension.ts
reimplements correct popout size in windows changes (#3249) with fix for #3276 included
=> reimplement #3249

packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx, packages/recoil/src/hooks/useTransactionData.tsx
addresses (but does not fully close) #976 
Adds an aggregation view for all transactions being approved at once
=> multiple transaction approval aggregation

packages/app-extension/src/components/Unlocked/Approvals/ApproveTransaction.tsx
=> add advanced view option for multiple tx approvals

packages/app-extension/src/components/Unlocked/Swap.tsx, packages/common/src/constants.ts, packages/common/src/solana/index.ts, packages/recoil/src/context/Swap.tsx
fixes #3089
adds a popover with a breakdown of the fees
=> include fee if creating a token account during swap

packages/recoil/src/atoms/solana/token.tsx
=> fix incorrect decimals for some tokens

packages/app-extension/src/app/Router.tsx, packages/app-extension/src/spotlight/ActionRow.tsx, packages/app-extension/src/spotlight/FriendCard.tsx, packages/app-extension/src/spotlight/GroupIdentifier.tsx, packages/app-extension/src/spotlight/Line.tsx, packages/app-extension/src/spotlight/SearchBar.tsx, packages/app-extension/src/spotlight/SearchBody.tsx, packages/app-extension/src/spotlight/Spotlight.tsx, packages/app-extension/src/spotlight/SpotlightContacts.tsx, packages/app-extension/src/spotlight/SpotlightGroups.tsx, packages/app-extension/src/spotlight/SpotlightNfts.tsx, packages/app-extension/src/spotlight/SpotlightTokens.tsx, packages/app-extension/src/spotlight/colors.ts, packages/app-extension/src/spotlight/styles.ts, packages/app-extension/src/spotlight/useSearchedContacts.tsx, packages/app-extension/src/spotlight/useSearchedGroups.tsx, packages/app-extension/src/spotlight/useSearchedNfts.tsx, packages/app-extension/src/spotlight/useSearchedTokens.tsx, packages/app-extension/src/spotlight/utils.ts
Closes https://github.com/coral-xyz/backpack/issues/3256
https://user-images.githubusercontent.com/8079861/224459425-9ac5eb23-109d-4df3-b41d-580206cf26d0.mov
=> Add spotlight search

.github/workflows/notifications-worker.yml, docker/notifications-worker/docker-compose.yml
- newrelic on notifications worker
- Updated tag
=> Adds newrelic to notification worker

packages/app-extension/src/components/Onboarding/pages/Finish.tsx, packages/app-extension/src/components/Onboarding/pages/NotificationsPermission.tsx
Closes https://github.com/coral-xyz/backpack/issues/3317
=> Fixes Notification subscriptiobn

.npmrc, backend/native/backend-common/package.json, package.json, packages/app-extension/package.json, packages/background/package.json, packages/blockchains/keyring/package.json, packages/common/package.json, packages/ledger-injection/package.json, packages/tamagui-core/package.json, web/components/Nav.tsx, web/components/PlaceholderApps.tsx, web/components/Posts.tsx, web/components/SecondaryCta.tsx, yarn.lock
adds some missing packages
adds some missing peer dependencies
removes unused packages
fixes and ignores some eslint-disable max-len warnings (with intention to come back to them!)
=> npm packages cleanup

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Ethereum/index.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx, packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Solana/index.tsx, packages/recoil/src/hooks/navigation.tsx
=> fix view balances button on send confirmation card

packages/background/src/backend/keyring/index.ts, packages/blockchains/keyring/src/blockchain.ts
Closes https://github.com/coral-xyz/backpack/issues/3331
=> fix setting active blockchain for new user keyrings

packages/app-extension/src/components/Locked/Reset/ResetWarning.tsx, packages/background/src/backend/core.ts
=> fix logout drawer not closing properly

packages/app-extension/src/components/Unlocked/Nfts/Cards.tsx, packages/provider-core/src/provider-ethereum-xnft.ts, packages/provider-core/src/provider-solana-xnft.ts, packages/provider-core/src/root-provider-xnft.ts
- brings back missing `window.xnft.pubkeys` #3329
- styling fixes: #3262 & #3261
=> Collectibles & xnft fixes

backend/native/backend-common/package.json, examples/clients/simple/package.json, packages/blockchains/keyring/package.json, packages/common/package.json, packages/common/src/solana/background-connection.ts, packages/ledger-injection/package.json, packages/provider-core/package.json, yarn.lock
explicitly adds missing packages that are pulled from the shared node_modules directory
removes dependencies that aren't used
=> add some missing deps + remove unused

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/Send.tsx, packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx
=> Fixed nft sends

packages/app-extension/src/components/common/PopoverMenu.tsx
=> fix: corner borders in nft menu

packages/chat-sdk/src/components/Message.tsx
=> fix: change margin top 16px -> 8px

packages/app-extension/src/components/Unlocked/Messages/ChatDrawer.tsx, packages/app-extension/src/components/common/Layout/Nav.tsx, packages/app-extension/src/components/common/Layout/Router.tsx, packages/message-sdk/src/components/MessageList.tsx
=> add groupchat images to page header and drawer

backend/reef/hasura/metadata/databases/databases.yaml, backend/reef/hasura/metadata/databases/default/tables/auth_users.yaml, backend/reef/hasura/migrations/default/1678913017499_drop_func/down.sql, backend/reef/hasura/migrations/default/1678913017499_drop_func/up.sql
removes function to calculate dropzone wallet as it's now using the primary one
=> hasura sql cleanup

packages/db/src/api/LocalImageManager.ts, packages/react-common/src/components/base/ProxyImage.tsx
- Fixed metadata
- added laziness
=> Optimise images

backend/native/backend-ws/package.json, backend/native/backend-ws/src/db/users.ts, backend/native/backend-ws/tsconfig.json, backend/native/backpack-api/src/db/users.ts, backend/native/notifications-worker/src/db/collection_messages.ts
to make it easier to identify the source of queries when debugging
also fixes some eslint config
=> add operationName to some zeus queries

packages/app-mobile/app.config.js, packages/app-mobile/eas.json, packages/app-mobile/package.json, packages/app-mobile/src/App.tsx, packages/app-mobile/src/components/BottomDrawerEthereumConfirmation.tsx, packages/app-mobile/src/components/CheckBox.tsx, packages/app-mobile/src/components/Icon.tsx, packages/app-mobile/src/components/NavHeader.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx, packages/app-mobile/src/navigation/OnboardingNavigator.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/screens/Unlocked/BalancesScreen.tsx, packages/app-mobile/src/screens/Unlocked/NftCollectiblesScreen.tsx, packages/app-mobile/src/screens/Unlocked/WalletListScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/Balances.tsx, packages/recoil/package.json, packages/recoil/src/context/OnboardingProvider.tsx, packages/tamagui-core/src/components/Images.tsx, packages/tamagui-core/src/components/index.tsx, yarn.lock
- updates
- make changes to onboarding
- set to light
=> appstore changes

backend/native/backpack-api/src/db/publicKey.ts, backend/native/backpack-api/src/db/users.ts, backend/native/backpack-api/src/routes/v1/users.ts, packages/background/src/backend/core.ts
Related to https://github.com/coral-xyz/backpack/issues/3390
=> Return primary key from server

packages/background/src/backend/keyring/index.ts, packages/background/src/frontend/server-ui.ts
Closes https://github.com/coral-xyz/backpack/issues/3400
Closes https://github.com/coral-xyz/backpack/issues/3405
=> fix init bug

packages/app-extension/src/components/Unlocked/Balances/Notifications.tsx, packages/react-common/src/components/base/ProxyImage.tsx
=> Fix notifications

packages/app-mobile/src/components/BottomDrawerCards.tsx, packages/app-mobile/src/components/BottomDrawerSolanaConfirmation.tsx, packages/app-mobile/src/components/UserAccountsMenu.tsx, packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/screens/Unlocked/RecentActivityScreen.tsx, packages/app-mobile/src/screens/Unlocked/SendTokenScreen.tsx, packages/app-mobile/src/screens/Unlocked/SendTokenScreen2.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsList.tsx, packages/app-mobile/src/screens/Unlocked/WalletListScreen.tsx, packages/tamagui-core/src/components/index.tsx
- adds dehydratedWallets
- fix recent transactions
- wip
=> wip wip mobiles

backend/native/xnft-api-server/src/db/users.ts
should speed up getUserIdFromPubkey quite significantly
related #3420
=> simplify getUserIdFromPubkey

packages/db/src/api/friendships.ts, packages/tamagui-core/src/chat/AuthenticatedSync.tsx, packages/tamagui-core/src/chat/fetchMoreChatsFor.tsx, packages/tamagui-core/src/chat/getAuthHeader.ts, packages/tamagui-core/src/chat/refreshChatsFor.tsx, packages/tamagui-core/src/chat/refreshGroupsAndFriendships.tsx, packages/tamagui-core/src/chat/refreshIndividualChatsFor.tsx, packages/tamagui-core/src/chat/refreshUpdatesFor.tsx
Needed on mobile since mobile doens't use cookies
=> Adds jwt header to chat requests

packages/app-extension/src/components/common/Account/PrivateKeyInput.tsx
=> update error responses for conflicts during private key imports

packages/app-extension/src/components/Unlocked/Settings/AvatarPopover.tsx
=> Fixed zIndex of popover to solve overlapping issue #3473

packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/TransactionDetail.tsx
fixes #3460 
apply text-transform to capitalize the word
changes according to style pattern
=> add textTransform to label

packages/message-sdk/src/components/MessageList.tsx, packages/xnft-cli/package.json, yarn.lock
=> update message list to sort by most recent

packages/chat-sdk/src/components/FullScreenChat.tsx
closes #3435 
https://user-images.githubusercontent.com/79896602/226954583-39dbc0d7-fa2d-4489-b112-207c3ad1937f.mp4
=> only accept video/image file type in chat file upload

packages/background/src/frontend/server-injected.ts
=> Fix typo in server-injected.ts

web/components/Partners.tsx
=> fix anagram website and hover state on website

.github/workflows/pull_requests_and_merges.yml, package.json
- adds provider-injection to yarn:ext
- updates yarn build to yarn build:ext so it doesn't build _everything_
=> add provider-injection to build:ext

packages/app-extension/webpack.config.js
- https://webpack.js.org/plugins/terser-webpack-plugin/#swc
randomly came to mind. copied. pasted. testing.
locally, build times are over 2x as fast
=> 2x faster build times

backend/native/backpack-api/src/routes/v1/mobile.ts
fixes mimetype for backpack-api
=> fix mimetype

packages/app-extension/src/components/Unlocked/Nfts/Cards.tsx, packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/app-extension/src/components/Unlocked/Nfts/SendDrawer.tsx, packages/app-extension/src/components/common/Layout/RightClickMenu.tsx
- Show "Open xNFT" on Hover
- introduce right click menu
#3525
=> Update Collectibles View 

packages/app-extension/src/components/Unlocked/Nfts/Cards.tsx
=> Fix NFT name click

packages/background/src/index.ts, packages/background/src/service-worker.ts
=> investigate service worker

packages/app-extension/src/components/Unlocked/Nfts/Cards.tsx
Issue id : [3549](https://github.com/coral-xyz/backpack/issues/3549)
=> Increase padding-left and padding-right to 8px around xNFT button #3549

packages/app-extension/src/components/common/Account/PrivateKeyInput.tsx
Closes https://github.com/coral-xyz/backpack/issues/3562.
=> remove unexpected error to fix recovery

packages/app-extension/src/components/Unlocked/Nfts/Detail.tsx, packages/react-common/src/components/base/ProxyImage.tsx
=> Original Asset in Details view

packages/app-mobile/package.json, packages/app-mobile/src/screens/Unlocked/Chat/ChatDetailScreen.tsx, packages/app-mobile/src/screens/Unlocked/Chat/ChatRequestScreen.tsx, yarn.lock
- hook up chat request detail page
- message extras
=> more mobile chat additions

packages/app-mobile/src/screens/Unlocked/Chat/ChatDetailScreen.tsx, packages/app-mobile/src/screens/Unlocked/Chat/ChatHelpers.ts, packages/tamagui-core/src/chat/fetchMoreChatsFor.tsx
Related https://github.com/coral-xyz/backpack/issues/3575
=> Mobile chat fixes

packages/app-mobile/src/screens/Unlocked/Chat/ChatDetailScreen.tsx, packages/db/src/api/LocalImageManager.native.ts
Fixes sends, document not found error
Related https://github.com/coral-xyz/backpack/issues/3575
=> Mobile messaging

packages/app-extension/src/components/Unlocked/Balances/TokensWidget/AddressSelector.tsx
closes https://github.com/coral-xyz/backpack/issues/3612
=> Alphabetical sorted list of friends on send token screen

packages/app-extension/src/components/Unlocked/Apps/index.tsx
=> add xnft library link button to apps page

packages/db/src/api/friendships.ts, packages/db/src/db/chats.ts
Closes https://github.com/coral-xyz/backpack/issues/3633
=> Fixes Backpack all chat does not load on the user's first session.

packages/app-extension/src/components/Unlocked/Settings/Preferences/Solana/Explorer.tsx, packages/common/src/explorer.ts, packages/common/src/solana/explorer.ts
- added [XRAY explorer](https://xray.helius.xyz/) 
- replaced the empty fragments with div to make eslint happy, in [this file](https://github.com/jim4067/backpack/blob/b6dc1430763451ed6cd799fcc14838bfeebafb11/packages/app-extension/src/components/Unlocked/Settings/Preferences/Solana/Explorer.tsx).
=> feat: add xray explorer

packages/app-extension/src/components/Unlocked/Settings/Xnfts/Detail.tsx, packages/common/src/solana/programs/xnft.ts, packages/recoil/src/atoms/solana/xnft.tsx
=> clean up baked in xnft logic into common package, and remove uninstall for them

packages/recoil/src/context/WithAuth.tsx, packages/recoil/src/context/index.tsx
Reverts coral-xyz/backpack#3683
=> Revert "remove unused WithAuth duplicate"

backend/native/backpack-api/src/utils/metaplex.ts
Added ownership check back to nft collection PUT endpoint
=> Added back ownership check

backend/workers/ethereum-rpc-proxy/.eslintrc.js, backend/workers/ethereum-rpc-proxy/src/index.ts, packages/app-extension/src/components/Unlocked/Apps/index.tsx, packages/common/src/constants.ts
=> relocate alchemy api key into obfuscated environment

.github/workflows/backpack-ws.yml
=> Updated ws to new env

backend/workers/rpc-proxy/package.json, backend/workers/rpc-proxy/src/index.ts, backend/workers/rpc-proxy/wrangler.toml, yarn.lock
fixes #1514
if the initial solana RPC request fails for any reason this will try again with a different endpoint
=> add fallback option to rpc proxy

backend/reef/docker-compose.yml, backend/reef/hasura/metadata/databases/databases.yaml
=> add support for multiple read replicas

backend/native/backend-ws/src/users/User.ts
Reverts coral-xyz/backpack#3748
=> Revert "stop all chat for now"

backend/native/backend-ws/src/users/User.ts
Reverts coral-xyz/backpack#3749
=> Revert "Revert "stop all chat for now""

backend/native/backpack-api/src/utils/metaplex.ts
Reverts coral-xyz/backpack#3706
=> Revert "Added back ownership check"

packages/app-mobile/src/hooks/useLoadedAssets.tsx, packages/tamagui-core/src/components/ListItem2.tsx, packages/tamagui-core/src/fonts.ts, packages/tamagui-core/src/tamagui.config.ts, packages/themes/src/base.ts
- tamagui config updates
- clean up tamagui font stuff and separate it
=> tamagui font updates

backend/workers/feature-gates/src/FEATURES.ts
=> Enabled stickers

packages/app-extension/src/components/Locked/index.tsx
Before: 
https://user-images.githubusercontent.com/82360525/234929482-9fabf160-6e5c-490c-90c2-c59213a67230.mp4
After: 
https://user-images.githubusercontent.com/82360525/234929580-35f3e462-99cf-4496-b0b6-4835e8256a3c.mp4
=> when password changed, Update password input error state

packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/TransactionDetail.tsx
=> lazily fetch nft image and name for tx viewing

packages/app-extension/src/components/Unlocked/Balances/RecentSolanaActivity/TransactionDetail.tsx, packages/themes/src/colors.ts
=> fix table border style for dark mode

backend/native/backpack-api/src/routes/graphql/blockchain/solana.ts, backend/native/backpack-api/src/schema.graphql
- adds transaction.description
- fixes coingecko spl token response
=> adds description to transactions & fixes spl token node

packages/chat-sdk/src/components/barter/SelectPage.tsx
=> fixed sticker skeleton squishing

packages/chat-sdk/src/components/NftStickerRender.tsx, packages/chat-sdk/src/components/barter/SelectPage.tsx, packages/chat-sdk/src/components/barter/SwapPage.tsx
Closes https://github.com/coral-xyz/backpack/issues/3873
Closes https://github.com/coral-xyz/backpack/issues/3817
=> Sticker polishes

packages/common/src/browser/extension.ts, packages/common/src/constants.ts, packages/common/src/plugin.ts, packages/provider-core/src/root-provider-xnft.ts
Fixes https://github.com/coral-xyz/backpack/issues/1357
Works with both the extension window and when it's popped out. Please check the video for reference:
https://user-images.githubusercontent.com/90475821/235223921-700c127a-3428-4aa4-b948-da06cab65de2.mov
@callensm , you asked me to tag you for awareness. Thanks!
=> Resize Extension

packages/app-mobile/src/components/ListItem.tsx, packages/app-mobile/src/screens/Unlocked/DummyScreen.tsx
=> adds activity detail list item breakdown

backend/native/backpack-api/package.json, backend/native/backpack-api/src/index.ts, backend/native/backpack-api/src/routes/graphql/context.ts, backend/native/backpack-api/src/routes/graphql/index.ts, backend/native/backpack-api/src/routes/graphql/rules.ts, backend/native/backpack-api/src/routes/graphql/types.ts, backend/native/backpack-api/src/schema.graphql, yarn.lock
=> gql: server-side response cache and cache control setup

web/pages/about.tsx, web/pages/index.tsx
attempting to fix build issues with vercel
replaces `dynamic()` with `React.lazy()` to see if that helps https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading
=> use React.lazy in web

packages/common/src/constants.ts
Adds https://solscan.io/token/4wUE3tH2MTjNnxKQPYyx3owgL95ZYbYAtW1EsQPz9hfV
=> Added new collection

packages/app-extension/src/components/Unlocked/Settings/Xnfts/Detail.tsx
=> add xnft cached version to settings view of app

packages/app-mobile/src/components/DEPRECATED__WalletSectionList.tsx, packages/app-mobile/src/screens/HomeWalletListScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/ProfileScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/BalanceSummaryWidget.tsx
- more
- fxies
- fix wallet list screen
=> profile updates etc

backend/workers/feature-gates/package.json, backend/workers/feature-gates/src/FEATURES.ts, backend/workers/feature-gates/src/index.ts, backend/workers/feature-gates/wrangler.toml, yarn.lock
testing out a quick short-term solution for setting feature gates for specific user ids
=> conditionally toggle feature gates for user ids

packages/provider-core/src/provider-solana.ts
Prevents error to show up in console about unknown event names
=> Plugin event name fix

backend/workers/jupiter-proxy/src/feeAccounts.json, backend/workers/jupiter-proxy/src/index.ts
updates feeaccounts & harden proxy rules, supabase will be removed in a follow up pr
=> jupiter proxy updates

packages/app-extension/src/components/Unlocked/Settings/YourAccount/ChangePassword.tsx
closes #3834 
https://user-images.githubusercontent.com/79896602/235214434-943e46a7-cf28-40b1-aee3-87d7a398fa46.mp4
=> add a minimum password length validation

web/pages/downloads.tsx
=> mobile collapse for web download links

packages/common/src/constants.ts
=> Added new collections

packages/app-extension/package.json, packages/app-extension/webpack.config.js, yarn.lock
=> hide ResizeObserver error overlay in dev

.github/workflows/prod-mobile-service-worker.yml, .github/workflows/pull_requests_and_merges.yml
master: latest (new)
production: pegged to commit hash (status quo)
=> mobile service worker production deployment adjustments

packages/app-mobile/src/components/index.tsx, packages/tamagui-core/src/components/ApproveTransactionBottomSheet.tsx, packages/tamagui-core/src/components/TwoButtonFooter.tsx, packages/tamagui-core/src/components/index.tsx
example:
- creates tamagui component using tamagui elements
- moves something from mobile into tamagui
=> approve transacation bottom sheet

packages/app-extension/src/components/common/Account/PrivateKeyInput.tsx, packages/app-mobile/src/navigation/OnboardingNavigator.tsx, packages/recoil/src/context/OnboardingProvider.tsx, packages/recoil/src/hooks/index.tsx, packages/recoil/src/hooks/useSavePrivateKey.tsx
=> private key input to unblock app testing

package.json, scripts/confirm-before-build-fresh.js
confirms before running the command
=> confirm before running build:fresh

packages/app-mobile/app.config.ts, packages/app-mobile/eas.json, packages/app-mobile/package.json, packages/app-mobile/src/components/BottomSheetViewOptions.tsx, packages/app-mobile/src/components/BottomSheetWalletPicker.tsx, packages/app-mobile/src/components/Icon.tsx, packages/app-mobile/src/components/ListItem.tsx, packages/app-mobile/src/components/WalletSwitcherButton.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/navigation/WalletsNavigator.tsx, packages/app-mobile/src/navigation/components.tsx, packages/app-mobile/src/navigation/types.ts, packages/app-mobile/src/screens/CollectionListScreen.tsx, packages/app-mobile/src/screens/HomeWalletListScreen.tsx, packages/app-mobile/src/screens/RecentActivityScreen.tsx, packages/tamagui-core/src/components/BottomSheet.tsx, packages/tamagui-core/src/components/index.tsx
- fixes staging/production graphql api
- adds preview simulation
- adds easy deployment script
- adds bottom sheet view options modal placeholder 
- adds HeaderButtonDropdown for Balances dropdown, etc
- fixes prices in the wallets bottom sheet
- updates design of wallet switcher button to match design better
- adds error boundaries around bottom sheets
=> mobile adjustments

packages/app-mobile/eas.json, packages/app-mobile/package.json, packages/app-mobile/src/components/BottomSheetWalletPicker.tsx, packages/app-mobile/src/components/Icon.tsx, packages/app-mobile/src/components/UserAvatar.tsx, packages/app-mobile/src/navigation/FriendsNavigator.tsx, packages/app-mobile/src/navigation/GlobalDrawerContent.tsx, packages/app-mobile/src/navigation/RootNavigator.tsx, packages/app-mobile/src/navigation/WalletsNavigator.tsx, packages/app-mobile/src/screens/CollectionDetailScreen.tsx, packages/app-mobile/src/screens/CollectionListScreen.tsx, packages/app-mobile/src/screens/FriendListScreen.tsx, packages/app-mobile/src/screens/HomeWalletListScreen.tsx, packages/app-mobile/src/screens/NotificationsScreen.tsx, packages/app-mobile/src/screens/RecentActivityScreen.tsx, packages/app-mobile/src/screens/TokenListScreen.tsx, packages/app-mobile/src/screens/Unlocked/EditWalletsScreen.tsx, packages/tamagui-core/src/components/Button.tsx, packages/tamagui-core/src/tokens.ts, yarn.lock
- fix friends navigator
- updates icon menu color
- better drawer navigation ui
- root navigator clean up
- fix more screens with bad list padding
- adds iconBefore to LinkButton
=> ux updates

packages/app-mobile/src/components/AccountSettingsBottomSheet.tsx, packages/app-mobile/src/components/Icon.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx, packages/app-mobile/src/navigation/LockedNavigator.tsx, packages/app-mobile/src/screens/Unlocked/Settings/AboutBackpackScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsList.tsx, packages/tamagui-core/src/components/ListItem.tsx
adds about page and splits settings navigation into groups
tightening things up visually and refactoring the code to share more components will come later
=> add about backpack page to mobile app

packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx, packages/app-mobile/src/screens/Unlocked/Settings/PreferencesScreen.tsx
- developer mode toggle
- dark mode toggle
- trusted sites settings
- custom rpc settings
to be reintroduced later
=> remove unused mobile settings

packages/app-mobile/app.config.ts, packages/app-mobile/eas.json, packages/app-mobile/package.json, packages/app-mobile/src/App.tsx, packages/app-mobile/src/components/BottomSheetWalletPicker.tsx, packages/app-mobile/src/components/LoadingStates.tsx, packages/app-mobile/src/navigation/WalletsNavigator.tsx, packages/app-mobile/src/screens/BrowserScreen.tsx, packages/app-mobile/src/screens/CollectionDetailScreen.tsx, packages/app-mobile/src/screens/CollectionItemDetailScreen.tsx, packages/app-mobile/src/screens/CollectionListScreen.tsx, packages/app-mobile/src/screens/HomeWalletListScreen.tsx, packages/app-mobile/src/screens/RecentActivityScreen.tsx, packages/app-mobile/src/screens/TokenListScreen.tsx, packages/app-mobile/src/screens/Unlocked/SwapTokenScreen.tsx, packages/app-mobile/src/screens/Unlocked/components/BalanceSummaryWidget.tsx, packages/tamagui-core/src/tokens.ts, yarn.lock
- cleans up environment script in app.config
- bumps apollo client to beta.3
- sets statusbar to dark
- renames useSuspenseQuery_experimental to useSuspenseQuery (same with fragments)
- adds various "better" loading indicators to home wallet list and collection list
- overflow bottom tab scroll
- dims swap "you receive" when its updating it
=> visual adjustments

packages/app-mobile/src/components/BottomDrawerCards.tsx, packages/app-mobile/src/components/BottomDrawerSolanaConfirmation.tsx, packages/app-mobile/src/components/BottomSheetWalletPicker.tsx, packages/app-mobile/src/components/ListItem.tsx, packages/app-mobile/src/components/TokenAmountHeader.tsx, packages/app-mobile/src/components/WalletSwitcherButton.tsx, packages/app-mobile/src/components/index.tsx
- fixes nav flows (uncomment when tab is back)
- fix styling of bottom sheet card
- fix edit wallet settings
- ...
=> ux + ui nav flow fixes

packages/app-mobile/src/components/BottomSheetWalletPicker.tsx, packages/app-mobile/src/screens/FriendListScreen.tsx
- fix loading indicator on bottom sheet wallet picker
- update placeholder
=> various ux

packages/common/package.json, packages/common/tsconfig.json, packages/common/tsconfig.prod.json
a lot of the times esm fucks up react-native so i switched this around a bit. should work better
=> cleans up tsconfig for react-native

packages/app-mobile/package.json, packages/app-mobile/src/components/AccountSettingsBottomSheet.tsx, packages/app-mobile/src/components/Form.tsx, packages/app-mobile/src/components/ListItem.tsx, packages/app-mobile/src/components/MnemonicInputFields.tsx, packages/app-mobile/src/components/StyledTextInput.tsx, packages/app-mobile/src/components/index.tsx, packages/app-mobile/src/features/warning/index.tsx, packages/app-mobile/src/navigation/AccountSettingsNavigator.tsx, packages/app-mobile/src/navigation/OnboardingNavigator.tsx, packages/app-mobile/src/navigation/UnlockedNavigator.tsx, packages/app-mobile/src/navigation/components.tsx, packages/app-mobile/src/screens/ResetWarningScreen.tsx, packages/app-mobile/src/screens/Unlocked/EditWalletDetailScreen.tsx, packages/app-mobile/src/screens/Unlocked/EditWalletsScreen.tsx, packages/app-mobile/src/screens/Unlocked/RenameWalletScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/AboutBackpackScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/PreferencesScreen.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsMenuList.tsx, packages/app-mobile/src/screens/Unlocked/Settings/components/SettingsRow.tsx, packages/app-mobile/src/screens/Unlocked/ShowPrivateKeyScreen.tsx, packages/app-mobile/src/screens/Unlocked/ShowRecoveryPhraseScreen.tsx, packages/tamagui-core/src/components/ListItem.tsx, packages/tamagui-core/src/components/RoundedContainerGroup.tsx, packages/tamagui-core/src/tokens.ts, yarn.lock
- increase avatar size, stop autofocusing mnemonic
- adds keyboard avoiding
- various changes to settings
=> misc updates

.github/workflows/backpack-ws.yml
=> Added more secrets to ws
